### ISSUE TITLE
[TC-MF-1.1*] Commisionee app crash on third commission attempt. 

### ISSUE THREAD

**Issue by AntonGrey** [project-chip/connectedhomeip#10847]
#### DUT app crash while perform TC-MF-1.1* test cases. This only affected the MIPS platform. 
 * Expected: DUT should be commissioned on third fabric
 * Actual behavior: DUT app crash on replying to DNS-SD service request
 * Steps to reproduce
    1. CR_1(commissioner 1) starts a commissioning process with DUT
    2. CR_1 open commissioning window using ECM or BCM
    3. CR_2 starts a commissioning process with DUT
    4. CR_1 open commissioning window using ECM or BCM
    5. CR_3 starts a commissioning process with DUT

 * System configuration: MIPS, Linux, Musl libc

Crash stack trace:
```
(gdb) bt
#0  strlen (s=0x11060 <error: Cannot access memory at address 0x11060>) at src/string/strlen.c:17
#1  0x0044e625 in mdns::Minimal::TxtResourceRecord::WriteData (this=0x7d43c0, out=...) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/lib/mdns/minimal/records/Txt.h:59
#2  0x00497c79 in mdns::Minimal::ResourceRecord::Append (this=0x7d43c0, hdr=..., asType=mdns::Minimal::ResourceType::kAdditional, out=...)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/lib/mdns/minimal/records/ResourceRecord.cpp:47
#3  0x004509df in mdns::Minimal::ResponseBuilder::AddRecord (record=..., type=<optimized out>, this=0x583314 <chip::Mdns::(anonymous namespace)::gAdvertiser+3220>)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/lib/mdns/minimal/ResponseBuilder.h:82
#4  mdns::Minimal::ResponseSender::AddResponse (this=0x5832f0 <chip::Mdns::(anonymous namespace)::gAdvertiser+3184>, record=...) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/lib/mdns/minimal/ResponseSender.cpp:214
#5  0x00450b7b in mdns::Minimal::ResponseSender::AddResponse (this=0x5832f0 <chip::Mdns::(anonymous namespace)::gAdvertiser+3184>, record=...)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/lib/mdns/minimal/ResponseSender.cpp:205
#6  0x0044e475 in mdns::Minimal::TxtResponder::AddAllResponses (this=<optimized out>, source=<optimized out>, delegate=<optimized out>) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/lib/mdns/minimal/responders/Txt.h:33
#7  0x0045050b in mdns::Minimal::ResponseSender::Respond (this=0x5832f0 <chip::Mdns::(anonymous namespace)::gAdvertiser+3184>, messageId=0, query=..., querySource=0x77a15f04)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/lib/mdns/minimal/ResponseSender.cpp:149
#8  0x0044ac6f in chip::Mdns::(anonymous namespace)::AdvertiserMinMdns::AdvertiseRecords (this=0x582680 <chip::Mdns::(anonymous namespace)::gAdvertiser>)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:795
#9  0x0044c9e9 in chip::Mdns::(anonymous namespace)::AdvertiserMinMdns::Advertise (this=<optimized out>, params=...) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:426
#10 0x004470e3 in chip::app::MdnsServer::AdvertiseOperational (this=0x57c010 <chip::app::MdnsServer::Instance()::instance>) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/app/server/Mdns.cpp:273
#11 0x00446921 in chip::CommissioningWindowManager::OnPlatformEvent (this=<optimized out>, event=<optimized out>) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/app/server/CommissioningWindowManager.cpp:63
#12 0x00446961 in (anonymous namespace)::OnPlatformEventWrapper (event=<optimized out>, arg=<optimized out>) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/app/server/CommissioningWindowManager.cpp:39
#13 0x0045a17f in chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::DispatchEventToApplication (this=<optimized out>, event=0x77a16298)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/include/platform/internal/GenericPlatformManagerImpl.cpp:305
#14 0x0045a25b in chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::_DispatchEvent (this=<optimized out>, event=0x77a16298)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/include/platform/internal/GenericPlatformManagerImpl.cpp:252
#15 0x004c4a2f in chip::DeviceLayer::PlatformManager::DispatchEvent (event=0x77a16298, this=<optimized out>) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/include/platform/PlatformManager.h:383
#16 chip::DeviceLayer::Internal::DeviceControlServer::EnableNetworkForOperational (this=<optimized out>, networkID=...) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/platform/DeviceControlServer.cpp:108
#17 0x004c4c63 in chip::app::clusters::NetworkCommissioning::OnEnableNetworkCommandCallbackInternal (networkID=..., breadcrumb=8, timeoutMs=3000)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/app/clusters/network-commissioning/network-commissioning.cpp:288
#18 0x004c43f1 in emberAfNetworkCommissioningClusterEnableNetworkCallback (endpoint=<optimized out>, commandObj=<optimized out>, networkID=..., breadcrumb=8, timeoutMs=3000)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/app/clusters/network-commissioning/network-commissioning-ember.cpp:60
#19 0x004c26cd in chip::app::clusters::NetworkCommissioning::DispatchServerCommand (apCommandObj=<optimized out>, aCommandId=<optimized out>, aEndpointId=<optimized out>, aDataTlv=...)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/cluster/zap-generated/IMClusterCommandHandler.cpp:3159
#20 0x004c3dbb in chip::app::DispatchSingleClusterCommand (aClusterId=<optimized out>, aCommandId=<optimized out>, aEndPointId=<optimized out>, aReader=..., apCommandObj=0x589e1c <chip::app::sInteractionModelEngine+12>)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/cluster/zap-generated/IMClusterCommandHandler.cpp:4591
#21 0x004b4141 in chip::app::CommandHandler::ProcessCommandDataElement (this=<optimized out>, aCommandElement=...) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/app/CommandHandler.cpp:106
#22 0x00472245 in chip::app::Command::ProcessCommandMessage (this=<optimized out>, payload=..., aCommandRoleId=<optimized out>) at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/app/Command.cpp:112
#23 0x004b4373 in chip::app::CommandHandler::OnInvokeCommandRequest (this=0x589e1c <chip::app::sInteractionModelEngine+12>, ec=0x5813b8 <chip::Server::sServer+3704>, payloadHeader=..., payload=...)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/app/CommandHandler.cpp:48
#24 0x0047378b in chip::app::InteractionModelEngine::OnInvokeCommandRequest (this=<optimized out>, apExchangeContext=<optimized out>, aPayloadHeader=..., aPayload=...)
    at /home/anton/Documents/Work/hue-bridge/hue/openwrt/build_dir/target-mips_24kc_musl/connectedhomeip-1.0.0/src/app/InteractionModelEngine.cpp:215
#25 0x00473bc5 in chip::app::InteractionModelEngine::OnMessageReceived (this=<optimized out>, apExchangeContext=<optimized out>, aPayloadHeader=..., aPayload=...)
```
[MF-1.13_fail.log](https://github.com/project-chip/connectedhomeip/files/7397831/MF-1.13_fail.log)
[MF-1.1* dut_crash.log](https://github.com/project-chip/connectedhomeip/files/7397837/MF-1.1.dut_crash.log)

**Comment by AntonGrey** [comment]
The issue is not reproducible on branch test_event_7.
