### ISSUE TITLE
failed in Setting up Python environment....

### ISSUE THREAD

**Issue by iot-lorawan** [project-chip/connectedhomeip#12353]
Hi.
     when build matter according buiding guide, it always failed in Setting up Python environment...., the log is:

  WELCOME TO...

  ▄███?  ?▓█  ?▓█ ?▓█▓ ?█████▄
 ██? ?█?  ?█   ?█  ?█?  ?█?  █?
 █▓?      ?██████  ?█?  ?█▄▄▄█?
 ▓█   █?  ?█   ?█  ?█?  ?█?
 ?▓███?  ?▓███?▓█? ?█?  ?█

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...done (10.0s)
  Setting up Python environment.....[\]
ninja: Entering directory `/mnt/e/ProjectCode/matter/connectedhomeip/.environment/gn_out'
[1/45] python3 ../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../../third_party/pigweed/repo/pw_package/py --default-toolchain=//build/toolchain/linux:linux_x64_gcc --current-toolchain=//third_party/pigweed/repo/pw_build/python_toolchain:python --touch python/gen/third_party/pigweed/repo/pw_package/py/py._run_pip_install.pw_pystamp --capture-output --module pip -- install --constraint ../../scripts/constraints.txt --editable ../../third_party/pigweed/repo/pw_package/py
[2/45] touch python/obj/third_party/pigweed/repo/pw_package/py/py._run_pip_install.stamp
[3/45] touch python/obj/third_party/pigweed/repo/pw_package/py/py.install.stamp
[4/45] python3 ../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../../third_party/pigweed/repo/pw_protobuf --default-toolchain=//build/toolchain/linux:linux_x64_gcc --current-toolchain=//third_party/pigweed/repo/pw_build/python_toolchain:python --touch python/gen/third_party/pigweed/repo/pw_protobuf/common_protos.python._run_pip_install.pw_pystamp --capture-output --module pip -- install --constraint ../../scripts/constraints.txt python/gen/third_party/pigweed/repo/pw_protobuf/common_protos.python.generated_python_package
FAILED: python/gen/third_party/pigweed/repo/pw_protobuf/common_protos.python._run_pip_install.pw_pystamp
python3 ../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../../third_party/pigweed/repo/pw_protobuf --default-toolchain=//build/toolchain/linux:linux_x64_gcc --current-toolchain=//third_party/pigweed/repo/pw_build/python_toolchain:python --touch python/gen/third_party/pigweed/repo/pw_protobuf/common_protos.python._run_pip_install.pw_pystamp --capture-output --module pip -- install --constraint ../../scripts/constraints.txt python/gen/third_party/pigweed/repo/pw_protobuf/common_protos.python.generated_python_package
Processing ./python/gen/third_party/pigweed/repo/pw_protobuf/common_protos.python.generated_python_package
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: pw-protobuf-protos
  Building wheel for pw-protobuf-protos (pyproject.toml): started
  Building wheel for pw-protobuf-protos (pyproject.toml): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /mnt/e/ProjectCode/matter/connectedhomeip/.environment/pigweed-venv/bin/python3 /mnt/e/ProjectCode/matter/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmptm0102tc
       cwd: /mnt/e/ProjectCode/matter/connectedhomeip/.environment/gn_out/python/gen/third_party/pigweed/repo/pw_protobuf/common_protos.python.generated_python_package
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  running install_egg_info
  running egg_info
  writing pw_protobuf_protos.egg-info/PKG-INFO
  writing dependency_links to pw_protobuf_protos.egg-info/dependency_links.txt
  writing top-level names to pw_protobuf_protos.egg-info/top_level.txt
  reading manifest file 'pw_protobuf_protos.egg-info/SOURCES.txt'
  writing manifest file 'pw_protobuf_protos.egg-info/SOURCES.txt'
  removing 'build/bdist.linux-x86_64/wheel/pw_protobuf_protos-0.0.1-py3.8.egg-info' (and everything under it)
  Copying pw_protobuf_protos.egg-info to build/bdist.linux-x86_64/wheel/pw_protobuf_protos-0.0.1-py3.8.egg-info
  running install_scripts
  error: [('build/bdist.linux-x86_64/wheel/pw_protobuf_protos-0.0.1-py3.8.egg-info', 'build/bdist.linux-x86_64/wheel/pw_protobuf_protos-0.0.1.dist-info', "[Errno 13] Permission denied: 'build/bdist.linux-x86_64/wheel/pw_protobuf_protos-0.0.1.dist-info'")]
  ----------------------------------------
  ERROR: Failed building wheel for pw-protobuf-protos
Failed to build pw-protobuf-protos
ERROR: Could not build wheels for pw-protobuf-protos, which is required to install pyproject.toml-based projects
ninja: build stopped: subcommand failed.
['ninja', '-C', '/mnt/e/ProjectCode/matter/connectedhomeip/.environment/gn_out', '-v', ':python_packages.install']

Traceback (most recent call last):
  File "/mnt/e/ProjectCode/matter/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 279, in install_packages
    subprocess.check_call(ninja_cmd, stdout=outs, stderr=outs)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', '/mnt/e/ProjectCode/matter/connectedhomeip/.environment/gn_out', '-v', ':python_packages.install']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/e/ProjectCode/matter/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 679, in <module>
    sys.exit(main())
  File "/mnt/e/ProjectCode/matter/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 671, in main
    return EnvSetup(**vars(parse())).setup()
  File "/mnt/e/ProjectCode/matter/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 414, in setup
    result = step(spin)
  File "/mnt/e/ProjectCode/matter/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 533, in virtualenv
    if not virtualenv_setup.install(
  File "/mnt/e/ProjectCode/matter/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 294, in install
    install_packages(gn_target)
  File "/mnt/e/ProjectCode/matter/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 282, in install_packages
    raise subprocess.CalledProcessError(err.returncode, err.cmd,
subprocess.CalledProcessError: Command '['ninja', '-C', '/mnt/e/ProjectCode/matter/connectedhomeip/.environment/gn_out', '-v', ':python_packages.install']' returned non-zero exit status 1.

Best Regards,

**Comment by iot-lorawan** [comment]
it can be fixed  when install ubuntu2004 in virtualbox
