### ISSUE TITLE
See the crash in python mobile device test

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#12707]
#### Problem
See the crash in python mobile device test
[1638907511.070443][4361:4367] CHIP:DMG: },
[1638907511.070461][4361:4367] CHIP:DMG: Received Command Response Status for Endpoint=1 Cluster=0x0000_0008 Command=0x0000_0000 Status=0x0
[1638907511.070658][4361:4367] CHIP:DMG: ICR moving to [AwaitingDe]
[1638907511.071092][4361:4367] CHIP:EM: Sending Standalone Ack for MessageCounter:1943624 on exchange 58705i
[1638907511.071121][4361:4367] CHIP:IN: Prepared encrypted message 0x7fffefffe100 to 0x0000000000000001 (1)  of type 0x10 and protocolId (0, 0) on exchange 58705i with MessageCounter:6815915.
[1638907511.071132][4361:4367] CHIP:IN: Sending encrypted msg 0x7fffefffe100 with MessageCounter:6815915 to 0x0000000000000001 (1) at monotonic time: 1267583 msec
[1638907511.071169][4361:4367] CHIP:EM: Flushed pending ack for MessageCounter:1943624 on exchange 58705i
[1638907511.071934][4361:4367] CHIP:DMG: SendReadRequest: Client[0] [ INIT]
[1638907511.072002][4361:4367] CHIP:IN: Prepared encrypted message 0x10ae850 to 0x0000000000000001 (1)  of type 0x2 and protocolId (0, 1) on exchange 58706i with MessageCounter:6815916.
[1638907511.072012][4361:4367] CHIP:IN: Sending encrypted msg 0x10ae850 with MessageCounter:6815916 to 0x0000000000000001 (1) at monotonic time: 1267584 msec
[1638907511.072059][4361:4367] CHIP:DMG: Client[0] moving to [AwaitingInitialReport]
[1638907511.273072][4361:4367] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:1943625 on exchange 58706i
[1638907511.273113][4361:4367] CHIP:EM: Found matching exchange: 58706i, Delegate: 0x7ffff5088238
[1638907511.273140][4361:4367] CHIP:EM: Rxd Ack; Removing MessageCounter:6815916 from Retrans Table on exchange 58706i
[1638907511.273144][4361:4367] CHIP:EM: Removed CHIP MessageCounter:6815916 from RetransTable on exchange 58706i
[1638907511.273169][4361:4367] CHIP:DMG: ReportDataMessage =
[1638907511.273175][4361:4367] CHIP:DMG: {
[1638907511.273178][4361:4367] CHIP:DMG: 	AttributeReportIBs =
[1638907511.273185][4361:4367] CHIP:DMG: 	[
[1638907511.273188][4361:4367] CHIP:DMG: 		AttributeReportIB =
[1638907511.273194][4361:4367] CHIP:DMG: 		{
[1638907511.273232][4361:4367] CHIP:DMG: 			AttributeDataIB =
[1638907511.273237][4361:4367] CHIP:DMG: 			{
[1638907511.273242][4361:4367] CHIP:DMG: 				DataVersion = 0x0,
[1638907511.273245][4361:4367] CHIP:DMG: 				AttributePathIB =
[1638907511.273249][4361:4367] CHIP:DMG: 				{
[1638907511.273253][4361:4367] CHIP:DMG: 					Endpoint = 0x1,
[1638907511.273257][4361:4367] CHIP:DMG: 					Cluster = 0x8,
[1638907511.273262][4361:4367] CHIP:DMG: 					Attribute = 0x0000_0000,
[1638907511.273265][4361:4367] CHIP:DMG: 				}
[1638907511.273270][4361:4367] CHIP:DMG: 					
[1638907511.273274][4361:4367] CHIP:DMG: 					Data = 0, 
[1638907511.273277][4361:4367] CHIP:DMG: 			},
[1638907511.273282][4361:4367] CHIP:DMG: 			
[1638907511.273285][4361:4367] CHIP:DMG: 		},
[1638907511.273309][4361:4367] CHIP:DMG: 		
[1638907511.273313][4361:4367] CHIP:DMG: 	],
[1638907511.273318][4361:4367] CHIP:DMG: 	
[1638907511.273322][4361:4367] CHIP:DMG: 	SuppressResponse = true, 
[1638907511.273325][4361:4367] CHIP:DMG: }

Thread 3 "python3" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fffeffff700 (LWP 4367)]
0x00007ffff7ef26dc in send () from /lib/x86_64-linux-gnu/libc.so.6
#0  0x00007ffff7ef26dc in send () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000000623d7a in  ()
#2  0x0000000000627f3a in  ()
#3  0x00000000006285f2 in  ()
#4  0x0000000000504f8d in  ()
#5  0x000000000056bf09 in _PyEval_EvalFrameDefault ()
#6  0x00000000005f6166 in _PyFunction_Vectorcall ()
#7  0x000000000056bf09 in _PyEval_EvalFrameDefault ()
#8  0x000000000056a0ba in _PyEval_EvalCodeWithName ()
#9  0x00000000005f6343 in _PyFunction_Vectorcall ()
#10 0x000000000056bf09 in _PyEval_EvalFrameDefault ()
#11 0x00000000005f6166 in _PyFunction_Vectorcall ()
#12 0x000000000056bf09 in _PyEval_EvalFrameDefault ()
#13 0x00000000005f6166 in _PyFunction_Vectorcall ()
#14 0x00000000005f7667 in PyObject_CallObject ()
#15 0x00007ffff722f3f1 in  ()
    at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#16 0x00007ffff721ce06 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#17 0x00007ffff721d188 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#18 0x00007ffff4e0d159 in chip::python::ReadClientCallback::OnDone(chip::app::ReadClient*)
    (this=0x7fffe8001730, apReadClient=0x7ffff5088238 <chip::app::sInteractionModelEngine+2264>)
    at ../../src/controller/python/chip/clusters/attribute.cpp:165
#19 0x00007ffff4ef97da in chip::app::BufferedReadCallback::OnDone(chip::app::ReadClient*)
    (this=0x7fffe8001738, apReadClient=0x7ffff5088238 <chip::app::sInteractionModelEngine+2264>) at ../../src/app/BufferedReadCallback.h:82
#20 0x00007ffff4f16ac6 in chip::app::ReadClient::ShutdownInternal(chip::ChipError)
    (this=0x7ffff5088238 <chip::app::sInteractionModelEngine+2264>, aError=...)
    at ../../src/app/ReadClient.cpp:70
#21 0x00007ffff4f17fea in chip::app::ReadClient::OnMessageReceived(chip::Messaging::ExchangeContext*, chip::PayloadHeader const&, chip::System::PacketBufferHandle&&)
    (this=0x7ffff5088238 <chip::app::sInteractionModelEngine+2264>, apExchangeContext=0x10ae9a0, aPayloadHeader=..., aPayload=...)
    at ../../src/app/ReadClient.cpp:269
#22 0x00007ffff4f6f13a in chip::Messaging::ExchangeContext::HandleMessage(unsigned int, chip::PayloadHeader const&, chip::Transport::PeerAddress const&, chip::BitFlags<chip::Messaging::MessageFlagValues, unsigned int>, chip::System::PacketBufferHandle&&)
    (this=0x10ae9a0, messageCounter=1943625, payloadHeader=..., peerAddress=..., msgFlags=..., msgBuf=...) at ../../src/messaging/ExchangeContext.cpp:485
#23 0x00007ffff4f7263a in chip::Messaging::ExchangeManager::<lambda(auto:5*)>::operator()<chip::Messaging::ExchangeContext>(chip::Messaging::ExchangeContext *) const (__closure=0x7fffefffe680, ec=0x10ae9a0)
    at ../../src/messaging/ExchangeMgr.cpp:228
#24 0x00007ffff4f72a4a in chip::internal::LambdaProxy<chip::Messaging::ExchangeContext, chip::Messaging::ExchangeManager::OnMessageReceived(const chip::PacketHeader&, const chip::PayloadHeader&, chip::SessionHandle, const chip::Transport::PeerAddress&, chip::SessionMessageDelegate::DuplicateMessage, chip::System::PacketBufferHandle&&)::<lambda(auto:5*)> >::Call(void *, void *)
    (context=0x7fffefffe680, target=0x10ae9a0)
    at ../../src/lib/support/Pool.h:120
#25 0x00007ffff4f6cd86 in chip::internal::StaticAllocatorBitmap::ForEachActiveObjectInner(void*, chip::Loop (*)(void*, void*))
    (this=0x10ae968, context=0x7fffefffe680, lambda=0x7ffff4f72a23 <chip::internal::LambdaProxy<chip::Messaging::ExchangeContext, chip::Messaging::ExchangeManager::OnMessageReceived(const chip::PacketHeader&, const chip::PayloadHeader&, chip::SessionHandle, const chip::Transport::PeerAddress&, chip::SessionMessageDelegate::DuplicateMessage, chip::System::PacketBufferHandle&&)::<lambda(auto:5*)> >::Call(void *, void *)>) at ../../src/lib/support/Pool.cpp:98
#26 0x00007ffff4f726cd in chip::BitMapObjectPool<chip::Messaging::ExchangeContext, 8, (chip::OnObjectPoolDestruction)1>::ForEachActiveObject<chip::Messaging::ExchangeManager::OnMessageReceived(const chip::PacketHeader&, const chip::PayloadHeader&, chip::SessionHandle, const chip::Transport::PeerAddress&, chip::SessionMessageDelegate::DuplicateMessage, chip::System::PacketBufferHandle&&)::<lambda(auto:5*)> >(chip::Messaging::ExchangeManager::<lambda(auto:5*)> &&)
    (this=0x10ae968, function=...) at ../../src/lib/support/Pool.h:265
#27 0x00007ffff4f71b25 in chip::Messaging::ExchangeManager::OnMessageReceived(chip::PacketHeader const&, chip::PayloadHeader const&, chip::SessionHandle, chip::Transport::PeerAddress const&, chip::SessionMessageDelegate::DuplicateMessage, chip::System::PacketBufferHandle&&)
    (this=0x10ae7e0, packetHeader=..., payloadHeader=..., session=..., source=..., isDuplicate=chip::SessionMessageDelegate::DuplicateMessage::No, msgBuf=...) at ../../src/messaging/ExchangeMgr.cpp:214
#28 0x00007ffff4f8d390 in chip::SessionManager::SecureUnicastMessageDispatch(chip::PacketHeader const&, chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&)
    (this=0x10ad9f0, packetHeader=..., peerAddress=..., msg=...)
    at ../../src/transport/SessionManager.cpp:534
#29 0x00007ffff4f8c70f in chip::SessionManager::OnMessageReceived(chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&)
    (this=0x10ad9f0, peerAddress=..., msg=...)
    at ../../src/transport/SessionManager.cpp:377
#30 0x00007ffff4f8f55b in chip::TransportMgrBase::HandleMessageReceived(chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&)
    (this=0xbc6d80, peerAddress=..., msg=...)
    at ../../src/transport/TransportMgrBase.cpp:71
#31 0x00007ffff4ff80bb in chip::Transport::Base::HandleMessageReceived(chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&)
    (this=0xbc6e10, source=..., buffer=...)
    at ../../src/transport/raw/Base.h:102
#32 0x00007ffff4ff888e in chip::Transport::UDP::OnUdpReceive(chip::Inet::UDPEndPoint*, chip::System::PacketBufferHandle&&, chip::Inet::IPPacketInfo const*)
    (endPoint=0xb69b00, buffer=..., pktInfo=0x7fffefffec10)
    at ../../src/transport/raw/UDP.cpp:120
#33 0x00007ffff50279c8 in chip::Inet::UDPEndPointImplSockets::HandlePendingIO(chip::BitFlags<chip::System::SocketEventFlags, unsigned char>)
    (this=0xb69b00, events=...) at ../../src/inet/UDPEndPoint.cpp:1309
#34 0x00007ffff5027236 in chip::Inet::UDPEndPointImplSockets::HandlePendingIO(chip::BitFlags<chip::System::SocketEventFlags, unsigned char>, long)
    (events=..., data=11967232) at ../../src/inet/UDPEndPoint.cpp:1190
#35 0x00007ffff4f8667a in chip::System::LayerImplSelect::HandleEvents()
    (this=0x7ffff50899e0 <chip::DeviceLayer::SystemLayerImpl()::gSystemLayerImpl>) at ../../src/system/SystemLayerImplSelect.cpp:402
#36 0x00007ffff4f971a0 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl_POSIX<chip::DeviceLayer::PlatformManagerImpl>::_RunEventLoop()
    (this=0x7ffff508a428 <chip::DeviceLayer::PlatformManagerImpl::sInstance+8>) at ../../src/include/platform/internal/GenericPlatformManagerImpl_POSIX.cpp:181
#37 0x00007ffff4e15768 in chip::DeviceLayer::PlatformManager::RunEventLoop()
    (this=0x7ffff508a420 <chip::DeviceLayer::PlatformManagerImpl::sInstance>)
    at ../../src/include/platform/PlatformManager.h:314
#38 0x00007ffff4e157a3 in (anonymous namespace)::PlatformMainLoop(void*) ()
    at ../../src/controller/python/chip/native/StackInit.cpp:36
#39 0x00007ffff7db5609 in start_thread ()
    at /lib/x86_64-linux-gnu/libpthread.so.0
#40 0x00007ffff7ef1293 in clone () at /lib/x86_64-linux-gnu/libc.so.6
 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by yunhanw-google** [comment]
[MobileDeviceTest.log](https://github.com/project-chip/connectedhomeip/files/7672422/MobileDeviceTest.log)
[CHIPEndDevice-1638907511-dc079e65.log](https://github.com/project-chip/connectedhomeip/files/7672423/CHIPEndDevice-1638907511-dc079e65.log)

**Comment by yunhanw-google** [comment]
not reproduced.
