### ISSUE TITLE
ZAP: Group Key Management cluster YAML test generation fails

### ISSUE THREAD

**Issue by rcasallas-silabs** [project-chip/connectedhomeip#13119]
#### Problem
Enabling [the YAML tests for the Group Key Management's commands](https://github.com/project-chip/connectedhomeip/blob/d24eff1b14c212bdff9c98aa14255753082543ba/src/app/tests/suites/TestGroupKeyManagementCluster.yaml#L62) yields code generation errors:
```
🤖 Generating files:
    ✍  /git/matter/zzz_generated/chip-tool/zap-generated/cluster/Commands.h
⚠️  Errors:
    👎  /git/matter/zzz_generated/chip-tool/zap-generated/test/Commands.h: ⛔ TypeError: value.replace is not a function [line: 37, column: 51, file: /git/matter/examples/chip-tool/templates/tests-commands.zapt ]
Stack trace:

TypeError: value.replace is not a function [line: 37, column: 51, file: /git/matter/examples/chip-tool/templates/tests-commands.zapt ]
    at Object.octetStringEscapedForCLiteral (/git/matter/src/app/zap-templates/common/ClusterTestGeneration.js:600:16)
    at Object.w (/git/matter/third_party/zap/repo/src-electron/generator/template-engine.js:177:28)
    at Object.helperWrapper (/git/matter/third_party/zap/repo/node_modules/promised-handlebars/index.js:130:23)
    at Object.<anonymous> (/git/matter/third_party/zap/repo/node_modules/promised-handlebars/lib/utils.js:29:28)
    at Object.wrapper (/git/matter/third_party/zap/repo/node_modules/handlebars/lib/handlebars/internal/wrapHelper.js:10:19)
    at eval (eval at createFunctionContext (/git/matter/third_party/zap/repo/node_modules/handlebars/lib/handlebars/compiler/javascript-compiler.js:265:23), <anonymous>:11:175)
    at Object.prog (/git/matter/third_party/zap/repo/node_modules/handlebars/lib/handlebars/runtime.js:333:12)
    at Object.prepareAndResolveMarkers (/git/matter/third_party/zap/repo/node_modules/promised-handlebars/index.js:92:17)
    at Object.fn (/git/matter/third_party/zap/repo/node_modules/promised-handlebars/lib/utils.js:29:28)
    at Object.<anonymous> (/git/matter/third_party/zap/repo/node_modules/handlebars/lib/handlebars/helpers/if.js:19:22)
🕐 Generation time: 4s 949ms
{"test/Commands.h":{}}
Error: Generation failed: /git/matter/src/controller/data_model/controller-clusters.zap
    at generateSingleFile (/git/matter/third_party/zap/repo/src-electron/main-process/startup.js:505:11)
    at startGeneration (/git/matter/third_party/zap/repo/src-electron/main-process/startup.js:571:3)
⇝ Zap generation error: Error: Generation failed: /git/matter/src/controller/data_model/controller-clusters.zap
👎 Program node exited with error code: 1
Traceback (most recent call last):
  File "/git/matter/./scripts/tools/zap/generate.py", line 165, in <module>
    main()
  File "/git/matter/./scripts/tools/zap/generate.py", line 153, in main
    runGeneration(zap_file, zcl_file, templates_file, output_dir)
  File "/git/matter/./scripts/tools/zap/generate.py", line 99, in runGeneration
    subprocess.check_call(['node', './src-script/zap-generate.js', '-z',
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', './src-script/zap-generate.js', '-z', '/git/matter/src/app/zap-templates/zcl/zcl.json', '-g', '/git/matter/examples/chip-tool/templates/templates.json', '-i', '/git/matter/src/controller/data_model/controller-clusters.zap', '-o', '/git/matter/zzz_generated/chip-tool/zap-generated']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/git/matter/./scripts/tools/zap_regen_all.py", line 132, in <module>
    main()
  File "/git/matter/./scripts/tools/zap_regen_all.py", line 128, in main
    subprocess.check_call(exec_list)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./scripts/tools/zap/generate.py', 'src/controller/data_model/controller-clusters.zap', '-t', 'examples/chip-tool/templates/templates.json', '-o', 'zzz_generated/chip-tool/zap-generated']' returned non-zero exit status 1.
```

#### Proposed Solution
None yet.

**Comment by bzbarsky-apple** [comment]
That YAML has arrays in places where the spec says you should have octet strings, that's why.  Fix the yaml?
