### ISSUE TITLE
Exception('Timeout for server listening')

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14332]
#### Problem

https://github.com/project-chip/connectedhomeip/runs/4890259801?check_suite_focus=true

```
2022-01-21 00:53:46.757 ERROR   !!!!!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!!!
83
2022-01-21 00:53:47.184 ERROR   ================ CAPTURED LOG START ==================
84
2022-01-21 00:53:47.285 ERROR   00:53:36.009 - APP       : EXECUTING ['./out/darwin-x64-all-clusters-no-ble-tsan/chip-all-clusters-app', '--discriminator', '1107']
85
2022-01-21 00:53:47.286 ERROR   ================ CAPTURED LOG END ====================
86
2022-01-21 00:53:47.490 ERROR   Test_TC_CC_6_3 - FAILED in 11.48 seconds
87
Traceback (most recent call last):
88
  File "./scripts/tests/run_test_suite.py", line 203, in cmd_run
89
    test.Run(runner, paths)
90
  File "/Users/runner/work/connectedhomeip/connectedhomeip/scripts/tests/chiptest/test_definition.py", line 121, in Run
91
    raise Exception('Timeout for server listening')
92
Exception: Timeout for server listening
93
Error: Process completed with exit code 2.
```

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
Another: https://github.com/project-chip/connectedhomeip/runs/4958933907?check_suite_focus=true

**Comment by woody-apple** [comment]
Another: https://github.com/project-chip/connectedhomeip/runs/4957970081?check_suite_focus=true

**Comment by woody-apple** [comment]
This was identified to be cross talk, and is now resolved.
