### ISSUE TITLE
Fuzzer: Crash found

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14348]
#### Problem
```

==589==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x0001057d26cf bp 0x7ff7ba79da50 sp 0x7ff7ba79da40 T0)
==589==The signal is caused by a READ memory access.
==589==Hint: address points to the zero page.
#0 0x1057d26cf in chip::System::PacketBuffer::Start() const+0x4f
#1 0x10621e31d in chip::PacketHeader::DecodeAndConsume(chip::System::PacketBufferHandle const&)+0x19d
#2 0x106186a19 in chip::SessionManager::OnMessageReceived(chip::Transport::PeerAddress const&, chip::System::PacketBufferHandle&&)+0x1b9
#3 0x10578e1f5 in XXXX+0x5c5
#4 0x10630f4b1 in XXXX::XXXX::ExecuteCallback(unsigned char const*, unsigned long)+0x121
#5 0x1062f95e2 in XXXX::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long)+0xe2
#6 0x1062ffa74 in XXXX::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x2114

==589==Register values:
rax = 0x0000000000000008  rbx = 0x00007ff7ba79dae0  rcx = 0x0000100000000000  rdx = 0x00007ff7ba79dc00
rdi = 0x0000000000000000  rsi = 0x00007ff7ba79dc00  rbp = 0x00007ff7ba79da50  rsp = 0x00007ff7ba79da40
r8 = 0xf2f2f2f2f2f8f801   r9 = 0x0000000000000002  r10 = 0x00000000ffffff00  r11 = 0x00007ff85492f400
r12 = 0x0000624000002100  r13 = 0x00000001065ddc00  r14 = 0x0000624000004100  r15 = 0x0000000000001bec
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (XXXX:x86_64+0x1000716cf) in chip::System::PacketBuffer::Start() const+0x4f
==589==ABORTING
```
 #### Proposed Solution
Fix

**Comment by bzbarsky-apple** [comment]
@woody For future reference, attaching the .tc file would be helpful in terms of diagnosing these.  ;)

Given that file, the steps to reproduce are to run:
```
% ./scripts/run_in_build_env.sh "./scripts/build/build_examples.py --target darwin-x64-all-clusters-no-ble-asan-libfuzzer build"
% ./out/darwin-x64-all-clusters-no-ble-asan-libfuzzer/chip-all-clusters-app-fuzzing tc-file-name.tc
```
