### ISSUE TITLE
CIPD failed

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14346]
#### Problem
https://github.com/project-chip/connectedhomeip/runs/4902085778?check_suite_focus=true

```
  File "/__w/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 269, in install_packages
34
ERROR at //build/chip/java/rules.gni:23:1: Assertion failed.
35
    subprocess.check_call(gn_cmd,
36
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
37
    raise CalledProcessError(retcode, cmd)
38
subprocess.CalledProcessError: Command '['gn', 'gen', '/__w/connectedhomeip/connectedhomeip/.environment/gn_out', '--args=dir_pigweed="/__w/connectedhomeip/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.
39

40
During handling of the above exception, another exception occurred:
41

42
Traceback (most recent call last):
43
  File "/__w/connectedhomeip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 715, in <module>
44
assert(android_sdk_root != "", "android_sdk_root must be specified")
45
^-----
46
android_sdk_root must be specified
47
See //src/platform/android/BUILD.gn:21:1: whence it was imported.
48
import("${chip_root}/build/chip/java/rules.gni")
49
^----------------------------------------------
50
See //src/controller/data_model/BUILD.gn:63:5: which caused the file to be included.
51
    "${chip_root}/src/platform/android",
52
    ^----------------------------------
53
['gn', 'gen', '/__w/connectedhomeip/connectedhomeip/.environment/gn_out', '--args=dir_pigweed="/__w/connectedhomeip/connectedhomeip/third_party/pigweed/repo"']
54
```

 #### Proposed Solution
Fix

**Comment by andy31415** [comment]
I have not seen android fail in a while now. `assert(android_sdk_root != "", "android_sdk_root must be specified")` seems to say that sdk root is undefined which does not seem to be the case now.

Closing as obsolete for now.
