### ISSUE TITLE
Multiple problems with ZAP configuration/generation

### ISSUE THREAD

**Issue by caipiblack** [project-chip/connectedhomeip#15619]
#### Problem

First, I am on this commit: 2aab9b86b7bd9cfcd51d2af13b2586563854ee43  (Sat Feb 26 08:13:18 2022 -0500)

Multiple problems with .zap files, the configuration tool and generator tool.

1. I had a problem using an existing zap file after connectedhomeip update, as `OpCSRRequest` has been renamed. The name was correct in .zap file but the generated files was still generating code with `OpCSRRequest` inside. So errors was generated during the build of my project.

2. Since a lot of time (always ?) Attribute List attributes are not selected in .zap files of the examples, if we select it there are errors in the generated files. This attribute appear as "mandatory" in the configuration tool but is disabled in all clusters (on examples). (It's not really important as it works (usually) without this, but i would like to know **if have to select it or not**)

3. Since a recent commit in less than 2-3 weeks, the configuration tool display duplicates attributes we have the same problem when creating an endpoint. It generate wrong data in the .zap file, and the generation "fails"

![capture_1](https://user-images.githubusercontent.com/29680146/155876109-746956b0-ba44-4810-97e4-92f96240bce4.png)
![capture_2](https://user-images.githubusercontent.com/29680146/155876115-8d3ea3a4-e2aa-417d-b1f4-1d85e065ddd2.png)

5. I don't know if this is related but when we create a fresh .zap file it also fails:
- Open the ZAP configuration tool
- Create a new zap configuration
- Add a "Matter Root Node" at endpoint 0
- Add a "Matter Temperature Sensor" at endpoint 1
- Close the configuration tool
- Call the script to generate zap files
- 
_This is a simple test you can do to check what i write_

```
$ ./scripts/tools/zap/generate.py /home/user/git/matter-weather-sensor/nrf52-eink/src/modules/matter/weather_sensor_2.zap 
🚀 Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
🔍 Git commit: aeaa21a71496f3c002e3781b68964fb09d1fa3fc from Fri Feb 04 2022 03:21:40 GMT+0100 (heure normale d’Europe centrale)
🚀 Executing: npm run build-backend

> zap@2022.2.4 build-backend /home/user/git/connectedhomeip/third_party/zap/repo
> npx tsc --build ./tsconfig.json

🚀 Executing: node dist/src-electron/main-process/electron-main.js generate --noUi --noServer --stateDirectory ~/.zap --zcl /home/user/git/connectedhomeip/src/app/zap-templates/zcl/zcl.json --generationTemplate /home/user/git/connectedhomeip/src/app/zap-templates/app-templates.json --out /home/user/git/matter-weather-sensor/nrf52-eink/src/modules/matter/zap-generated/ /home/user/git/matter-weather-sensor/nrf52-eink/src/modules/matter/weather_sensor_2.zap
🤖 ZAP generation started: 
    🔍 input files: /home/user/git/matter-weather-sensor/nrf52-eink/src/modules/matter/weather_sensor_2.zap
    🔍 output pattern: /home/user/git/matter-weather-sensor/nrf52-eink/src/modules/matter/zap-generated/
    🔍 using templates: /home/user/git/connectedhomeip/src/app/zap-templates/app-templates.json
    🔍 using zcl data: /home/user/git/connectedhomeip/src/app/zap-templates/zcl/zcl.json
    🔍 zap version: ver. 2022.2.4, featureLevel 67, commit: aeaa21a71496f3c002e3781b68964fb09d1fa3fc from 2022-02-04T02:21:40.000Z
🕐 Setup time: 10s 821ms 
👉 using input file: /home/user/git/matter-weather-sensor/nrf52-eink/src/modules/matter/weather_sensor_2.zap
[Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: ENDPOINT_TYPE_ATTRIBUTE.ENDPOINT_TYPE_REF, ENDPOINT_TYPE_ATTRIBUTE.ATTRIBUTE_REF, ENDPOINT_TYPE_ATTRIBUTE.ENDPOINT_TYPE_CLUSTER_REF] {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}
⇝ Zap generation error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: ENDPOINT_TYPE_ATTRIBUTE.ENDPOINT_TYPE_REF, ENDPOINT_TYPE_ATTRIBUTE.ATTRIBUTE_REF, ENDPOINT_TYPE_ATTRIBUTE.ENDPOINT_TYPE_CLUSTER_REF
👎 Program node exited with error code: 1
Traceback (most recent call last):
  File "./scripts/tools/zap/generate.py", line 186, in <module>
    main()
  File "./scripts/tools/zap/generate.py", line 174, in main
    runGeneration(zap_file, zcl_file, templates_file, output_dir)
  File "./scripts/tools/zap/generate.py", line 118, in runGeneration
    subprocess.check_call(['node', './src-script/zap-generate.js', '-z',
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', './src-script/zap-generate.js', '-z', '/home/user/git/connectedhomeip/src/app/zap-templates/zcl/zcl.json', '-g', '/home/user/git/connectedhomeip/src/app/zap-templates/app-templates.json', '-i', '/home/user/git/matter-weather-sensor/nrf52-eink/src/modules/matter/weather_sensor_2.zap', '-o', '/home/user/git/matter-weather-sensor/nrf52-eink/src/modules/matter/zap-generated/']' returned non-zero exit status 1.
```

**Comment by caipiblack** [comment]
The point 5 is maybe related to the fact that everything is duplicated in .zap file. So yeah unique things are not unique. 

Any idea why everything is duplicated 18 times ?

**Comment by caipiblack** [comment]
I close the issue because I don't have the problem with recent commits
