### ISSUE TITLE
Minimal mDNS crasher in Cirque multi fabric test

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#15688]
#### Problem

The Cirque MultiFabric test seems to resulting in an excessively high number of crashes on master:

```
[1646157567.930636][4348:4353] CHIP:CTL: Joined the fabric at index 2. Compressed fabric ID is: 0xF61816BB50272937
[1646157567.930700][4348:4353] CHIP:DL: Using wifi MAC for hostname
[1646157567.930713][4348:4353] CHIP:DIS: Advertise operational node D953C42240C3D9E0-000000000001B669
[1646157567.930731][4348:4353] CHIP:DIS: CHIP minimal mDNS configured as 'Operational device'.
[1646157567.930944][4348:4353] CHIP:DIS: Broadcasting mDns reply for query from 172.20.0.2

Thread 2 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3ad7700 (LWP 4353)]
0x00007ffff7f5a675 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#0  0x00007ffff7f5a675 in  () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4844b36 in mdns::Minimal::TxtResourceRecord::WriteData(mdns::Minimal::RecordWriter&) const (this=0x7fffe4029f80, out=...)
    at ../../src/lib/dnssd/minimal_mdns/records/Txt.h:59
#2  0x00007ffff48650a7 in mdns::Minimal::ResourceRecord::Append(mdns::Minimal::HeaderRef&, mdns::Minimal::ResourceType, mdns::Minimal::RecordWriter&) const
    (this=0x7fffe4029f80, hdr=..., asType=mdns::Minimal::ResourceType::kAdditional, out=...)
    at ../../src/lib/dnssd/minimal_mdns/records/ResourceRecord.cpp:47
#3  0x00007ffff486228d in mdns::Minimal::ResponseBuilder::AddRecord(mdns::Minimal::ResourceType, mdns::Minimal::ResourceRecord const&)
    (this=0x7ffff48b8380 <chip::Dnssd::(anonymous namespace)::gAdvertiser+5472>, type=mdns::Minimal::ResourceType::kAdditional, record=...)
    at ../../src/lib/dnssd/minimal_mdns/ResponseBuilder.h:91
#4  0x00007ffff4863ab7 in mdns::Minimal::ResponseSender::AddResponse(mdns::Minimal::ResourceRecord const&)
    (this=0x7ffff48b8338 <chip::Dnssd::(anonymous namespace)::gAdvertiser+5400>, record=...) at ../../src/lib/dnssd/minimal_mdns/ResponseSender.cpp:216
#5  0x00007ffff4844c94 in mdns::Minimal::TxtResponder::AddAllResponses(chip::Inet::IPPacketInfo const*, mdns::Minimal::ResponderDelegate*)
    (this=0x7fffe4029f60, source=0x7ffff3ad53e0, delegate=0x7ffff48b8338 <chip::Dnssd::(anonymous namespace)::gAdvertiser+5400>)
    at ../../src/lib/dnssd/minimal_mdns/responders/Txt.h:33
#6  0x00007ffff4863318 in mdns::Minimal::ResponseSender::Respond(unsigned int, mdns::Minimal::QueryData const&, chip::Inet::IPPacketInfo const*)
    (this=0x7ffff48b8338 <chip::Dnssd::(anonymous namespace)::gAdvertiser+5400>, messageId=0, query=..., querySource=0x7ffff3ad53e0)
    at ../../src/lib/dnssd/minimal_mdns/ResponseSender.cpp:148
#7  0x00007ffff4847c3b in chip::Dnssd::(anonymous namespace)::AdvertiserMinMdns::AdvertiseRecords()
    (this=0x7ffff48b6e20 <chip::Dnssd::(anonymous namespace)::gAdvertiser>)
    at ../../src/lib/dnssd/Advertiser_ImplMinimalMdns.cpp:797
#8  0x00007ffff4845fef in chip::Dnssd::(anonymous namespace)::AdvertiserMinMdns::Advertise(chip::Dnssd::OperationalAdvertisingParameters const&)
    (this=0x7ffff48b6e20 <chip::Dnssd::(anonymous namespace)::gAdvertiser>, params=...) at ../../src/lib/dnssd/Advertiser_ImplMinimalMdns.cpp:421
#9  0x00007ffff4822154 in chip::app::DnssdServer::AdvertiseOperational()
    (this=0x7ffff48b1580 <chip::app::DnssdServer::Instance()::instance>)
    at ../../src/app/server/Dnssd.cpp:285
#10 0x00007ffff4615ee9 in chip::Controller::DeviceController::Init(chip::Controller::ControllerInitParams) (this=0x7fffe402b280, params=...)
    at ../../src/controller/CHIPDeviceController.cpp:151
#11 0x00007ffff4618c32 in chip::Controller::DeviceCommissioner::Init(chip::Controller::CommissionerInitParams) (this=0x7fffe402b280, params=...)
    at ../../src/controller/CHIPDeviceController.cpp:610
#12 0x00007ffff46453c1 in chip::Controller::DeviceControllerFactory::SetupCommissioner(chip::Controller::SetupParams, chip::Controller::DeviceCommissioner&)
    (this=0x7ffff48b1760 <chip::Controller::DeviceControllerFactory::GetInstance()::instance>, params=..., commissioner=...)
    at ../../src/controller/CHIPDeviceControllerFactory.cpp:246
#13 0x00007ffff45358ac in pychip_OpCreds_AllocateController(OpCredsContext*, chip::Controller::DeviceCommissioner**, uint8_t, chip::FabricId, chip::NodeId, bool)
    (context=0x7fffe4021270, outDevCtrl=0x7ffff5b56d90, fabricIndex=2 '\002', fabricId=2, nodeId=112233, useTestCommissioner=false)
    at ../../src/controller/python/OpCredsBinding.cpp:183
#14 0x00007ffff721cff5 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#15 0x00007ffff721c40a in  () at /lib/x86_64-linux-gnu/libffi.so.7
#16 0x00007ffff7235316 in _ctypes_callproc ()
    at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#17 0x00007ffff72359ec in  ()
    at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#18 0x00000000005f6a46 in _PyObject_MakeTpCall ()
#19 0x0000000000570a1f in _PyEval_EvalFrameDefault ()
#20 0x00000000005696da in _PyEval_EvalCodeWithName ()
#21 0x00000000005f6403 in _PyFunction_Vectorcall ()
#22 0x00000000005703e6 in _PyEval_EvalFrameDefault ()
#23 0x00000000005f6226 in _PyFunction_Vectorcall ()
#24 0x000000000059cffd in  ()
#25 0x00000000005f6a46 in _PyObject_MakeTpCall ()
#26 0x0000000000570612 in _PyEval_EvalFrameDefault ()
#27 0x00000000005696da in _PyEval_EvalCodeWithName ()
#28 0x00000000005f6403 in _PyFunction_Vectorcall ()
#29 0x00000000005f7127 in PyObject_CallObject ()
#30 0x00007ffff722f3f1 in  ()
    at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#31 0x00007ffff721ce06 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#32 0x00007ffff721d188 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#33 0x00007ffff478c2e9 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::_DispatchEvent(chip::DeviceLayer::ChipDeviceEvent const*)
    (this=0x7ffff48b64f0 <chip::DeviceLayer::PlatformManagerImpl::sInstance+16>, event=0x7ffff3ad6e40)
    at ../../src/include/platform/internal/GenericPlatformManagerImpl.cpp:232
#34 0x00007ffff478b975 in chip::DeviceLayer::PlatformManager::DispatchEvent(chip::DeviceLayer::ChipDeviceEvent const*)
    (this=0x7ffff48b64e0 <chip::DeviceLayer::PlatformManagerImpl::sInstance>, event=0x7ffff3ad6e40) at ../../src/include/platform/PlatformManager.h:429
#35 0x00007ffff478d0ac in chip::DeviceLayer::Internal::GenericPlatformManagerImpl_POSIX<chip::DeviceLayer::PlatformManagerImpl>::ProcessDeviceEvents()
    (this=0x7ffff48b64f0 <chip::DeviceLayer::PlatformManagerImpl::sInstance+16>)
    at ../../src/include/platform/internal/GenericPlatformManagerImpl_POSIX.cpp:146
#36 0x00007ffff478cb62 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl_POSIX<chip::DeviceLayer::PlatformManagerImpl>::_RunEventLoop()
    (this=0x7ffff48b64f0 <chip::DeviceLayer::PlatformManagerImpl::sInstance+16>)
    at ../../src/include/platform/internal/GenericPlatformManagerImpl_POSIX.cpp:183
#37 0x00007ffff45414c0 in chip::DeviceLayer::PlatformManager::RunEventLoop()
    (this=0x7ffff48b64e0 <chip::DeviceLayer::PlatformManagerImpl::sInstance>)
    at ../../src/include/platform/PlatformManager.h:352
#38 0x00007ffff45414fb in (anonymous namespace)::PlatformMainLoop(void*) ()
    at ../../src/controller/python/chip/native/StackInit.cpp:36
#39 0x00007ffff7db5609 in start_thread ()
    at /lib/x86_64-linux-gnu/libpthread.so.0
#40 0x00007ffff7ef1293 in clone () at /lib/x86_64-linux-gnu/libc.so.6
(gdb) quit
```

Original failure run [link](https://github.com/project-chip/connectedhomeip/runs/5379592623?check_suite_focus=true).

**Comment by bzbarsky-apple** [comment]
@mrjerryjohns Is this still crashing?
