### ISSUE TITLE
generate_jars_for_test.py fails to build

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/connectedhomeip#16946]
jonsmirl@ares:~/aosp/chip$ python3 build/chip/java/tests/generate_jars_for_test.py
/home/jonsmirl/aosp/chip/build/chip/java/tests/IncludedInJar.java:4: error: cannot find symbol

-----------------------------------------------------------------------------------------
jonsmirl@ares:~/aosp/chip$ source scripts/activate.sh

  WELCOME TO...
  ACTIVATOR! This sets your shell environment variables.

Activating environment (setting environment variables):

  Setting environment variables for CIPD package manager...done
  Setting environment variables for Python environment.....done
  Setting environment variables for pw packages............skipped
  Setting environment variables for Host tools.............done

Checking the environment:

20220401 15:14:10 INF Environment passes all checks!

Environment looks good, you are ready to go!

jonsmirl@ares:/aosp/chip$ python3 build/chip/java/tests/generate_jars_for_test.py
/home/jonsmirl/aosp/chip/build/chip/java/tests/IncludedInJar.java:4: error: cannot find symbol
  IncludedInChildJar includedInChildJar;
  ^
  symbol:   class IncludedInChildJar
  location: class IncludedInJar
1 error
Traceback (most recent call last):
  File "/home/jonsmirl/aosp/chip/build/chip/java/javac_runner.py", line 146, in <module>
    sys.exit(main())
  File "/home/jonsmirl/aosp/chip/build/chip/java/javac_runner.py", line 130, in main
    retcode = subprocess.check_call(java_args + args.rest)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/javac', '-d', '/tmp/chip_java_build_test/classes', '/home/jonsmirl/aosp/chip/build/chip/java/tests/IncludedInJar.java']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "build/chip/java/tests/generate_jars_for_test.py", line 50, in <module>
    sys.exit(main())
  File "build/chip/java/tests/generate_jars_for_test.py", line 45, in main
    generateJar(test_dir + '/IncludedInJar.java', 'prebuilt_jar.jar')
  File "build/chip/java/tests/generate_jars_for_test.py", line 30, in generateJar
    subprocess.check_call(javac_runner_command)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3', '/home/jonsmirl/aosp/chip/build/chip/java/javac_runner.py', '--classdir', '/tmp/chip_java_build_test/classes', '--outfile', '/tmp/chip_java_build_test/prebuilt_jar.classlist', '--build-config', '/home/jonsmirl/aosp/chip/build/chip/java/tests/empty_build_config.json', '--', '-d', '/tmp/chip_java_build_test/classes', '/home/jonsmirl/aosp/chip/build/chip/java/tests/IncludedInJar.java']' returned non-zero exit status 1.
jonsmirl@ares:~/aosp/chip$

**Comment by jonsmirl** [comment]
Build failures building Android app on Linux with Java 17

This hack works around the previous error:
--- a/build/chip/java/tests/generate_jars_for_test.py
+++ b/build/chip/java/tests/generate_jars_for_test.py
@@ -26,6 +26,7 @@ def generateJar(source_file, output_name):
         '-d',
         tmp_classes_dir,
         source_file,
+        test_dir + '/IncludedInChildJar.java'
     ]
     subprocess.check_call(javac_runner_command)
 

Add this next line to examples/tv-casting-app/android/App/gradle.properties and src/android/CHIPTool/gradle.properties and src/android/CHIPTest/gradle.properties

org.gradle.jvmargs=-Xmx1536M --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED

I still can't get the test app to build so ignoring it for now.
