### ISSUE TITLE
Source bootstrap.sh error

### ISSUE THREAD

**Issue by TheWalkingDead1024** [project-chip/connectedhomeip#18931]
When I try to source bootstrap.sh to build preparation for CHIP project (I use M1 Macbook Pro), I got an error like this(I am using branch master(the latest commit is f188fd9625f171a7d32a4b8e4a00d6abf60af891), python verson 3.9.6):

      In file included from third_party/boringssl-with-bazel/err_data.c:17:
      third_party/boringssl-with-bazel/src/include/openssl/base.h:187:9: warning: 'OPENSSL_VERSION_NUMBER' macro redefined [-Wmacro-redefined]
      #define OPENSSL_VERSION_NUMBER 0x1010107f
              ^
      /opt/homebrew/opt/openssl@3/include/openssl/opensslv.h:99:10: note: previous definition is here
      # define OPENSSL_VERSION_NUMBER          \
               ^
      In file included from third_party/boringssl-with-bazel/err_data.c:18:
      In file included from /opt/homebrew/opt/openssl@3/include/openssl/err.h:21:
      /opt/homebrew/opt/openssl@3/include/openssl/e_os2.h:183:11: warning: 'OPENSSL_EXPORT' macro redefined [-Wmacro-redefined]
      #  define OPENSSL_EXPORT extern
                ^
      third_party/boringssl-with-bazel/src/include/openssl/base.h:222:9: note: previous definition is here
      #define OPENSSL_EXPORT
              ^
      In file included from third_party/boringssl-with-bazel/err_data.c:18:
      In file included from /opt/homebrew/opt/openssl@3/include/openssl/err.h:28:
      /opt/homebrew/opt/openssl@3/include/openssl/types.h:62:13: error: typedef redefinition with different types ('int' vs 'struct asn1_null_st')
      typedef int ASN1_NULL;
                  ^
      third_party/boringssl-with-bazel/src/include/openssl/base.h:333:29: note: previous definition is here
      typedef struct asn1_null_st ASN1_NULL;
                                  ^
      In file included from third_party/boringssl-with-bazel/err_data.c:18:
      In file included from /opt/homebrew/opt/openssl@3/include/openssl/err.h:28:
      /opt/homebrew/opt/openssl@3/include/openssl/types.h:103:26: error: typedef redefinition with different types ('struct evp_md_st' vs 'struct env_md_st')
      typedef struct evp_md_st EVP_MD;
                               ^
      third_party/boringssl-with-bazel/src/include/openssl/base.h:403:26: note: previous definition is here
      typedef struct env_md_st EVP_MD;
                               ^
      In file included from third_party/boringssl-with-bazel/err_data.c:18:
      In file included from /opt/homebrew/opt/openssl@3/include/openssl/err.h:28:
      /opt/homebrew/opt/openssl@3/include/openssl/types.h:104:30: error: typedef redefinition with different types ('struct evp_md_ctx_st' vs 'struct env_md_ctx_st')
      typedef struct evp_md_ctx_st EVP_MD_CTX;
                                   ^
      third_party/boringssl-with-bazel/src/include/openssl/base.h:402:30: note: previous definition is here
      typedef struct env_md_ctx_st EVP_MD_CTX;
                                   ^
      In file included from third_party/boringssl-with-bazel/err_data.c:18:
      In file included from /opt/homebrew/opt/openssl@3/include/openssl/err.h:28:
      /opt/homebrew/opt/openssl@3/include/openssl/types.h:130:34: error: typedef redefinition with different types ('struct evp_Encode_Ctx_st' vs 'struct evp_encode_ctx_st')
      typedef struct evp_Encode_Ctx_st EVP_ENCODE_CTX;
                                       ^
      third_party/boringssl-with-bazel/src/include/openssl/base.h:407:34: note: previous definition is here
      typedef struct evp_encode_ctx_st EVP_ENCODE_CTX;
                                       ^
      In file included from third_party/boringssl-with-bazel/err_data.c:18:
      In file included from /opt/homebrew/opt/openssl@3/include/openssl/err.h:29:
      In file included from /opt/homebrew/opt/openssl@3/include/openssl/bio.h:30:
      /opt/homebrew/opt/openssl@3/include/openssl/crypto.h:308:3: error: typedef redefinition with different types ('struct crypto_threadid_st' vs 'int')
      } CRYPTO_THREADID;
        ^
      third_party/boringssl-with-bazel/src/include/openssl/base.h:329:13: note: previous definition is here
      typedef int CRYPTO_THREADID;
                  ^
      third_party/boringssl-with-bazel/err_data.c:33:1: error: static_assert failed due to requirement '13 == 12' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_ASN1 == 12, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:34:1: error: static_assert failed due to requirement '14 == 13' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_CONF == 13, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:35:1: error: static_assert failed due to requirement '15 == 14' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_CRYPTO == 14, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:36:1: error: static_assert failed due to requirement '16 == 15' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_EC == 15, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:37:1: error: static_assert failed due to requirement '20 == 16' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_SSL == 16, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:38:1: error: static_assert failed due to requirement '32 == 17' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_BIO == 17, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:39:1: error: static_assert failed due to requirement '33 == 18' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_PKCS7 == 18, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:40:23: error: use of undeclared identifier 'ERR_LIB_PKCS8'
      OPENSSL_STATIC_ASSERT(ERR_LIB_PKCS8 == 19, "library value changed");
                            ^
      third_party/boringssl-with-bazel/err_data.c:41:1: error: static_assert failed due to requirement '34 == 20' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_X509V3 == 20, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:42:1: error: static_assert failed due to requirement '36 == 21' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_RAND == 21, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:43:1: error: static_assert failed due to requirement '38 == 22' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_ENGINE == 22, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:44:1: error: static_assert failed due to requirement '39 == 23' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_OCSP == 23, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:45:1: error: static_assert failed due to requirement '40 == 24' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_UI == 24, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      third_party/boringssl-with-bazel/err_data.c:46:1: error: static_assert failed due to requirement '41 == 25' "library value changed"
      OPENSSL_STATIC_ASSERT(ERR_LIB_COMP == 25, "library value changed");
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      third_party/boringssl-with-bazel/src/include/openssl/type_check.h:75:42: note: expanded from macro 'OPENSSL_STATIC_ASSERT'
      #define OPENSSL_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
                                               ^              ~~~~
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      2 warnings and 20 errors generated.
      
      third_party/re2/re2/prog.cc:514:16: warning: code will never be executed [-Wunreachable-code]
          LOG(ERROR) << "Using trivial bytemap.";
                     ^~
      third_party/re2/re2/prog.cc:513:7: note: silence by adding parentheses to mark code as explicitly dead
        if (0) {  // For debugging, use trivial bytemap.
            ^
            /* DISABLES CODE */ ( )
      third_party/re2/re2/prog.cc:613:7: warning: variable 'total' set but not used [-Wunused-but-set-variable]
        int total = 0;
            ^
      2 warnings generated.
      third_party/re2/re2/prog.cc:514:16: warning: code will never be executed [-Wunreachable-code]
          LOG(ERROR) << "Using trivial bytemap.";
                     ^~
      third_party/re2/re2/prog.cc:513:7: note: silence by adding parentheses to mark code as explicitly dead
        if (0) {  // For debugging, use trivial bytemap.
            ^
            /* DISABLES CODE */ ( )
      third_party/re2/re2/prog.cc:613:7: warning: variable 'total' set but not used [-Wunused-but-set-variable]
        int total = 0;
            ^
      2 warnings generated.
      
      Traceback (most recent call last):
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 173, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] +
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 917, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 176, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/setup.py", line 527, in <module>
          setuptools.setup(
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 670, in run
          self.run_command('build')
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 136, in run
          self.run_command(cmd_name)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/commands.py", line 284, in build_extensions
          raise CommandError(
      commands.CommandError: Failed `build_ext` step:
      Traceback (most recent call last):
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 173, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] +
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 917, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/yk/ldwj3fj10qj9ysvj77vq0zhw0000gn/T/pip-install-it8c1ufh/grpcio_415dc625f5b941f0b3998312f05f351e/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 176, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
ninja: build stopped: subcommand failed.
['ninja', '-C', '/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/gn_out', '-v', ':python_packages.install']

Traceback (most recent call last):
  File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 287, in install_packages
    subprocess.check_call(ninja_cmd, stdout=outs, stderr=outs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', '/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/gn_out', '-v', ':python_packages.install']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 768, in <module>
    sys.exit(main())
  File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 760, in main
    return EnvSetup(**vars(parse())).setup()
  File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 442, in setup
    result = step(spin)
  File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 582, in virtualenv
    if not virtualenv_setup.install(
  File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 302, in install
    install_packages(gn_target)
  File "/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 290, in install_packages
    raise subprocess.CalledProcessError(err.returncode, err.cmd,
subprocess.CalledProcessError: Command '['ninja', '-C', '/Users/TheWalkingDead/Documents/GitHub/connectedhomeip/.environment/gn_out', '-v', ':python_packages.install']' returned non-zero exit status 1.

**Comment by bzbarsky-apple** [comment]
@mspang any idea what's going on there?

**Comment by benjaminnestler** [comment]
What about the first errors relating the multiple defines of OpenSSL (installed via brew) and boringssl-with-bazel?
