### ISSUE TITLE
I can`t build android chip tool project in ubuntu ,this is my log and i need help

### ISSUE THREAD

**Issue by Qiu-zhangbao** [project-chip/connectedhomeip#19946]
According to doc/guides/building_android.md
i Building Android CHIPTool from scripts
i have java11,android-sdk,android-ndk,gradle,and add the path to my system
but i can`t build apk file
this is my log

qzb@ubuntu:~/tools/connectedhomeip$ ./scripts/build/build_examples.py --target android-arm64-chip-tool build
2022-06-24 17:33:45 INFO    Building targets: android-arm64-chip-tool
2022-06-24 17:33:45 INFO    Generating /home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool
2022-06-24 17:33:45 INFO    Generating JARs for Java build rules test
2022-06-24 17:33:46 INFO    Command ['python3', 'build/chip/java/tests/generate_jars_for_test.py'] completed
2022-06-24 17:33:46 INFO    Setting up Android deps through Gradle
2022-06-24 17:33:47 INFO    > Task :buildSrc:compileJava NO-SOURCE
2022-06-24 17:33:47 INFO    > Task :buildSrc:compileGroovy UP-TO-DATE
2022-06-24 17:33:47 INFO    > Task :buildSrc:processResources NO-SOURCE
2022-06-24 17:33:47 INFO    > Task :buildSrc:classes UP-TO-DATE
2022-06-24 17:33:47 INFO    > Task :buildSrc:jar UP-TO-DATE
2022-06-24 17:33:47 INFO    > Task :buildSrc:assemble UP-TO-DATE
2022-06-24 17:33:47 INFO    > Task :buildSrc:compileTestJava NO-SOURCE
2022-06-24 17:33:47 INFO    > Task :buildSrc:compileTestGroovy NO-SOURCE
2022-06-24 17:33:47 INFO    > Task :buildSrc:processTestResources NO-SOURCE
2022-06-24 17:33:47 INFO    > Task :buildSrc:testClasses UP-TO-DATE
2022-06-24 17:33:47 INFO    > Task :buildSrc:test NO-SOURCE
2022-06-24 17:33:47 INFO    > Task :buildSrc:check UP-TO-DATE
2022-06-24 17:33:47 INFO    > Task :buildSrc:build UP-TO-DATE
2022-06-24 17:33:47 INFO    > Task :copyArtifacts UP-TO-DATE
2022-06-24 17:33:47 INFO    > Task :setUpAndroidDeps
2022-06-24 17:33:47 INFO    
2022-06-24 17:33:47 INFO    BUILD SUCCESSFUL in 458ms
2022-06-24 17:33:47 INFO    4 actionable tasks: 1 executed, 3 up-to-date
2022-06-24 17:33:47 INFO    Command ['python3', 'third_party/android_deps/set_up_android_deps.py'] completed
2022-06-24 17:33:47 INFO    Building /home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool
2022-06-24 17:33:47 INFO    Building JNI android-arm64-chip-tool
2022-06-24 17:33:47 INFO    ninja: Entering directory `/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool'
2022-06-24 17:33:47 INFO    [0/1] Regenerating ninja files
2022-06-24 17:33:47 INFO    [1/802] cp /home/qzb/android/android-ndk-r24/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so lib/jni/arm64-v8a/libc++_shared.so
2022-06-24 17:33:47 INFO    [2/802] stamp obj/src/lib/dnssd/platform_header.stamp
2022-06-24 17:33:47 INFO    [3/802] stamp obj/build/chip/java/shared_cpplib.stamp
2022-06-24 17:33:47 INFO    [4/802] ACTION //src/controller/java:android_config(//build/toolchain/android:android_arm64)
2022-06-24 17:33:47 INFO    [5/802] ACTION //build/chip/java/tests:child_library_config(//third_party/pigweed/repo/pw_build/python_toolchain:python)
2022-06-24 17:33:47 INFO    [6/802] ACTION //src/ble:gen_ble_buildconfig(//build/toolchain/android:android_arm64)
2022-06-24 17:33:47 INFO    [7/802] ACTION //src/crypto:gen_crypto_buildconfig(//build/toolchain/android:android_arm64)
2022-06-24 17:33:47 INFO    [8/802] ACTION //src/app:gen_app_buildconfig(//build/toolchain/android:android_arm64)
2022-06-24 17:33:47 INFO    [9/802] stamp python/obj/build/chip/java/tests/child_library_config.stamp
2022-06-24 17:33:47 INFO    [10/802] stamp obj/src/controller/java/android_config.stamp
2022-06-24 17:33:47 INFO    [11/802] ACTION //src/lib/asn1:gen_asn1oid(//build/toolchain/android:android_arm64)
2022-06-24 17:33:47 INFO    [12/802] stamp obj/src/app/gen_app_buildconfig.stamp
2022-06-24 17:33:47 INFO    [13/802] stamp obj/src/ble/gen_ble_buildconfig.stamp
2022-06-24 17:33:47 INFO    [14/802] cp /home/qzb/android/android-sdk-linux/platforms/android-21/android.jar lib/src/controller/java/android.jar
2022-06-24 17:33:47 INFO    [15/802] stamp obj/src/crypto/gen_crypto_buildconfig.stamp
2022-06-24 17:33:47 INFO    [16/802] stamp obj/src/lib/asn1/gen_asn1oid.stamp
2022-06-24 17:33:47 INFO    [17/802] stamp obj/src/app/app_buildconfig.stamp
2022-06-24 17:33:47 INFO    [18/802] stamp obj/src/ble/ble_buildconfig.stamp
2022-06-24 17:33:47 INFO    [19/802] stamp obj/src/controller/java/android.stamp
2022-06-24 17:33:47 INFO    [20/802] stamp obj/src/crypto/crypto_buildconfig.stamp
2022-06-24 17:33:47 INFO    [21/802] ACTION //build/chip/java/tests:child_prebuilt_config(//third_party/pigweed/repo/pw_build/python_toolchain:python)
2022-06-24 17:33:47 INFO    [22/802] stamp obj/src/lib/asn1/asn1oid_header.stamp
2022-06-24 17:33:47 INFO    [23/802] ACTION //src/lib/core:gen_chip_buildconfig(//build/toolchain/android:android_arm64)
2022-06-24 17:33:47 INFO    [24/802] ACTION //build/chip/java/tests:grandchild_library_config(//third_party/pigweed/repo/pw_build/python_toolchain:python)
2022-06-24 17:33:47 INFO    [25/802] stamp python/obj/build/chip/java/tests/child_prebuilt_config.stamp

.....

bj/src/controller/data_model/data_model.stamp
2022-06-24 17:34:37 INFO    [797/802] ar libControllerTests.a
2022-06-24 17:34:37 INFO    [798/802] stamp obj/src/controller/tests/tests.stamp
2022-06-24 17:34:37 INFO    [799/802] stamp obj/src/tests.stamp
2022-06-24 17:34:38 INFO    [800/802] ld -shared lib/jni/arm64-v8a/libCHIPController.so
2022-06-24 17:34:38 INFO    [801/802] stamp obj/src/controller/java/java.stamp
2022-06-24 17:34:38 INFO    [802/802] stamp obj/default.stamp
2022-06-24 17:34:38 INFO    Command ['ninja', '-C', '/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool'] completed
2022-06-24 17:34:38 INFO    Prepare Native libs android-arm64-chip-tool
2022-06-24 17:34:38 INFO    Command ['mkdir', '-p', '/home/qzb/tools/connectedhomeip/src/android/CHIPTool/app/libs/jniLibs/arm64-v8a'] completed
2022-06-24 17:34:38 INFO    Command ['cp', '/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool/lib/jni/arm64-v8a/libSetupPayloadParser.so', '/home/qzb/tools/connectedhomeip/src/android/CHIPTool/app/libs/jniLibs/arm64-v8a/libSetupPayloadParser.so'] completed
2022-06-24 17:34:38 INFO    Command ['cp', '/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool/lib/jni/arm64-v8a/libCHIPController.so', '/home/qzb/tools/connectedhomeip/src/android/CHIPTool/app/libs/jniLibs/arm64-v8a/libCHIPController.so'] completed
2022-06-24 17:34:38 INFO    Command ['cp', '/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool/lib/jni/arm64-v8a/libc++_shared.so', '/home/qzb/tools/connectedhomeip/src/android/CHIPTool/app/libs/jniLibs/arm64-v8a/libc++_shared.so'] completed
2022-06-24 17:34:38 INFO    Command ['cp', '/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool/lib/src/controller/java/CHIPController.jar', '/home/qzb/tools/connectedhomeip/src/android/CHIPTool/app/libs/CHIPController.jar'] completed
2022-06-24 17:34:38 INFO    Command ['cp', '/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool/lib/src/setup_payload/java/SetupPayloadParser.jar', '/home/qzb/tools/connectedhomeip/src/android/CHIPTool/app/libs/SetupPayloadParser.jar'] completed
2022-06-24 17:34:38 INFO    Command ['cp', '/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool/lib/src/platform/android/AndroidPlatform.jar', '/home/qzb/tools/connectedhomeip/src/android/CHIPTool/app/libs/AndroidPlatform.jar'] completed
2022-06-24 17:34:38 INFO    Building APP android-arm64-chip-tool
2022-06-24 17:34:39 INFO    Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
2022-06-24 17:34:43 INFO    
2022-06-24 17:34:43 INFO    > Configure project :app
2022-06-24 17:34:43 INFO    Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
2022-06-24 17:34:43 INFO    Observed package id 'build-tools;30.0.0-rc2' in inconsistent location '/home/qzb/android/android-sdk-linux/build-tools/30.0.0-preview' (Expected '/home/qzb/android/android-sdk-linux/build-tools/30.0.0-rc2')
2022-06-24 17:34:44 INFO    Observed package id 'build-tools;30.0.0-rc2' in inconsistent location '/home/qzb/android/android-sdk-linux/build-tools/30.0.0-preview' (Expected '/home/qzb/android/android-sdk-linux/build-tools/30.0.0-rc2')
2022-06-24 17:34:46 INFO    Checking the license for package Android SDK Build-Tools 30.0.2 in /home/qzb/android/android-sdk-linux/licenses
2022-06-24 17:34:46 INFO    Warning: License for package Android SDK Build-Tools 30.0.2 not accepted.
2022-06-24 17:34:46 WARNING 
2022-06-24 17:34:46 INFO    Checking the license for package Android SDK Platform 30 in /home/qzb/android/android-sdk-linux/licenses
2022-06-24 17:34:46 WARNING FAILURE: Build failed with an exception.
2022-06-24 17:34:46 WARNING 
2022-06-24 17:34:46 WARNING * What went wrong:
2022-06-24 17:34:46 INFO    Warning: License for package Android SDK Platform 30 not accepted.
2022-06-24 17:34:46 WARNING Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
2022-06-24 17:34:46 WARNING > Failed to install the following Android SDK packages as some licences have not been accepted.
2022-06-24 17:34:46 WARNING      build-tools;30.0.2 Android SDK Build-Tools 30.0.2
2022-06-24 17:34:46 WARNING      platforms;android-30 Android SDK Platform 30
2022-06-24 17:34:46 WARNING   To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
2022-06-24 17:34:46 WARNING   Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
2022-06-24 17:34:46 WARNING   
2022-06-24 17:34:46 WARNING   Using Android SDK: /home/qzb/android/android-sdk-linux
2022-06-24 17:34:46 WARNING 
2022-06-24 17:34:46 WARNING * Try:
2022-06-24 17:34:46 WARNING Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2022-06-24 17:34:46 WARNING 
2022-06-24 17:34:46 WARNING * Get more help at https://help.gradle.org
2022-06-24 17:34:46 WARNING 
2022-06-24 17:34:46 WARNING BUILD FAILED in 7s
Traceback (most recent call last):
  File "./scripts/build/build_examples.py", line 213, in <module>
    main()
  File "/home/qzb/tools/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/qzb/tools/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/qzb/tools/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/qzb/tools/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/qzb/tools/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/qzb/tools/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./scripts/build/build_examples.py", line 203, in cmd_build
    context.obj.Build()
  File "/home/qzb/tools/connectedhomeip/scripts/build/build/__init__.py", line 59, in Build
    builder.build()
  File "/home/qzb/tools/connectedhomeip/scripts/build/builders/builder.py", line 89, in build
    self._build()
  File "/home/qzb/tools/connectedhomeip/scripts/build/builders/android.py", line 208, in _build
    self._Execute([
  File "/home/qzb/tools/connectedhomeip/scripts/build/builders/builder.py", line 94, in _Execute
    self._runner.Run(cmdarray, title=title)
  File "/home/qzb/tools/connectedhomeip/scripts/build/runner/shell.py", line 72, in Run
    raise Exception('Command %r failed: %d' % (cmd, code))
Exception: Command ['/home/qzb/tools/connectedhomeip/src/android/CHIPTool/gradlew', '-p', '/home/qzb/tools/connectedhomeip/src/android/CHIPTool', '-PmatterBuildSrcDir=/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool', '-PmatterSdkSourceBuild=false', '-PbuildDir=/home/qzb/tools/connectedhomeip/out/android-arm64-chip-tool', 'assembleDebug'] failed: 1
qzb@ubuntu:~/tools/connectedhomeip$

**Comment by andy31415** [comment]
```
2022-06-24 17:34:46 WARNING * What went wrong:
2022-06-24 17:34:46 INFO Warning: License for package Android SDK Platform 30 not accepted.
2022-06-24 17:34:46 WARNING Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
2022-06-24 17:34:46 WARNING > Failed to install the following Android SDK packages as some licences have not been accepted.
```

seems to indicate that license acceptance failed. License acceptance involves saving files into the SDK path, so I am guessing no permissions.

Try to see what trying to accept licenses with `sdkmanager --licenses` does
