### ISSUE TITLE
Can't build the default Simulated App with Script : error TS7016

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#22208]
#### Can't build the default Simulated App with Script
 * expected behavior : build the chip-app1 binary
 * actual behavior: error TS7016: Could not find a declaration file for module 'sqlite3'. 
 * steps to reproduce
 
```
npm install node-ipc sqlite3 axios http-status-codes bytebuffer electron
 ./scripts/examples/gn_build_test_example.sh app1
```

 * system configuration
Ubuntu 20.04.3 LTS
Python 3.8.10

```
user@ubuntu:~/connectedhomeip$ ./scripts/examples/gn_build_test_example.sh app1

  WELCOME TO...


        â–ˆ
        â–ˆ
    â–„   â–ˆ   â–„                                 â–ˆ     â–Œ
    â–€â–€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–€â–€     â–„â–“â–€â–€â–€â–„,â–„â–€â–€â–€â–€â–„   â•“â–„â–€â–€â–€â–€â–„â–ˆ  â–€â–€â–ˆâ–€â–€â–€â–€â–€â–ˆâ–€â–€  ,â–„â–€â–€â–€â–€â–„    â–„â–€â–€
  â–€â–ˆâ–„       â–„â–ˆâ–€   â–ˆ     â–ˆ     â–ˆ  â–â–Œ      â–ˆ    â–ˆ     â–ˆ   .â–ˆâ–„â–„â–„â–„â–„â–„â–ˆâŒ â–â–Œ
    â–€â–ˆâ–„   â–„â–ˆâ–€     â–ˆ     â–ˆ     â–ˆ  â–â–Œ      â–ˆ    â–ˆ     â–ˆ    â–ˆ         â–â–Œ
 â–„â–ˆâ–ˆâ–€â–€â–ˆ   â–ˆâ–€â–€â–ˆâ–ˆâ–„  â–ˆ     â–ˆ     â–ˆ   â•™â–€â–„â–„â–„Î¦â–€â–ˆ    â–€â–„â–„   â–€â–„â–„   â–€â–„â–„â–„â–„â–€^  â–â–Œ
â–€â–€    â–ˆ   â–ˆ    â–€â–€

  ACTIVATOR! This sets your shell environment variables.

Activating environment (setting environment variables):

  Setting environment variables for CIPD package manager...done
  Setting environment variables for Python environment.....done
  Setting environment variables for pw packages............skipped
  Setting environment variables for Host tools.............done

Checking the environment:

20220826 22:55:10 INF Environment passes all checks!

Environment looks good, you are ready to go!

Searching for zcl file from /home/user/connectedhomeip/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap
ðŸš€ Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
ðŸ” Git commit: a62906eac316be552be78fbb669c5c853fd3a955 from Fri Jul 08 2022 11:33:39 GMT-0700 (Pacific Daylight Time)
ðŸš€ Executing: npx tsc --build ./tsconfig.json
src-shared/types/db-types.ts(18,25): error TS7016: Could not find a declaration file for module 'sqlite3'. '/home/user/connectedhomeip/node_modules/sqlite3/lib/sqlite3.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sqlite3` if it exists or add a new declaration (.d.ts) file containing `declare module 'sqlite3';`
src-shared/types/ipc-types.ts(18,17): error TS7016: Could not find a declaration file for module 'node-ipc'. '/home/user/connectedhomeip/node_modules/node-ipc/node-ipc.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/node-ipc` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-ipc';`
src-electron/client/ipc-client.ts(22,17): error TS7016: Could not find a declaration file for module 'node-ipc'. '/home/user/connectedhomeip/node_modules/node-ipc/node-ipc.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/node-ipc` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-ipc';`
src-electron/client/ipc-client.ts(56,44): error TS7006: Parameter 'data' implicitly has an 'any' type.
src-electron/client/ipc-client.ts(61,44): error TS7006: Parameter 'data' implicitly has an 'any' type.
src-electron/util/bin.ts(20,24): error TS7016: Could not find a declaration file for module 'bytebuffer'. '/home/user/connectedhomeip/node_modules/bytebuffer/dist/bytebuffer-node.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/bytebuffer` if it exists or add a new declaration (.d.ts) file containing `declare module 'bytebuffer';`
src-electron/ide-integration/studio-rest-api.ts(36,25): error TS7016: Could not find a declaration file for module 'sqlite3'. '/home/user/connectedhomeip/node_modules/sqlite3/lib/sqlite3.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sqlite3` if it exists or add a new declaration (.d.ts) file containing `declare module 'sqlite3';`
src-electron/server/ipc-server.ts(19,17): error TS7016: Could not find a declaration file for module 'node-ipc'. '/home/user/connectedhomeip/node_modules/node-ipc/node-ipc.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/node-ipc` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-ipc';`
src-electron/server/ipc-server.ts(172,38): error TS7006: Parameter 'err' implicitly has an 'any' type.
src-electron/server/ipc-server.ts(185,56): error TS7006: Parameter 'data' implicitly has an 'any' type.
src-electron/server/ipc-server.ts(185,62): error TS7006: Parameter 'socket' implicitly has an 'any' type.
ðŸ‘Ž Program npx exited with error code: 1
Traceback (most recent call last):
  File "/home/user/connectedhomeip/scripts/examples/../../scripts/tools/zap/generate.py", line 230, in <module>
    main()
  File "/home/user/connectedhomeip/scripts/examples/../../scripts/tools/zap/generate.py", line 218, in main
    runGeneration(zap_file, zcl_file, templates_file, output_dir)
  File "/home/user/connectedhomeip/scripts/examples/../../scripts/tools/zap/generate.py", line 141, in runGeneration
    subprocess.check_call(['node', './src-script/zap-generate.js', '-z',
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', './src-script/zap-generate.js', '-z', '/home/user/connectedhomeip/src/app/zap-templates/zcl/zcl.json', '-g', '/home/user/connectedhomeip/src/app/zap-templates/app-templates.json', '-i', '/home/user/connectedhomeip/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap', '-o', '/home/user/connectedhomeip/scripts/examples/../../zzz_generated/placeholder/app1/zap-generated']' returned non-zero exit status 1.
```

**Comment by lboue** [comment]
I managed to fix the previous errors with those commands 

```
npm install -D @types/sqlite3
npm install -D @types/node-ipc
npm install -D @types/bytebuffer
```

But I have another one this time even if I pass the test:
**_`INF Environment passes all checks!`_**


```
user@ubuntu:~/connectedhomeip$ ./scripts/examples/gn_build_test_example.sh app1                                                    

  WELCOME TO...


        â–ˆ
        â–ˆ
    â–„   â–ˆ   â–„                                 â–ˆ     â–Œ
    â–€â–€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–€â–€     â–„â–“â–€â–€â–€â–„,â–„â–€â–€â–€â–€â–„   â•“â–„â–€â–€â–€â–€â–„â–ˆ  â–€â–€â–ˆâ–€â–€â–€â–€â–€â–ˆâ–€â–€  ,â–„â–€â–€â–€â–€â–„    â–„â–€â–€
  â–€â–ˆâ–„       â–„â–ˆâ–€   â–ˆ     â–ˆ     â–ˆ  â–â–Œ      â–ˆ    â–ˆ     â–ˆ   .â–ˆâ–„â–„â–„â–„â–„â–„â–ˆâŒ â–â–Œ
    â–€â–ˆâ–„   â–„â–ˆâ–€     â–ˆ     â–ˆ     â–ˆ  â–â–Œ      â–ˆ    â–ˆ     â–ˆ    â–ˆ         â–â–Œ
 â–„â–ˆâ–ˆâ–€â–€â–ˆ   â–ˆâ–€â–€â–ˆâ–ˆâ–„  â–ˆ     â–ˆ     â–ˆ   â•™â–€â–„â–„â–„Î¦â–€â–ˆ    â–€â–„â–„   â–€â–„â–„   â–€â–„â–„â–„â–„â–€^  â–â–Œ
â–€â–€    â–ˆ   â–ˆ    â–€â–€

  ACTIVATOR! This sets your shell environment variables.

Activating environment (setting environment variables):

  Setting environment variables for CIPD package manager...done
  Setting environment variables for Python environment.....done
  Setting environment variables for pw packages............skipped
  Setting environment variables for Host tools.............done

Checking the environment:

20220827 02:13:08 INF Environment passes all checks!

Environment looks good, you are ready to go!

Searching for zcl file from /home/user/connectedhomeip/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap
ðŸš€ Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
ðŸ” Git commit: a62906eac316be552be78fbb669c5c853fd3a955 from Fri Jul 08 2022 11:33:39 GMT-0700 (Pacific Daylight Time)
ðŸš€ Executing: npx tsc --build ./tsconfig.json
ðŸš€ Executing: npx copyfiles -V ./src-electron/**/*.sql ./dist/
unglobed path: ./src-electron/db/zap-schema.sql
copy from: ./src-electron/db/zap-schema.sql
copy to: dist/src-electron/db/zap-schema.sql
ðŸš€ Executing: node /home/user/connectedhomeip/third_party/zap/repo/dist/src-electron/main-process/main.js generate --noUi --noServer --stateDirectory ~/.zap --zcl /home/user/connectedhomeip/src/app/zap-templates/zcl/zcl.json --generationTemplate /home/user/connectedhomeip/src/app/zap-templates/app-templates.json --out /home/user/connectedhomeip/scripts/examples/../../zzz_generated/placeholder/app1/zap-generated /home/user/connectedhomeip/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap
â‡ Error: Cannot find module '/home/user/connectedhomeip/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node'
Require stack:
- /home/user/connectedhomeip/node_modules/sqlite3/lib/sqlite3-binding.js
- /home/user/connectedhomeip/node_modules/sqlite3/lib/sqlite3.js
- /home/user/connectedhomeip/third_party/zap/repo/dist/src-electron/db/db-api.js
- /home/user/connectedhomeip/third_party/zap/repo/dist/src-electron/db/query-package.js
- /home/user/connectedhomeip/third_party/zap/repo/dist/src-electron/util/util.js
- /home/user/connectedhomeip/third_party/zap/repo/dist/src-electron/main-process/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function.Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/user/connectedhomeip/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
ðŸ‘Ž Program node exited with error code: 1
Traceback (most recent call last):
  File "/home/user/connectedhomeip/scripts/examples/../../scripts/tools/zap/generate.py", line 230, in <module>
    main()
  File "/home/user/connectedhomeip/scripts/examples/../../scripts/tools/zap/generate.py", line 218, in main
    runGeneration(zap_file, zcl_file, templates_file, output_dir)
  File "/home/user/connectedhomeip/scripts/examples/../../scripts/tools/zap/generate.py", line 141, in runGeneration
    subprocess.check_call(['node', './src-script/zap-generate.js', '-z',
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', './src-script/zap-generate.js', '-z', '/home/user/connectedhomeip/src/app/zap-templates/zcl/zcl.json', '-g', '/home/user/connectedhomeip/src/app/zap-templates/app-templates.json', '-i', '/home/user/connectedhomeip/scripts/examples/../../examples/placeholder/linux/apps/app1/config.zap', '-o', '/home/user/connectedhomeip/scripts/examples/../../zzz_generated/placeholder/app1/zap-generated']' returned non-zero exit status 1.
```
