### ISSUE TITLE
[Workflow] Android full CI runs out of space in github CI

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#22485]
### Workflow issues

```bash
Running full android CI gets out of space:


System.IO.IOException: No space left on device : '/home/runner/runners/2.296.1/_diag/Worker_20220908-144851-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.296.1/_diag/Worker_20220908-144851-utc.log'
```

see

https://github.com/project-chip/connectedhomeip/actions/runs/3016038239/attempts/1
```


### Platform

android

### Anything else?

Smoke tests do pass, so we likely need to split out builds and cleanup after builds are made.

**Comment by andy31415** [comment]
Looking through android yaml it also seems we do 'submodules' on checkout which is not needed if we use checkout_submodules.py
