### ISSUE TITLE
[1.0] Running into this new failure while trying to create the docker container 

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#22613]
### Reproduction steps

```bash
Creating the docker container for TH release 

Steps : 
1. docker buildx create --use --name mybuild
2. docker run --privileged --rm tonistiigi/binfmt --install all
3. docker login 
4. cd to connectedhomeip/integrations/docker/images/chip-cert-bins
5. docker buildx build --build-arg COMMITHASH=0f593d21c16ddc188485a763cc3a78dcbcecc4b9 --platform linux/arm64 --tag connectedhomeip/chip-cert-bins:0f593d21c16ddc188485a763cc3a78dcbcecc4b9 --push .
```

### Bug prevalence

100% reproducible

### GitHub hash of the SDK that was being used

0f593d21c16ddc188485a763cc3a78dcbcecc4b9

### Platform

raspi

### Type

Platform Issue, Core SDK Memory Issue

### Anything else?

Error Snippet 
```

 => ERROR [stage-2 23/23] RUN pip install --no-cache-dir python_lib/controller/python/chip*.whl                                                                     14.1s
------
 > [stage-2 23/23] RUN pip install --no-cache-dir python_lib/controller/python/chip*.whl:
#0 0.408 Processing ./python_lib/controller/python/chip_clusters-0.0-py3-none-any.whl
#0 0.414 Processing ./python_lib/controller/python/chip_core-0.0-cp37-abi3-linux_aarch64.whl
#0 0.416 Processing ./python_lib/controller/python/chip_repl-0.0-py3-none-any.whl
#0 0.561 Collecting dacite
#0 0.948   Downloading dacite-1.6.0-py3-none-any.whl (12 kB)
#0 1.018 Collecting deprecation
#0 1.073   Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
#0 1.129 Collecting construct
#0 1.197   Downloading construct-2.10.68.tar.gz (57 kB)
#0 1.239      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.9/57.9 KB 1.2 MB/s eta 0:00:00
#0 1.251   Preparing metadata (setup.py): started
#0 1.379   Preparing metadata (setup.py): finished with status 'done'
#0 1.408 Collecting pygobject
#0 1.439   Downloading PyGObject-3.42.2.tar.gz (719 kB)
#0 1.572      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.5/719.5 KB 5.8 MB/s eta 0:00:00
#0 1.763   Installing build dependencies: started
#0 8.756   Installing build dependencies: finished with status 'done'
#0 8.760   Getting requirements to build wheel: started
#0 8.857   Getting requirements to build wheel: finished with status 'done'
#0 8.859   Preparing metadata (pyproject.toml): started
#0 8.956   Preparing metadata (pyproject.toml): finished with status 'done'
#0 8.990 Collecting pycrypto
#0 9.038   Downloading pycrypto-2.6.1.tar.gz (446 kB)
#0 9.062      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 446.2/446.2 KB 18.9 MB/s eta 0:00:00
#0 9.089   Preparing metadata (setup.py): started
#0 9.160   Preparing metadata (setup.py): finished with status 'done'
#0 9.251 Collecting rich
#0 9.283   Downloading rich-12.5.1-py3-none-any.whl (235 kB)
#0 9.299      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.6/235.6 KB 15.9 MB/s eta 0:00:00
#0 9.493 Collecting cryptography
#0 9.544   Downloading cryptography-38.0.1-cp36-abi3-manylinux_2_28_aarch64.whl (4.0 MB)
#0 9.929      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 10.4 MB/s eta 0:00:00
#0 9.975 Collecting ecdsa
#0 10.02   Downloading ecdsa-0.18.0-py2.py3-none-any.whl (142 kB)
#0 10.03      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.9/142.9 KB 39.2 MB/s eta 0:00:00
#0 10.07 Collecting mobly
#0 10.12   Downloading mobly-1.12.tar.gz (192 kB)
#0 10.14      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.3/192.3 KB 8.4 MB/s eta 0:00:00
#0 10.17   Preparing metadata (setup.py): started
#0 10.25   Preparing metadata (setup.py): finished with status 'done'
#0 10.25 Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from chip-core==0.0) (5.4.1)
#0 10.29 Collecting dbus-python
#0 10.32   Downloading dbus-python-1.3.2.tar.gz (605 kB)
#0 10.41      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 605.5/605.5 KB 7.3 MB/s eta 0:00:00
#0 10.50   Installing build dependencies: started
#0 13.96   Installing build dependencies: finished with status 'done'
#0 13.96   Getting requirements to build wheel: started
#0 14.02   Getting requirements to build wheel: finished with status 'error'
#0 14.02   error: subprocess-exited-with-error
#0 14.02   
#0 14.02   × Getting requirements to build wheel did not run successfully.
#0 14.02   │ exit code: 1
#0 14.02   ╰─> [35 lines of output]
#0 14.02       + meson setup --native-file=/tmp/pip-install-7hk8seia/dbus-python_709fffadbd8e4ed692db9da66f9ab7c5/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/usr /tmp/pip-install-7hk8seia/dbus-python_709fffadbd8e4ed692db9da66f9ab7c5 /tmp/pip-install-7hk8seia/dbus-python_709fffadbd8e4ed692db9da66f9ab7c5/.mesonpy-4hd6hv7u/build
#0 14.02       Traceback (most recent call last):
#0 14.02         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#0 14.02           main()
#0 14.02         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#0 14.02           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 14.02         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
#0 14.02           return hook(config_settings)
#0 14.02         File "/tmp/pip-build-env-1fn11254/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 923, in get_requires_for_build_wheel
#0 14.02           with _project(config_settings) as project:
#0 14.02         File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
#0 14.02           return next(self.gen)
#0 14.02         File "/tmp/pip-build-env-1fn11254/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 902, in _project
#0 14.02           with Project.with_temp_working_dir(
#0 14.02         File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
#0 14.02           return next(self.gen)
#0 14.02         File "/tmp/pip-build-env-1fn11254/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 547, in with_temp_working_dir
#0 14.02           yield cls(source_dir, tmpdir, build_dir)
#0 14.02         File "/tmp/pip-build-env-1fn11254/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 463, in __init__
#0 14.02           self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
#0 14.02         File "/tmp/pip-build-env-1fn11254/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 494, in _configure
#0 14.02           self._meson(
#0 14.02         File "/tmp/pip-build-env-1fn11254/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 477, in _meson
#0 14.02           return self._proc('meson', *args)
#0 14.02         File "/tmp/pip-build-env-1fn11254/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 472, in _proc
#0 14.02           subprocess.check_call(list(args))
#0 14.02         File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
#0 14.02           retcode = call(*popenargs, **kwargs)
#0 14.02         File "/usr/lib/python3.10/subprocess.py", line 345, in call
#0 14.02           with Popen(*popenargs, **kwargs) as p:
#0 14.02         File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
#0 14.02           self._execute_child(args, executable, preexec_fn, close_fds,
#0 14.02         File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
#0 14.02           raise child_exception_type(errno_num, err_msg, err_filename)
#0 14.02       FileNotFoundError: [Errno 2] No such file or directory: 'meson'
#0 14.02       [end of output]
#0 14.02   
#0 14.02   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 14.02 error: subprocess-exited-with-error
#0 14.02 
#0 14.02 × Getting requirements to build wheel did not run successfully.
#0 14.02 │ exit code: 1
#0 14.02 ╰─> See above for output.
#0 14.02 
#0 14.02 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:285
--------------------
 283 |     COPY --from=chip-build-cert-bins /root/connectedhomeip/out/python_lib python_lib
 284 |     COPY --from=chip-build-cert-bins /root/connectedhomeip/src/python_testing python_testing
 285 | >>> RUN pip install --no-cache-dir python_lib/controller/python/chip*.whl
 286 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir python_lib/controller/python/chip*.whl" did not complete successfully: exit code: 1
testingmatters@TestingMatterss-MacBook-Pro chip-cert-bins % 

```
Uploading the full failure logs here : 
[Docker_failure_logs.rtf.zip](https://github.com/project-chip/connectedhomeip/files/9562925/Docker_failure_logs.rtf.zip)

Was able to successfully create the docker container while using an older SDK SHA 8b6c0c0a7337c76c016891e26cc7b8df066b0739. 

Issue reproduces on 4 different setups , blocking us from creating a new TH image for SVE-2

**Comment by tcarmelveilleux** [comment]
This is because version 1.3.0 that is the newest available without version constraints, requires `meson` which we do not install. Let's pin to 1.2.18 while we resolve, to get back to early SVE2 state.
