### ISSUE TITLE
[Platform] RPC console missing whl in artifacts

### ISSUE THREAD

**Issue by rgoliver** [project-chip/connectedhomeip#22902]
### Reproduction steps / Feature

```bash
Rpc console packages is missing the tokenizer whl in the artifacts:


Traceback (most recent call last):
  File "/home/gtvchrome/venv/rpc_console/bin/chip-console", line 5, in <module>
    from chip_rpc.console import main
  File "/home/gtvchrome/venv/rpc_console/lib/python3.9/site-packages/chip_rpc/console.py", line 61, in <module>
    from pw_tokenizer.database import LoadTokenDatabases
ModuleNotFoundError: No module named 'pw_tokenizer'
```
```


### Platform

python

### Platform Version(s)

_No response_

### Type

Manually tested with SDK

### (Optional) If manually tested please explain why this is only manually tested

Error occurs while installing tool artifacts: `pip install out/chip-console-whl/*.whl`

### Anything else?

_No response_

**Comment by bzbarsky-apple** [comment]
@rgoliver Was this fixed by #22875?
