### ISSUE TITLE
[Errno 2] No such file or directory: 'pkg-config' ['pkg-config', '--cflags', '--libs', 'openssl'] IOS Compile in MacBook M1

### ISSUE THREAD

**Issue by aelposhi** [project-chip/connectedhomeip#23373]
### Reproduction steps

```bash
+ mkdir -p /Users/aelposhi/Library/Developer/Xcode/DerivedData/Darwin-fiarwprtkzhzakagiaewjawagrju/Build/Intermediates.noindex/Matter.build/Debug-maccatalyst/Matter.build
+ export
+ defines=()
+ declare -a defines
+ read -r -a defines
+ declare target_defines=
+ for define in '"${defines[@]}"'
+ case "$define" in
+ continue
+ for define in '"${defines[@]}"'
+ case "$define" in
+ target_defines+=',"CHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=<lib/address_resolve/AddressResolve_DefaultImpl.h>"'
+ for define in '"${defines[@]}"'
+ case "$define" in
+ target_defines+=',"DEBUG=1"'
+ for define in '"${defines[@]}"'
+ case "$define" in
+ target_defines+=',"CHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=<lib/address_resolve/AddressResolve_DefaultImpl.h>"'
+ target_defines='["CHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=<lib/address_resolve/AddressResolve_DefaultImpl.h>","DEBUG=1","CHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=<lib/address_resolve/AddressResolve_DefaultImpl.h>"]'
+ declare target_arch=
+ declare target_cpu=
+ declare target_cflags=
+ read -r -a archs
+ for arch in '"${archs[@]}"'
+ '[' -z ']' ']'
+ '[' -n '' ']'
+ target_cflags+='"-arch","arm64"'
+ [[ NO == YES ]]
+ args=('default_configs_cosmetic=[]' 'chip_crypto="boringssl"' 'chip_build_tools=false' 'chip_build_tests=false' 'chip_enable_wifi=false' 'chip_log_message_max_size=4096' 'chip_disable_platform_kvs=true' "target_cpu=\"$target_cpu\"" "target_defines=$target_defines" "target_cflags=[$target_cflags]" "mac_target_arch=\"$target_arch\"" "mac_deployment_target=\"$LLVM_TARGET_TRIPLE_OS_VERSION$LLVM_TARGET_TRIPLE_SUFFIX\"")
+ declare -a args
+ [[ Debug == Debug ]]
+ args+=('is_debug=true')
+ [[ macOS != macOS ]]
+ [[ macOS == macOS ]]
+ args+=('target_os="mac"')
+ cd '/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip'
++ find_in_ancestors chip_xcode_build_connector_env.sh
+ ENV=
+ [[ -n '' ]]
+ scripts/checkout_submodules.py --shallow --platform darwin
Checking out: nlassert, nlfaultinjection, nlio, nlunit-test, mbedtls, qrcode, pigweed, openthread, nanopb, zap, third_party/pybind11/repo, third_party/jsoncpp/repo, editline, third_party/boringssl/repo/src, open-iot-sdk-storage
+ [[ -z '' ]]
+ env -i PW_ENVSETUP_NO_BANNER=1 PW_ENVSETUP_QUIET=1 bash -c '. scripts/activate.sh'

AUTO-DETECTING input matter IDL file.
AUTO-DETECTING input matter IDL file.
ERROR at //build/config/linux/pkg_config.gni:116:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/gn_out/
Command: python3 /Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/build/config/linux/pkg-config.py openssl
Returned 1 and printed out:

[Errno 2] No such file or directory: 'pkg-config' ['pkg-config', '--cflags', '--libs', 'openssl']
/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/pigweed-venv/bin:/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/cipd/packages/pigweed/bin:/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/cipd/packages/pigweed:/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/cipd:/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.

stderr:

Could not run pkg-config.

See //src/crypto/BUILD.gn:83:3: whence it was called.
  pkg_config("openssl_config") {
  ^-----------------------------
See //BUILD.gn:152:7: which caused the file to be included.
      "${chip_root}/src/crypto",
      ^------------------------
['gn', 'gen', '/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/gn_out', '--args=dir_pigweed="/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo"']

Traceback (most recent call last):
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 310, in install_packages
    subprocess.check_call(gn_cmd,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/gn_out', '--args=dir_pigweed="/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 795, in <module>
    sys.exit(main())
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 787, in main
    return EnvSetup(**vars(parse())).setup()
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 457, in setup
    result = step(spin)
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 606, in virtualenv
    if not virtualenv_setup.install(
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 342, in install
    install_packages(gn_target)
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 317, in install_packages
    raise subprocess.CalledProcessError(err.returncode, err.cmd,
subprocess.CalledProcessError: Command '['gn', 'gen', '/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/gn_out', '--args=dir_pigweed="/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.
+ set +ex

AUTO-DETECTING input matter IDL file.
AUTO-DETECTING input matter IDL file.
ERROR at //build/config/linux/pkg_config.gni:116:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/gn_out/
Command: python3 /Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/build/config/linux/pkg-config.py openssl
Returned 1 and printed out:

[Errno 2] No such file or directory: 'pkg-config' ['pkg-config', '--cflags', '--libs', 'openssl']
/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/pigweed-venv/bin:/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/cipd/packages/pigweed/bin:/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/cipd/packages/pigweed:/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/cipd:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/appleinternal/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/appleinternal/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

stderr:

Could not run pkg-config.

See //src/crypto/BUILD.gn:83:3: whence it was called.
  pkg_config("openssl_config") {
  ^-----------------------------
See //BUILD.gn:152:7: which caused the file to be included.
      "${chip_root}/src/crypto",
      ^------------------------
['gn', 'gen', '/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/gn_out', '--args=dir_pigweed="/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo"']

Traceback (most recent call last):
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 310, in install_packages
    subprocess.check_call(gn_cmd,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/gn_out', '--args=dir_pigweed="/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 795, in <module>
    sys.exit(main())
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 787, in main
    return EnvSetup(**vars(parse())).setup()
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 457, in setup
    result = step(spin)
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 606, in virtualenv
    if not virtualenv_setup.install(
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 342, in install
    install_packages(gn_target)
  File "/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 317, in install_packages
    raise subprocess.CalledProcessError(err.returncode, err.cmd,
subprocess.CalledProcessError: Command '['gn', 'gen', '/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/.environment/gn_out', '--args=dir_pigweed="/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.
+ cd /Users/aelposhi/Library/Developer/Xcode/DerivedData/Darwin-fiarwprtkzhzakagiaewjawagrju/Build/Intermediates.noindex/Matter.build/Debug-maccatalyst/Matter.build
+ gn '--root=/Volumes/Data Disk/Matter/ConnectedHomeIP/connectedhomeip' gen --check out '--args=default_configs_cosmetic=[] chip_crypto="boringssl" chip_build_tools=false chip_build_tests=false chip_enable_wifi=false chip_log_message_max_size=4096 chip_disable_platform_kvs=true target_cpu="" target_defines=["CHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=<lib/address_resolve/AddressResolve_DefaultImpl.h>","DEBUG=1","CHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=<lib/address_resolve/AddressResolve_DefaultImpl.h>"] target_cflags=["-arch","arm64"] mac_target_arch="" mac_deployment_target="ios13.4-macabi" is_debug=true target_os="mac"'
./chip_xcode_build_connector.sh: line 156: gn: command not found
Command PhaseScriptExecution failed with a nonzero exit code
```

### Bug prevalence

Every time

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/tree/master/src/darwin/CHIPTool

### Platform

darwin

### Platform Version(s)

1.0

### Anything else?

Hello Everyone,

I tried to compile the IOS app through Xcode, and I received many errors. The last one is listed. I installed the pkg-config already, but Xcode still couldn't find it inside the folder, I don't know actually which folder he is searching for the pkg in.

Can you advise, please?

**Comment by aelposhi** [comment]
I followed this [guide](https://noknow.info/it/os/install_pkg_config_from_source?lang=en ) to create a Symbolic Link for the installed pkg-config library with /usr/local/bin/
