### ISSUE TITLE
[PSoC6] cannot erase flash 

### ISSUE THREAD

**Issue by mmt-10** [project-chip/connectedhomeip#23395]
### Reproduction steps

```bash
$ python3 out/infineon-psoc6-lock/chip-psoc6-lock-example.flash.py -h
usage: chip-psoc6-lock-example.flash.py [-h] [--verbose] [--erase] [--application FILE] [--verify_application] [--reset] [--skip_reset] [--make FILE] [--device DEVICE] [--sdk_path SDK_PATH]

Flash PSOC6 device

optional arguments:
  -h, --help            show this help message and exit

configuration:
  --verbose, -v         Report more verbosely
  --make FILE           File name of the make executable
  --device DEVICE, -d DEVICE
                        Device family or platform to target
  --sdk_path SDK_PATH, --sdk-path SDK_PATH, -p SDK_PATH
                        Path to psoc6 sdk

operations:
  --erase               Erase device
  --application FILE    Flash an image
  --verify_application, --verify-application
                        Verify the image after flashing
  --reset               Reset device after flashing
  --skip_reset, --skip-reset
                        Do not reset device after flashing

$ python3 out/infineon-psoc6-lock/chip-psoc6-lock-example.flash.py --erase
Traceback (most recent call last):
  File "out/infineon-psoc6-lock/chip-psoc6-lock-example.flash.py", line 13, in <module>
    sys.exit(psoc6_firmware_utils.Flasher(**DEFAULTS).flash_command(sys.argv))
  File "/home/mmt-10/matter/matter-v1.0/out/infineon-psoc6-lock/firmware_utils.py", line 387, in flash_command
    return self.parse_argv(argv).actions().status()
  File "/home/mmt-10/matter/matter-v1.0/out/infineon-psoc6-lock/psoc6_firmware_utils.py", line 127, in actions
    if self.erase().err:
  File "/home/mmt-10/matter/matter-v1.0/out/infineon-psoc6-lock/psoc6_firmware_utils.py", line 106, in erase
    raise NotImplementedError()
NotImplementedError
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

commit 7f2b0a5920d1a7acc202c2932ac4c626c54cd31e (HEAD -> v1.0-branch, origin/v1.0-branch)

### Platform

other

### Anything else?

does not run --erase option.

**Comment by bzbarsky-apple** [comment]
@praveenCY Could you take a look please?
