### ISSUE TITLE
[BUG] [Android] Service Discovery start fail when using specific service type

### ISSUE THREAD

**Issue by jeonghwan7** [project-chip/connectedhomeip#25235]
### Reproduction steps

Service Discovery start fail when using specific service type (_S9._sub._matterc._udp)

Hi, Service Discovery fail when using specific service type like _S9._sub._matterc._udp
without sub type (_matterc._udp) is working well.

It is mandatory function for just using manual pairing code and QR Code pairing.

Log is below 
`02-22 10:01:54.414 D 31680    31680    NsdManagerServiceBrowser:                                                Starting service discovering for _S9._sub._matterc._udp 
.....
02-22 10:01:54.626 E 1039     15809    MDnsDS                                                                    : Discover request 732 got an error from DNSServiceBrowse -65540 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             Discover service failed. 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             android.os.ServiceSpecificException: Unknown error -65540 (code -65540) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.os.Parcel.createExceptionOrNull(Parcel.java:3037) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.os.Parcel.createException(Parcel.java:3007) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.os.Parcel.readException(Parcel.java:2990) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.os.Parcel.readException(Parcel.java:2932) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.net.connectivity.android.net.mdns.aidl.IMDns$Stub$Proxy.discover(IMDns.java:269) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.net.connectivity.android.net.nsd.MDnsManager.discover(MDnsManager.java:107) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at com.android.server.NsdService.discoverServices(NsdService.java:818) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at com.android.server.NsdService.-$$Nest$mdiscoverServices(Unknown Source:0) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at com.android.server.NsdService$NsdStateMachine$EnabledState.processMessage(NsdService.java:314) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.net.connectivity.com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:993) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.net.connectivity.com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:810) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.os.Handler.dispatchMessage(Handler.java:106) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.os.Looper.loopOnce(Looper.java:226) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.os.Looper.loop(Looper.java:313) 
02-22 10:01:54.636 E 1590     2299     MDnsManager:                                                             	at android.os.HandlerThread.run(HandlerThread.java:67) 
02-22 10:01:54.636 E 1039     15809    MDnsDS                                                                    : Stop used unknown requestId 732 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             Stop operation failed. 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             android.os.ServiceSpecificException: No such process (code 3) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.os.Parcel.createExceptionOrNull(Parcel.java:3037) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.os.Parcel.createException(Parcel.java:3007) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.os.Parcel.readException(Parcel.java:2990) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.os.Parcel.readException(Parcel.java:2932) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.net.connectivity.android.net.mdns.aidl.IMDns$Stub$Proxy.stopOperation(IMDns.java:323) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.net.connectivity.android.net.nsd.MDnsManager.stopOperation(MDnsManager.java:167) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at com.android.server.NsdService.stopServiceDiscovery(NsdService.java:822) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at com.android.server.NsdService.-$$Nest$mstopServiceDiscovery(Unknown Source:0) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at com.android.server.NsdService$NsdStateMachine$EnabledState.processMessage(NsdService.java:322) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.net.connectivity.com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:993) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.net.connectivity.com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:810) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.os.Handler.dispatchMessage(Handler.java:106) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.os.Looper.loopOnce(Looper.java:226) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.os.Looper.loop(Looper.java:313) 
02-22 10:01:54.637 E 1590     2299     MDnsManager:                                                             	at android.os.HandlerThread.run(HandlerThread.java:67) 
02-22 10:01:54.638 W 31680    31780    NsdManagerServiceBrowser:                                                Failed to start discovery service _S9._sub._matterc._udp: 0 

`

### Bug prevalence

everytime

### GitHub hash of the SDK that was being used

5f058f9232cd7b050b98c6752302ac3282464e5b

### Platform

android

**Comment by jeonghwan7** [comment]
It seems that Android NsdService don't support dns sd subtype(_S9._sub.)

Actually, I have tried to another way to resolve this issue.
For example 
1. We try to find  "_matterc._udp" 
2. If device found, ㅑ checked if it could be processed within the second found callback, but it seems impossible because the Service Info object does not contain a service type.

`    @Override
    public void onServiceFound(NsdServiceInfo serviceInfo) {
      Log.i(TAG, "Found service '" + serviceInfo.getServiceName() + "' service info "+serviceInfo.getServiceType() + "service "+serviceInfo);
      serviceNameList.add(serviceInfo.getServiceName());
    }`
