### ISSUE TITLE
[1.0] some error with android chiptool 

### ISSUE THREAD

**Issue by cyyyys** [project-chip/connectedhomeip#25270]
### Reproduction steps

here is the error log with ubuntu. 

ffx@ffx-virtual-machine:~/workspace/matter/code/tag_1.0.0.2/connectedhomeip$ ./scripts/build/build_examples.py --target android-arm64-chip-tool build
2023-02-23 10:33:35 INFO    Building targets: android-arm64-chip-tool
2023-02-23 10:33:35 INFO    Preparing builder 'android-arm64-chip-tool'
2023-02-23 10:33:35 INFO    Generating /home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/out/android-arm64-chip-tool
2023-02-23 10:33:35 INFO    Setting up Android deps through Gradle
2023-02-23 10:33:36 INFO    > Task :buildSrc:compileJava NO-SOURCE
2023-02-23 10:33:36 INFO    > Task :buildSrc:compileGroovy UP-TO-DATE
2023-02-23 10:33:36 INFO    > Task :buildSrc:processResources NO-SOURCE
2023-02-23 10:33:36 INFO    > Task :buildSrc:classes UP-TO-DATE
2023-02-23 10:33:36 INFO    > Task :buildSrc:jar UP-TO-DATE
2023-02-23 10:33:36 INFO    > Task :buildSrc:assemble UP-TO-DATE
2023-02-23 10:33:36 INFO    > Task :buildSrc:compileTestJava NO-SOURCE
2023-02-23 10:33:36 INFO    > Task :buildSrc:compileTestGroovy NO-SOURCE
2023-02-23 10:33:36 INFO    > Task :buildSrc:processTestResources NO-SOURCE
2023-02-23 10:33:36 INFO    > Task :buildSrc:testClasses UP-TO-DATE
2023-02-23 10:33:36 INFO    > Task :buildSrc:test NO-SOURCE
2023-02-23 10:33:36 INFO    > Task :buildSrc:check UP-TO-DATE
2023-02-23 10:33:36 INFO    > Task :buildSrc:build UP-TO-DATE
2023-02-23 10:33:36 INFO    > Task :copyArtifacts UP-TO-DATE
2023-02-23 10:33:36 INFO    > Task :setUpAndroidDeps
2023-02-23 10:33:36 INFO    
2023-02-23 10:33:36 INFO    BUILD SUCCESSFUL in 948ms
2023-02-23 10:33:36 INFO    4 actionable tasks: 1 executed, 3 up-to-date
2023-02-23 10:33:37 INFO    Command ['python3', 'third_party/android_deps/set_up_android_deps.py'] completed
2023-02-23 10:33:37 INFO    Setting up Java deps
2023-02-23 10:33:37 WARNING third_party/java_deps/set_up_java_deps.sh: 行 20: curl：未找到命令
2023-02-23 10:33:37 WARNING third_party/java_deps/set_up_java_deps.sh: 行 21: curl：未找到命令
Traceback (most recent call last):
  File "./scripts/build/build_examples.py", line 208, in <module>
    main(auto_envvar_prefix='CHIP')
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./scripts/build/build_examples.py", line 198, in cmd_build
    context.obj.Build()
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/scripts/build/build/__init__.py", line 67, in Build
    self.Generate()
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/scripts/build/build/__init__.py", line 62, in Generate
    builder.generate()
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/scripts/build/builders/android.py", line 313, in generate
    self._Execute(
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/scripts/build/builders/builder.py", line 104, in _Execute
    self._runner.Run(cmdarray, title=title)
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/scripts/build/runner/shell.py", line 73, in Run
    raise Exception('Command %r failed: %d' % (cmd, code))
Exception: Command ['third_party/java_deps/set_up_java_deps.sh'] failed: 127

### Bug prevalence

not a bug

### GitHub hash of the SDK that was being used

tag 1.0.0.2

### Platform

android

### Type

Test Improvement

**Comment by cyyyys** [comment]
ffx@ffx-virtual-machine:~/workspace/matter/code/tag_1.0.0.2/connectedhomeip$ ./scripts/build/build_examples.py --target android-arm64-chip-tool build
2023-02-24 19:04:12 INFO    Building targets: android-arm64-chip-tool
2023-02-24 19:04:12 INFO    Preparing builder 'android-arm64-chip-tool'
2023-02-24 19:04:12 INFO    Generating /home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/out/android-arm64-chip-tool
2023-02-24 19:04:12 INFO    Setting up Android deps through Gradle
2023-02-24 19:04:15 INFO    > Task :buildSrc:compileJava NO-SOURCE
2023-02-24 19:04:15 INFO    > Task :buildSrc:compileGroovy UP-TO-DATE
2023-02-24 19:04:15 INFO    > Task :buildSrc:processResources NO-SOURCE
2023-02-24 19:04:15 INFO    > Task :buildSrc:classes UP-TO-DATE
2023-02-24 19:04:15 INFO    > Task :buildSrc:jar UP-TO-DATE
2023-02-24 19:04:15 INFO    > Task :buildSrc:assemble UP-TO-DATE
2023-02-24 19:04:15 INFO    > Task :buildSrc:compileTestJava NO-SOURCE
2023-02-24 19:04:15 INFO    > Task :buildSrc:compileTestGroovy NO-SOURCE
2023-02-24 19:04:15 INFO    > Task :buildSrc:processTestResources NO-SOURCE
2023-02-24 19:04:15 INFO    > Task :buildSrc:testClasses UP-TO-DATE
2023-02-24 19:04:15 INFO    > Task :buildSrc:test NO-SOURCE
2023-02-24 19:04:15 INFO    > Task :buildSrc:check UP-TO-DATE
2023-02-24 19:04:15 INFO    > Task :buildSrc:build UP-TO-DATE
2023-02-24 19:04:15 INFO    > Task :copyArtifacts UP-TO-DATE
2023-02-24 19:04:15 INFO    > Task :setUpAndroidDeps
2023-02-24 19:04:15 INFO    
2023-02-24 19:04:15 INFO    BUILD SUCCESSFUL in 3s
2023-02-24 19:04:15 INFO    4 actionable tasks: 1 executed, 3 up-to-date
2023-02-24 19:04:16 INFO    Command ['python3', 'third_party/android_deps/set_up_android_deps.py'] completed
2023-02-24 19:04:16 INFO    Setting up Java deps
2023-02-24 19:04:16 WARNING mkdir: 无法创建目录 “third_party/java_deps/artifacts”: 文件已存在
2023-02-24 19:04:18 INFO    Command ['third_party/java_deps/set_up_java_deps.sh'] completed
Traceback (most recent call last):
  File "./scripts/build/build_examples.py", line 208, in <module>
    main(auto_envvar_prefix='CHIP')
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./scripts/build/build_examples.py", line 198, in cmd_build
    context.obj.Build()
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/scripts/build/build/__init__.py", line 67, in Build
    self.Generate()
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/scripts/build/build/__init__.py", line 62, in Generate
    builder.generate()
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/scripts/build/builders/android.py", line 321, in generate
    self.validate_build_environment()
  File "/home/ffx/workspace/matter/code/tag_1.0.0.2/connectedhomeip/scripts/build/builders/android.py", line 141, in validate_build_environment
    raise Exception(
Exception: '/home/ffx/Android/Sdk/tools/bin/sdkmanager' and '/home/ffx/Android/Sdk/cmdline-tools/latest/bin/sdkmanager' is not executable by the current user

**Comment by cyyyys** [comment]
macos:
source scripts/bootstrap.sh

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...Traceback (most recent call last):
  File "/Users/congyuyang/matter/1.0.0.2/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 857, in <module>
    sys.exit(main())
  File "/Users/congyuyang/matter/1.0.0.2/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 849, in main
    return EnvSetup(**vars(parse())).setup()
  File "/Users/congyuyang/matter/1.0.0.2/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 501, in setup
    result = step(spin)
  File "/Users/congyuyang/matter/1.0.0.2/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 598, in cipd
    rosetta=self._rosetta,
  File "/Users/congyuyang/matter/1.0.0.2/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 378, in init
    bootstrap(client, silent, rosetta=rosetta)
  File "/Users/congyuyang/matter/1.0.0.2/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 328, in bootstrap
    tmp.write(client_bytes(rosetta))
  File "/Users/congyuyang/matter/1.0.0.2/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 252, in client_bytes
    conn.request('GET', path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
