### ISSUE TITLE
[BUG] Matter Cert test TC_RR_1_1 is failed to test 5 fabrics with 20 devices

### ISSUE THREAD

**Issue by dhdanh** [project-chip/connectedhomeip#25689]
### Reproduction steps

1. Run the script to test the test case TC_RR_1_1.py => 5 fabrics and 4 devices per fabric
2. It is passed if you run the same test with 4 fabrics and 4 devices per fabric
3. Please let me know if you need more information
4. Test script is attached [TC_RR_1_1.zip](https://github.com/project-chip/connectedhomeip/files/10978781/TC_RR_1_1.zip)

```
Traceback (most recent call last):
  File " /third_party/connectedhomeip/out/python_env/lib/python3.10/site-packages/mobly/base_test.py", line 777, in exec_one_test
    test_method()
  File " /third_party/connectedhomeip/src/python_testing/matter_testing_support.py", line 685, in async_runner
    return asyncio.run(body(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File " /third_party/connectedhomeip/src/python_testing/TC_RR_1_1.py", line 195, in test_TC_RR_1_1
    new_controllers = await CommissioningBuildingBlocks.CreateControllersOnFabric(
  File " /third_party/connectedhomeip/out/python_env/lib/python3.10/site-packages/chip/utils/CommissioningBuildingBlocks.py", line 122, in CreateControllersOnFabric
    newController = fabricAdmin.NewController(nodeId=nodeId, catTags=catTags)
  File " /third_party/connectedhomeip/out/python_env/lib/python3.10/site-packages/chip/FabricAdmin.py", line 100, in NewController
    controller = ChipDeviceCtrl.ChipDeviceController(
  File " /third_party/connectedhomeip/out/python_env/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 1413, in __init__
    ).raise_on_error()
  File " /third_party/connectedhomeip/out/python_env/lib/python3.10/site-packages/chip/native/__init__.py", line 67, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: ../../src/credentials/FabricTable.cpp:795: CHIP Error 0x0000000B: No memory
```

### Bug prevalence

all the time

### GitHub hash of the SDK that was being used

c1810b6d95cb2a946fc0ba71c6e63e88b15554cd

### Platform

esp32

**Comment by bzbarsky-apple** [comment]
`CHIP_CONFIG_MAX_FABRICS` defaults to 16 for tests.  You're asking to create 20 entries.  20 > 16, so it does not work.

If you want to make this change to the script, you need to compile the python controller with a larger `CHIP_CONFIG_MAX_FABRICS` value.
