### ISSUE TITLE
In the Provision chip device with wifi's input page, click Commission cause crash

### ISSUE THREAD

**Issue by BonyYeah** [project-chip/connectedhomeip#27117]
### Reproduction steps

1. PROVISION CHIP DEVICE WITH WI-FI
2. input device address
3. click COMMISSION

### Bug prevalence

always

### GitHub hash of the SDK that was being used

4f6923fe7c7df3dea22b3e9d5bc4944b888e5dbb

### Platform

android

### Platform Version(s)

Android 12

### Anything else?

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.google.chip.chiptool, PID: 8438
java.lang.NoSuchMethodError: no non-static method "Lchip/devicecontroller/ChipDeviceControllerException;.(ILjava/lang/String;)V"
at chip.devicecontroller.ChipDeviceController.pairDeviceWithAddress(Native Method)
at chip.devicecontroller.ChipDeviceController.pairDeviceWithAddress(ChipDeviceController.java:174)
at com.google.chip.chiptool.provisioning.DeviceProvisioningFragment.pairDeviceWithAddress(DeviceProvisioningFragment.kt:156)
at com.google.chip.chiptool.provisioning.DeviceProvisioningFragment.onCreateView(DeviceProvisioningFragment.kt:81)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by yunhanw-google** [comment]
It has been fixed with J https://github.com/project-chip/connectedhomeip/blame/f2fa44a2fe5880355ae6c53b03d38e3758c00ced/src/controller/java/AndroidControllerExceptions.cpp#L35
