### ISSUE TITLE
[Build] Darwin build failed

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#27427]
### Build issue(s)

https://github.com/project-chip/connectedhomeip/actions/runs/5352024097/jobs/9706522500

```
INFO    [592/616] ACTION //:build-darwin-framework(//third_party/connectedhomeip/build/toolchain/host:mac_x64_clang)
INFO    FAILED: macos_framework_output/Build/Products/Debug/Matter.framework darwin_framework_build.log macos_framework_output/ModuleCache.noindex macos_framework_output/Logs macos_framework_output/Index macos_framework_output/Build 
INFO    python ../../examples/darwin-framework-tool/third_party/connectedhomeip/scripts/build/build_darwin_framework.py --project_path ../../examples/darwin-framework-tool/third_party/connectedhomeip/src/darwin/Framework/Matter.xcodeproj --out_path macos_framework_output --target Matter\ Framework --log_path darwin_framework_build.log --target_arch x86_64 --no-ipv4 --asan --no-ble --clang --enable_encoding_sentinel_enum_values
INFO    Running ['xcodebuild', '-scheme', 'Matter Framework', '-sdk', 'macosx', '-project', '../../examples/darwin-framework-tool/third_party/connectedhomeip/src/darwin/Framework/Matter.xcodeproj', '-derivedDataPath', '/Users/runner/work/connectedhomeip/connectedhomeip/out/darwin-x64-darwin-framework-tool-no-ble-asan-clang/macos_framework_output', 'ARCHS=x86_64', 'CHIP_INET_CONFIG_ENABLE_IPV4=NO', 'CHIP_IS_ASAN=YES', 'CHIP_IS_BLE=NO', 'CHIP_IS_CLANG=YES', 'CHIP_ENABLE_ENCODING_SENTINEL_ENUM_VALUES=YES', 'CC=/Users/runner/work/connectedhomeip/connectedhomeip/examples/darwin-framework-tool/third_party/connectedhomeip/.environment/cipd/packages/pigweed/bin/clang', 'CXX=/Users/runner/work/connectedhomeip/connectedhomeip/examples/darwin-framework-tool/third_party/connectedhomeip/.environment/cipd/packages/pigweed/bin/clang++', 'COMPILER_INDEX_STORE_ENABLE=NO', 'CLANG_ENABLE_MODULES=NO', 'OTHER_CFLAGS=${inherited} -Wno-unguarded-availability-new -fsanitize=address -fno-omit-frame-pointer -DCHIP_CONFIG_IM_ENABLE_ENCODING_SENTINEL_ENUM_VALUES=1', 'OTHER_LDFLAGS=${inherited} -nostdlib++ /Users/runner/work/connectedhomeip/connectedhomeip/examples/darwin-framework-tool/third_party/connectedhomeip/.environment/cipd/packages/pigweed/lib/libc++.a -fsanitize=address -fno-omit-frame-pointer /Users/runner/work/connectedhomeip/connectedhomeip/examples/darwin-framework-tool/third_party/connectedhomeip/.environment/cipd/packages/pigweed/lib/clang/17/lib/darwin/libclang_rt.asan_osx_dynamic.dylib']
INFO    Build Framework Result: 65
INFO    ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/Users/runner/work/connectedhomeip/connectedhomeip/./scripts/build/build_examples.py", line 230, in <module>
    main(auto_envvar_prefix='CHIP')
  File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/runner/work/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/runner/work/connectedhomeip/connectedhomeip/./scripts/build/build_examples.py", line 220, in cmd_build
    context.obj.Build()
  File "/Users/runner/work/connectedhomeip/connectedhomeip/scripts/build/build/__init__.py", line 71, in Build
    builder.build()
  File "/Users/runner/work/connectedhomeip/connectedhomeip/scripts/build/builders/builder.py", line 99, in build
    self._build()
  File "/Users/runner/work/connectedhomeip/connectedhomeip/scripts/build/builders/gn.py", line 110, in _build
    self._Execute(cmd, title='Building ' + self.identifier)
  File "/Users/runner/work/connectedhomeip/connectedhomeip/scripts/build/builders/builder.py", line 104, in _Execute
    self._runner.Run(cmdarray, title=title)
  File "/Users/runner/work/connectedhomeip/connectedhomeip/scripts/build/runner/shell.py", line 73, in Run
    raise Exception('Command %r failed: %d' % (cmd, code))
Exception: Command ['ninja', '-C', '/Users/runner/work/connectedhomeip/connectedhomeip/out/darwin-x64-darwin-framework-tool-no-ble-asan-clang'] failed: 1
```

### Platform

darwin

**Comment by woody-apple** [comment]
here as well: https://github.com/project-chip/connectedhomeip/actions/runs/5352142294/jobs/9706758256
