### ISSUE TITLE
[Build] Darwin python parser no-ble-tsan failing

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#27524]
### Build issue(s)

https://github.com/project-chip/connectedhomeip/actions/runs/5398386504/jobs/9804137158?pr=27516

```
ERROR   08:39:54.460 - TEST OUT  : 		    [IN] (U) Sending msg 6874998 to IP address 'UDP:[fd00:0:1:1::3]:5540'
ERROR   08:39:54.460 - TEST OUT  : 		    [SC] Sent Sigma1 msg
ERROR   08:39:54.460 - TEST OUT  : 		    [DIS] OperationalSessionSetup[1:0000000012344321]: State change 3 --> 4
ERROR   08:39:54.460 - TEST OUT  : 		    [DIS] Failed to parse mDNS query
ERROR   08:39:54.460 - TEST OUT  : 		    [EM] Retransmitting MessageCounter:6874998 on exchange 3292i Send Cnt 1
ERROR   08:39:54.460 - TEST OUT  : 		    [IN] (U) Sending msg 6874998 to IP address 'UDP:[fd00:0:1:1::3]:5540'
ERROR   08:39:54.460 - TEST OUT  : 		    [DIS] Failed to parse mDNS query
ERROR   08:39:54.460 - TEST OUT  : 		    [DIS] Failed to parse mDNS query
ERROR   08:39:54.460 - TEST OUT  : 		    [EM] Retransmitting MessageCounter:6874998 on exchange 3292i Send Cnt 2
ERROR   08:39:54.460 - TEST OUT  : 		    [IN] (U) Sending msg 6874998 to IP address 'UDP:[fd00:0:1:1::3]:5540'
ERROR   08:39:54.460 - TEST OUT  : 		    [DIS] Failed to parse mDNS query
ERROR   08:39:54.460 - TEST OUT  : 		    [DIS] Failed to parse mDNS query
ERROR   08:39:54.460 - TEST OUT  : 		    [EM] Retransmitting MessageCounter:6874998 on exchange 3292i Send Cnt 3
ERROR   08:39:54.461 - TEST OUT  : 		    [IN] (U) Sending msg 6874998 to IP address 'UDP:[fd00:0:1:1::3]:5540'
ERROR   08:39:54.461 - TEST OUT  : 		    [DIS] Failed to parse mDNS query
ERROR   08:39:54.461 - TEST OUT  : 		    [DIS] Failed to parse mDNS query
ERROR   08:39:54.461 - TEST OUT  : 		    [DIS] Failed to parse mDNS query
ERROR   08:39:54.461 - TEST OUT  : 		    [EM] Retransmitting MessageCounter:6874998 on exchange 3292i Send Cnt 4
ERROR   08:39:54.461 - TEST OUT  : 		    [IN] (U) Sending msg 6874998 to IP address 'UDP:[fd00:0:1:1::3]:5540'
ERROR   08:39:54.461 - TEST OUT  : 		    [DIS] Failed to parse mDNS query
ERROR   08:39:54.461 - TEST OUT  : 		    [EM] Failed to Send CHIP MessageCounter:6874998 on exchange 3292i sendCount: 4 max retries: 4
ERROR   08:39:54.461 - TEST OUT  : 		    [SC] CASESession timed out while waiting for a response from the peer. Current state was 1
ERROR   08:39:54.461 - TEST OUT  : 		    [IN] SecureSession[0x7b3c000078f0]: Released - Type:2 LSID:63073
ERROR   08:39:54.461 - TEST OUT  : 		    [DIS] OperationalSessionSetup[1:0000000012344321]: State change 4 --> 2
ERROR   08:39:54.461 - TEST OUT  : 		    [DIS] OperationalSessionSetup[1:0000000012344321]: State change 2 --> 1
ERROR   08:39:54.462 - TEST OUT  : 		    [-] src/protocols/secure_channel/CASESession.cpp:493: CHIP Error 0x00000032: Timeout at ../../examples/chip-tool/commands/delay/WaitForCommissioneeCommand.cpp:46
ERROR   08:39:54.462 - TEST OUT  : 		    [TOO] Run command failure: src/protocols/secure_channel/CASESession.cpp:493: CHIP Error 0x00000032: Timeout
ERROR   08:39:54.462 - TEST OUT  : 		    Expected: [
ERROR   08:39:54.462 - TEST OUT  : 		                {
ERROR   08:39:54.462 - TEST OUT  : 		                  "values": [
ERROR   08:39:54.462 - TEST OUT  : 		                    {}
ERROR   08:39:54.462 - TEST OUT  : 		                  ]
ERROR   08:39:54.462 - TEST OUT  : 		                }
ERROR   08:39:54.462 - TEST OUT  : 		              ]
ERROR   08:39:54.462 - TEST OUT  : 		    Received: [
ERROR   08:39:54.462 - TEST OUT  : 		                 {
ERROR   08:39:54.462 - TEST OUT  : 		                   "error": "FAILURE"
ERROR   08:39:54.462 - TEST OUT  : 		                 }
ERROR   08:39:54.462 - TEST OUT  : 		               ]
ERROR   08:39:54.462 - TEST OUT  : 		***** Test Failure : The test expects no error but the "FAILURE" error occured.
ERROR   08:39:54.462 - TEST OUT  : 		**** Test Setup: Device Connection Failure [deviceId=305414945. Error The test expects no error but the "FAILURE" error occured.]
ERROR   08:39:54.463 - TEST OUT  : ✗ Test finished in 6461ms with 0 success, 1 errors and 0 warnings
ERROR   ================ CAPTURED LOG END ====================
ERROR   TestSelfFabricRemoval          - FAILED in 9.78 seconds
Traceback (most recent call last):
  File "/__w/connectedhomeip/connectedhomeip/./scripts/tests/run_test_suite.py", line 344, in cmd_run
    test.Run(
  File "/__w/connectedhomeip/connectedhomeip/scripts/tests/chiptest/test_definition.py", line 340, in Run
    runner.RunSubprocess(
  File "/__w/connectedhomeip/connectedhomeip/scripts/tests/chiptest/runner.py", line 167, in RunSubprocess
    raise Exception('Command %r failed: %d' % (cmd, s.returncode))
Exception: Command ['ip', 'netns', 'exec', 'tool', 'python3', '/__w/connectedhomeip/connectedhomeip/scripts/tests/yaml/chiptool.py', 'tests', 'TestSelfFabricRemoval', '--PICS', 'src/app/tests/suites/certification/ci-pics-values', '--server_path', './out/linux-x64-chip-tool-no-ble-tsan-clang/chip-tool', '--server_arguments', 'interactive server --storage-directory /tmp/tmphgafbthn'] failed: 1
Error: Process completed with exit code 2.
```

**Comment by woody-apple** [comment]
Another here: https://github.com/project-chip/connectedhomeip/actions/runs/5398386504/jobs/9804137158?pr=27516

**Comment by woody-apple** [comment]
`Running Wait for the commissioned device to be retrieved` is timing out

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/actions/runs/5403870057/jobs/9817290510
https://github.com/project-chip/connectedhomeip/actions/runs/5403976009/jobs/9817540869

**Comment by woody-apple** [comment]
Escalated here: https://support.github.com/ticket/personal/0/2240190

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/actions/runs/5471128459/jobs/9961958585#logs
https://github.com/project-chip/connectedhomeip/actions/runs/5467947144/jobs/9954929582
https://github.com/project-chip/connectedhomeip/actions/runs/5465839678/jobs/9949886784
https://github.com/project-chip/connectedhomeip/actions/runs/5465306649/jobs/9948563815
https://github.com/project-chip/connectedhomeip/actions/runs/5464784980/jobs/9947297255
https://github.com/project-chip/connectedhomeip/actions/runs/5464288218
