### ISSUE TITLE
Getting JNI Reference Error

### ISSUE THREAD

**Issue by thejaimin** [project-chip/connectedhomeip#28196]
### Reproduction steps

I used https://github.com/google-home/sample-app-for-matter-android repo 

App getting crashed while I build APK(Debug) from android studio and then install it.

but If I run the app from android studio  then It works, I don't understand, What is the difference between run app and build APK?

Caused by: chip.devicecontroller.ChipDeviceControllerException: ../../src/lib/support/JniReferences.cpp:124: Error 0x00000702
at chip.devicecontroller.ChipDeviceController.newDeviceController(Native Method)
at chip.devicecontroller.ChipDeviceController.(ChipDeviceController.java:58)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

NA

### Platform

android

**Comment by stevePalmerin** [comment]
Is there a solution for this? Noticed this bug today and it is currently a blocker for testing.
