### ISSUE TITLE
[Build] Build examples script fails for Ameba target on Ubuntu host

### ISSUE THREAD

**Issue by samryanuofl** [project-chip/connectedhomeip#28218]
### Build issue(s)

1. Did a clean checkout of the connectedhomeip repo (commit hash: 0e0fd72befb24759347c43c5eca2d88fc03d89d1)
2. Navigated to project root directory
3. Ran `source scripts/bootstrap.sh` and it succeeded
4. Ran `source scripts/activate.sh` and it succeeded
5. Ran `./scripts/build/build_examples.py --target ameba-amebad-all-clusters build`
6. Command failed with error below
...

Running on Ubuntu 22.04

```sam@ubuntu-dev:~/dev/connectedhomeip$ ./scripts/build/build_examples.py --target ameba-amebad-all-clusters build
2023-07-24 15:38:58 INFO    Building targets: ameba-amebad-all-clusters
2023-07-24 15:38:58 INFO    Preparing builder 'ameba-amebad-all-clusters'
2023-07-24 15:38:58 INFO    Generating /home/sam/dev/connectedhomeip/out/ameba-amebad-all-clusters
2023-07-24 15:38:58 INFO    Generating ameba-amebad-all-clusters
2023-07-24 15:38:58 WARNING bash: line 1: /project/realtek_amebaD_va0_example/GCC-RELEASE/build.sh: No such file or directory
Traceback (most recent call last):
  File "/home/sam/dev/connectedhomeip/./scripts/build/build_examples.py", line 230, in <module>
    main(auto_envvar_prefix='CHIP')
  File "/home/sam/dev/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/dev/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sam/dev/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/sam/dev/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/dev/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sam/dev/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sam/dev/connectedhomeip/./scripts/build/build_examples.py", line 220, in cmd_build
    context.obj.Build()
  File "/home/sam/dev/connectedhomeip/scripts/build/build/__init__.py", line 67, in Build
    self.Generate()
  File "/home/sam/dev/connectedhomeip/scripts/build/build/__init__.py", line 62, in Generate
    builder.generate()
  File "/home/sam/dev/connectedhomeip/scripts/build/builders/ameba.py", line 84, in generate
    self._Execute(['bash', '-c', cmd],
  File "/home/sam/dev/connectedhomeip/scripts/build/builders/builder.py", line 104, in _Execute
    self._runner.Run(cmdarray, title=title)
  File "/home/sam/dev/connectedhomeip/scripts/build/runner/shell.py", line 73, in Run
    raise Exception('Command %r failed: %d' % (cmd, code))
Exception: Command ['bash', '-c', '$AMEBA_PATH/project/realtek_amebaD_va0_example/GCC-RELEASE/build.sh /home/sam/dev/connectedhomeip ninja /home/sam/dev/connectedhomeip/out/ameba-amebad-all-clusters all-clusters-app'] failed: 127
```

### Platform

ameba

**Comment by woody-apple** [comment]
Closing older issues, trying to focus on current build failures
