### ISSUE TITLE
[CERT-TEST-FAILURE] TC-IDM-1.2.py 

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#29581]
### Feature Area

Other

### Test Case

TC-IDM-1.2

### Reproduction steps

Command to execute the TC_IDM_1_2.py : ` python3 TC_IDM_1_2.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --storage-path admin_storage.json --PICS ci-pics-values --paa-trust-store-path /credentials/development/paa-root-certs/`

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

19771ed7101321d68b87d05201d42d00adf5368f

### Platform

python, raspi

### Anything else?

TC_IDM_1_2.py is failed to pair the TH2.

> [MatterTest] 10-05 12:37:18.524 ERROR Exception occurred in test_TC_IDM_1_2.
Traceback (most recent call last):
  File "/root/python_testing/TC_IDM_1_2.py", line 210, in test_TC_IDM_1_2
    TH2.GetConnectedDeviceSync(nodeid=self.dut_node_id+1, allowPASE=True, timeoutMs=1000)
  File "/usr/local/lib/python3.10/dist-packages/chip/ChipDeviceCtrl.py", line 776, in GetConnectedDeviceSync
    raise TimeoutError("Timed out waiting for DNS-SD resolution")
TimeoutError: Timed out waiting for DNS-SD resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mobly/base_test.py", line 783, in exec_one_test
    test_method()
  File "/root/python_testing/matter_testing_support.py", line 1008, in async_runner
    return asyncio.run(body(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/python_testing/TC_IDM_1_2.py", line 212, in test_TC_IDM_1_2
    asserts.fail("Unable to establish a PASE session to the device")
  File "/usr/local/lib/python3.10/dist-packages/mobly/asserts.py", line 475, in fail
    raise signals.TestFailure(msg, extras)
mobly.signals.TestFailure: Details=Unable to establish a PASE session to the device, Extras=None
[MatterTest] 10-05 12:37:18.532 INFO [Test] test_TC_IDM_1_2 FAIL

**Log:**
[tc-idm-1-2.txt](https://github.com/project-chip/connectedhomeip/files/12818473/tc-idm-1-2.txt)

**Comment by Saravana-kr22** [comment]
This is setup issue, tried with other setup and passed.

[tc-idm-1-2.txt](https://github.com/project-chip/connectedhomeip/files/12853451/tc-idm-1-2.txt)
