### ISSUE TITLE
[BUG] Android project use ChipDeviceController will crash.

### ISSUE THREAD

**Issue by freemanspace** [project-chip/connectedhomeip#30566]
### Reproduction steps

1. use ChipClient.getDeviceController() to get ChipDeviceController.

2.use deviceController to do commission
    deviceController!!.pairDevice(gatt, connId, deviceId, mDeviceInfo!!.setupPinCode, networkCredentials)

3. if networkCredentials was wong setting will commission error

4. exit fragment and call deviceController.close()

5. than reset matter device

6. do commissiom again
    deviceController!!.pairDevice(gatt, connId, deviceId, mDeviceInfo!!.setupPinCode, networkCredentials)

7. ChipDeviceController will crash

crash log ======>
FATAL EXCEPTION: main
                                                                                                    Process: com.test, PID: 26374
                                                                                                    chip.devicecontroller.ChipDeviceControllerException: src/transport/raw/BLE.cpp:118: CHIP Error 0x0000000B: No memory
                                                                                                    	at chip.devicecontroller.ChipDeviceController.pairDevice(Native Method)
                                                                                                    	at chip.devicecontroller.ChipDeviceController.pairDevice(ChipDeviceController.java:160)
                                                                                                    	at chip.devicecontroller.ChipDeviceController.pairDevice(ChipDeviceController.java:129)
                                                                                                    	at com.google.chip.chiptool.SharedMatterViewModel$pairDeviceWithBle$1.invokeSuspend(SharedMatterViewModel.kt:193)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7397)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
2023-11-20 14:01:32.945 26374-26374 Process                 com.test                     I  Sending signal. PID: 26374 SIG: 9
2023-11-20 14:01:33.093  1093-2140  InputDispatcher         system_server                        E  channel 'c551c08 com.test/com.ui.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

### Bug prevalence

every time

### GitHub hash of the SDK that was being used

73c327e91a4252daac96728452e8cb713ea83697

### Platform

android

**Comment by netscell** [comment]
also encouter this exception：
11-21 19:59:34.212  1718  7189 W BluetoothGatt: Unhandled exception in callback
11-21 19:59:34.212  1718  7189 W BluetoothGatt: chip.devicecontroller.ChipDeviceControllerException: src/transport/raw/BLE.cpp:118: CHIP Error 0x0000000B: No memory
11-21 19:59:34.212  1718  7189 W BluetoothGatt: 	at chip.devicecontroller.ChipDeviceController.pairDevice(Native Method)

**Comment by maurycy-yolabs** [comment]
What was the resolution here? @freemanspace
