### ISSUE TITLE
[CERT-TEST-FAILURE]  [TC-RVCCLEANM-1.2,TC-RVCCLEANM-2.1 ] python script Failure

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#30622]
### Feature Area

Area:RobotVacuums

### Test Case

TC-RVCCLEANM-1.2, TC-RVCCLEANM-2.1

### Reproduction steps

Command to execute the RVCCLEANM-1.2- `python3 TC_RVCCLEANM_1_2.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --storage-path admin_storage.json --PICS ../app/tests/suites/certification/ci-pics-values --int-arg PIXIT_ENDPOINT:1`

Command to execute the RVCCLEANM-2.1 - `python3 TC_RVCCLEANM_2_1.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --storage-path admin_storage.json --PICS ../app/tests/suites/certification/ci-pics-values  --int-arg PIXIT_ENDPOINT:1 PIXIT.RVCCLEANM.MODE_CHANGE_OK:2 PIXIT.RVCCLEANM.MODE_CHANGE_FAIL:0`

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

64a6594e1c7d8b3a76a24c86d24758d0c88fc888

### Platform

python, raspi

### Anything else?

TC-RVCCLEANM-1-2.py and TC-RVCCLEANM-2-1.py are failed with the error `AttributeError: kUnknownEnumValue`

Below the traceback error i got in the Execution:

>  Traceback (most recent call last):
  File "/home/ubuntu/connectedhomeip/no/lib/python3.10/site-packages/mobly/base_test.py", line 783, in exec_one_test
    test_method()
  File "/home/ubuntu/connectedhomeip/src/python_testing/matter_testing_support.py", line 1066, in async_runner
    return asyncio.run(body(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/connectedhomeip/src/python_testing/TC_RVCCLEANM_1_2.py", line 84, in test_TC_RVCCLEANM_1_2
    cleanTags = [tag.value for tag in Clusters.RvcCleanMode.Enums.ModeTag
  File "/home/ubuntu/connectedhomeip/src/python_testing/TC_RVCCLEANM_1_2.py", line 85, in <listcomp>
    if tag is not Clusters.RvcCleanMode.Enums.ModeTag.kUnknownEnumValue]
  File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: kUnknownEnumValue

Reference log:
[tc-rvccleanm-1-2.txt](https://github.com/project-chip/connectedhomeip/files/13448700/tc-rvccleanm-1-2.txt)
[tc-rvccleanm-2-1.txt](https://github.com/project-chip/connectedhomeip/files/13448729/tc-rvccleanm-2-1.txt)

**Comment by Saravana-kr22** [comment]
TC-RVCOPSTATE-2.1 has the same issue.

[tc-rvcopstate-2-1.txt](https://github.com/project-chip/connectedhomeip/files/13449455/tc-rvcopstate-2-1.txt)

**Comment by Saravana-kr22** [comment]
TC-RVCRUNM-1.2 , TC-RVCRUNM-2.1 has the same issue.

[tc-rvcrunm-1-2.txt](https://github.com/project-chip/connectedhomeip/files/13449598/tc-rvcrunm-1-2.txt)
[tc-rvcrunm-2-1.txt](https://github.com/project-chip/connectedhomeip/files/13449599/tc-rvcrunm-2-1.txt)
