### ISSUE TITLE
EVSE cluster now won't allow events to be turned on in ZAP 

### ISSUE THREAD

**Issue by jamesharrow** [project-chip/connectedhomeip#31032]
### Reproduction steps

1. Run ./scripts/tools/zap/run_zaptool.sh examples/energy-management-app/energy-management-common/energy-management-app.zap
2. Goto EP1, and Energy EVSE cluster
3. Click on Events tab
4. Turn on an event

Nothing happens but an error message is sent on console:

```(node:157908) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'endpointTypeClusterId')

    at Object.insertOrUpdateEventState (/home/jebh/workspace/connectedhomeip/.environment/cipd/packages/zap/resources/app.asar/dist/src-electron/db/query-config.js:384:29)

    at /home/jebh/workspace/connectedhomeip/.environment/cipd/packages/zap/resources/app.asar/dist/src-electron/rest/user-data.js:298:9

(Use `zap --trace-warnings ...` to show where the warning was created)

(node:157908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```

I think this is because I was asked to remove side="server" from events in XML.
(ISSUE here: https://github.com/project-chip/connectedhomeip/issues/30665) @bzbarsky-apple 

```
-    <event code="0x0000" name="EVConnected" priority="info" side="server" apiMaturity="provisional">
+    <event code="0x0000" name="EVConnected" priority="info" apiMaturity="provisional">
```

### Bug prevalence

Every time

### GitHub hash of the SDK that was being used

N/A see PR #30857

### Platform

core

### Platform Version(s)

1.3

### Type

Spec Compliance Issue

**Comment by jamesharrow** [comment]
Reverted in PR #30701
