### ISSUE TITLE
[CERT-TEST-FAILURE] Ble-Thread Fails For Python

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#31385]
### Feature Area

Other

### Test Case

TC-RR-1.1

### Reproduction steps

Command to run this Python Testcases: `python3 TC_RR_1_1.py  --commissioning-method ble-thread --discriminator 3840 --passcode 20202021 --thread-dataset-hex 0e08000000000001000035060004001fffe00708fd99434432b35eab0c0402a0f7f8051000112233485566778899aabbccddeeff030f4f70656e54687265616444656d6f7404105fb16125077f91d910f8801ef67f283200030000100208111181112222222201021237 --ble-interface-id 0 -storage-path admin_storage.json --paa-trust-store-path ../../credentials/development/paa-root-certs/
`

### Bug prevalence

Whenver I Do this

### GitHub hash of the SDK that was being used

548e4f3de32053abe44854c35882bbc354f0538a

### Platform

nrf, python

### Anything else?

Ble-Thread pairing is fails in the python testcases for example the TC-RR-1.1 testcase has been run with the ble-thread pairing but it is failed in the commissioning with the error:

> Traceback (most recent call last):
  File "/home/ubuntu/connectedhomeip/no/lib/python3.10/site-packages/mobly/base_test.py", line 783, in exec_one_test
    test_method()
  File "/home/ubuntu/connectedhomeip/src/python_testing/matter_testing_support.py", line 1336, in test_run_commissioning
    if not self._commission_device(commission_idx):
  File "/home/ubuntu/connectedhomeip/src/python_testing/matter_testing_support.py", line 1369, in _commission_device
    return dev_ctrl.CommissionThread(
  File "/home/ubuntu/connectedhomeip/no/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 1785, in CommissionThread
    return self.ConnectBLE(discriminator, setupPinCode, nodeId)
  File "/home/ubuntu/connectedhomeip/no/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 441, in ConnectBLE
    ).raise_on_error()
  File "/home/ubuntu/connectedhomeip/no/lib/python3.10/site-packages/chip/native/__init__.py", line 67, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[MatterTest] 01-12 09:44:34.591 INFO [Test] test_run_commissioning ERROR
[MatterTest] 01-12 09:44:34.604 INFO Summary for test class CommissionDeviceTest: Error 1, Executed 1, Failed 0, Passed 0, Requested 1, Skipped 0

**Reference log:** 
[tc-rr-1-1.txt](https://github.com/project-chip/connectedhomeip/files/13917665/tc-rr-1-1.txt)

Note: Due to this issue it is also failing in TH as well.

**Comment by Saravana-kr22** [comment]
This issue has been resolved in lasest commit: f59323b0303e90dc4158acd44f115beabfcba89b
