### ISSUE TITLE
[Ask] Cannot edit zap file with zigbee tool

### ISSUE THREAD

**Issue by nmtoan91** [project-chip/connectedhomeip#31411]
### Documentation issues

Hi, I'm trying to edit the zap file of the all-cluster-app but I got stuck with several questions.
1. The program builds an error even if I simply open the zip file and save it with a new name. I also noticed that the file size changes from 665KB to 163KB.
2. What should I do with the all-clusters-app.matter file, is there any tool to visualize this file?
Here is the error log:
```
Traceback (most recent call last):
  File "/home/nuc6/Work/connectedhomeip_controller/./scripts/build/build_examples.py", line 230, in <module>
    main(auto_envvar_prefix='CHIP')
  File "/home/nuc6/Work/connectedhomeip_controller/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/nuc6/Work/connectedhomeip_controller/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/nuc6/Work/connectedhomeip_controller/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/nuc6/Work/connectedhomeip_controller/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nuc6/Work/connectedhomeip_controller/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/nuc6/Work/connectedhomeip_controller/.environment/pigweed-venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/nuc6/Work/connectedhomeip_controller/./scripts/build/build_examples.py", line 220, in cmd_build
    context.obj.Build()
  File "/home/nuc6/Work/connectedhomeip_controller/scripts/build/build/__init__.py", line 67, in Build
    self.Generate()
  File "/home/nuc6/Work/connectedhomeip_controller/scripts/build/build/__init__.py", line 62, in Generate
    builder.generate()
  File "/home/nuc6/Work/connectedhomeip_controller/scripts/build/builders/host.py", line 478, in generate
    super(HostBuilder, self).generate()
  File "/home/nuc6/Work/connectedhomeip_controller/scripts/build/builders/gn.py", line 89, in generate
    self._Execute(cmd, title=title)
  File "/home/nuc6/Work/connectedhomeip_controller/scripts/build/builders/builder.py", line 104, in _Execute
    self._runner.Run(cmdarray, title=title)
  File "/home/nuc6/Work/connectedhomeip_controller/scripts/build/runner/shell.py", line 73, in Run
    raise Exception('Command %r failed: %d' % (cmd, code))
Exception: Command ['gn', 'gen', '--check', '--fail-on-unused-args', '--export-compile-commands', '--root=/home/nuc6/Work/connectedhomeip_controller/examples/all-clusters-app/linux', '--args=chip_config_network_layer_ble=false is_asan=true is_clang=true', '/home/nuc6/Work/connectedhomeip_controller/out/linux-x64-all-clusters-no-ble-asan-clang'] failed: 1
```

**Comment by nmtoan91** [comment]
By the way, I'm just a newbie, I need a full tutorial to customize the zap file with GUI-zap and apply it back to a sample project. Thanks,
