### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-RVCRUNM-1.2,TC-RVCRUNM-2.1 ] python script Failure

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#32034]
### Feature Area

Area:RobotVacuums

### Test Case

- [ ] TC-RVCRUNM-1.2
- [ ] TC-RVCRUNM-2.1

### Reproduction steps

Command to execute the RVCRUNM-1.2:
`python3 TC_RVCRUNM_1_2.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --storage-path admin_storage.json --PICS all-clusters-app_pics --int-arg PIXIT_ENDPOINT:1 --paa-trust-store-path ../../credentials/development/paa-root-certs/`

Command to execute the RVCRUNM-2.1:

`python3 TC_RVCRUNM_2_1.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --storage-path admin_storage.json --PICS all-clusters-app_pics --int-arg PIXIT_ENDPOINT:1 PIXIT.RVCRUNM.MODE_CHANGE_OK:2 PIXIT.RVCRUNM.MODE_CHANGE_FAIL:0  --paa-trust-store-path ../../credentials/development/paa-root-certs/`

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

3ec1ba5b2989b18e153053e3060d374ef6b2c60d

### Platform

raspi

### Anything else?

TC-RVCRUNM-1.2.py and TC-RVCRUNM-2.1.py  test cases are failed in Step 2` Read SupportedModes attribute`. Hence SupportedModes needs to be implemented in the python.

> [MatterTest] 02-09 09:09:45.171 INFO 		***** Test Step 1 : Run entire test
> [MatterTest] 02-09 09:09:45.174 INFO ***** Test Step 1 : Commissioning, already done
> [MatterTest] 02-09 09:09:45.175 INFO ***** Test Step 2 : Read SupportedModes attribute
> [MatterTest] 02-09 09:09:45.178 INFO Found an existing secure session to [1:0000000012344321]!
> [MatterTest] 02-09 09:09:45.183 INFO <<< [E:3268i S:63528 M:208828092] (S) Msg TX to 1:0000000012344321 [43A5] [UDP:[fe80::e65f:1ff:fe43:4214%eth0]:5540] --- Type 0001:02 (IM:ReadRequest)
> [MatterTest] 02-09 09:09:45.188 INFO >>> [E:3268i S:63528 M:116300470 (Ack:208828092)] (S) Msg RX from 1:0000000012344321 [43A5] --- Type 0001:05 (IM:ReportData)
> [MatterTest] 02-09 09:09:45.202 INFO <<< [E:3268i S:63528 M:208828093 (Ack:116300470)] (S) Msg TX to 1:0000000012344321 [43A5] [UDP:[fe80::e65f:1ff:fe43:4214%eth0]:5540] --- Type 0000:10 (SecureChannel:StandaloneAck)
> [MatterTest] 02-09 09:09:45.205 ERROR Exception occurred in test_TC_RVCRUNM_2_1.
> Traceback (most recent call last):
>   File "/home/ubuntu/master_cntrl/connectedhomeip/no/lib/python3.10/site-packages/mobly/base_test.py", line 783, in exec_one_test
>     test_method()
>   File "/home/ubuntu/master_cntrl/connectedhomeip/src/python_testing/matter_testing_support.py", line 1494, in async_runner
>     return asyncio.run(runner_with_timeout)
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
>     return fut.result()
>   File "/home/ubuntu/master_cntrl/connectedhomeip/src/python_testing/TC_RVCRUNM_2_1.py", line 74, in test_TC_RVCRUNM_2_1
>     supported_modes = await self.read_mod_attribute_expect_success(endpoint=self.endpoint, attribute=attributes.SupportedModes)
>   File "/home/ubuntu/master_cntrl/connectedhomeip/src/python_testing/TC_RVCRUNM_2_1.py", line 39, in read_mod_attribute_expect_success
>     return await self.read_single_attribute_check_success(endpoint=endpoint, cluster=cluster, attribute=attribute)
>   File "/home/ubuntu/master_cntrl/connectedhomeip/src/python_testing/matter_testing_support.py", line 833, in read_single_attribute_check_success
>     asserts.assert_true(read_ok, read_err_msg)
>   File "/home/ubuntu/master_cntrl/connectedhomeip/no/lib/python3.10/site-packages/mobly/asserts.py", line 353, in assert_true
>     fail(msg, extras)
>   File "/home/ubuntu/master_cntrl/connectedhomeip/no/lib/python3.10/site-packages/mobly/asserts.py", line 475, in fail
>     raise signals.TestFailure(msg, extras)
> mobly.signals.TestFailure: Details=Error reading <class 'chip.clusters.Objects.RvcRunMode'>:<class 'chip.clusters.Objects.RvcRunMode.Attributes.SupportedModes'> = ValueDecodeFailure(TLVValue=None, Reason=InteractionModelError(<Status.UnsupportedCluster: 195>)), Extras=None
> [MatterTest] 02-09 09:09:45.223 INFO 		***** Test Failure : 

**Reference log:**
[TC-RVCRUNM-1.2.txt](https://github.com/project-chip/connectedhomeip/files/14219981/TC-RVCRUNM-1.2.txt)
[TC-RVCRUNM-2.1.txt](https://github.com/project-chip/connectedhomeip/files/14219982/TC-RVCRUNM-2.1.txt)

**Comment by Ashwinigrl** [comment]
TC-RVCCLEANM-1.2 , TC-RVCCLEANM-2.1 has the same issue.
**Reference Log:**
[TC-RVCCLEANM-1.2.txt](https://github.com/project-chip/connectedhomeip/files/14220002/TC-RVCCLEANM-1.2.txt)
[TC-RVCCLEANM-2.1.txt](https://github.com/project-chip/connectedhomeip/files/14220003/TC-RVCCLEANM-2.1.txt)

**Comment by Ashwinigrl** [comment]
TC-RVCCLEANM-2.2 , TC-RVCRUNM-2.1 has the same issue.
