### ISSUE TITLE
Issue bash scripts/bootstrap.sh pigweed command not found/permission denied

### ISSUE THREAD

**Issue by planeckatamb** [project-chip/connectedhomeip#32624]
### Build issue(s)

I've got issues bootstrapping and building anything. 
Using VS Studio code, docker, Ubuntu 18.04 LTS and Python 3.9.5 
Tried everything I could find in already opened and closed issues 
Also restarted the whole project with clean installations of Studio Code and Docker. 
Cloned the actual build and successfully created the development container. So no more ideas left. 

When bootstrapping I get the following issue: 

### Platform

vscode

### Anything else?

` *  Executing task: bash scripts/bootstrap.sh 

Synchronizing submodule url for 'examples/common/QRCode/repo'
Synchronizing submodule url for 'examples/common/m5stack-tft/repo'
Synchronizing submodule url for 'third_party/asr/asr550x/asr_sdk'
Synchronizing submodule url for 'third_party/asr/asr582x/asr_sdk'
Synchronizing submodule url for 'third_party/asr/asr595x/asr_sdk'
Synchronizing submodule url for 'third_party/asr/components'
Synchronizing submodule url for 'third_party/boringssl/repo/src'
Synchronizing submodule url for 'third_party/bouffalolab/repo'
Synchronizing submodule url for 'third_party/bouffalolab/repo/components'
Synchronizing submodule url for 'third_party/bouffalolab/repo/customer_app'
Synchronizing submodule url for 'third_party/bouffalolab/repo/docs'
Synchronizing submodule url for 'third_party/bouffalolab/repo/tools'
Synchronizing submodule url for 'third_party/cirque/repo'
Synchronizing submodule url for 'third_party/editline/repo'
Synchronizing submodule url for 'third_party/freertos/repo'
Synchronizing submodule url for 'third_party/imgui/repo'
Synchronizing submodule url for 'third_party/infineon/cyw30739_sdk/repos/30739A0'
Synchronizing submodule url for 'third_party/infineon/cyw30739_sdk/repos/CYW930739M2EVB-01'
Synchronizing submodule url for 'third_party/infineon/cyw30739_sdk/repos/btsdk-include'
Synchronizing submodule url for 'third_party/infineon/cyw30739_sdk/repos/btsdk-tools'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/TARGET_CY8CKIT-062S2-43012'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/abstraction-rtos'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/anycloud-ota'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/bluetooth-freertos'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/btstack'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/clib-support'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/connectivity-utilities'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/core-lib'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/core-make'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/freertos'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/kv-store'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/lwip'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/lwip-network-interface-integration'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/mbedtls'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/mtb-hal-cat1'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/mtb-pdl-cat1'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/psoc6cm0p'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/recipe-make-cat1a'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/retarget-io'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/secure-sockets'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/serial-flash'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/whd-bsp-integration'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/wifi-connection-manager'
Synchronizing submodule url for 'third_party/infineon/psoc6/psoc6_sdk/libs/wifi-host-driver'
Synchronizing submodule url for 'third_party/jsoncpp/repo'
Synchronizing submodule url for 'third_party/libwebsockets/repo'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/cypress/libs/core-lib'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/cypress/libs/cy-mbedtls-acceleration'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/cypress/libs/mtb-pdl-cat1'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/cypress/libs/pdl/psoc6pdl'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/cypress/libs/psoc6hal'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/cypress/libs/retarget-io'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/asio/asio'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/bootloader/subproject/components/micro-ecc/micro-ecc'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/bt/controller/lib_esp32'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/bt/controller/lib_esp32c3_family'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/bt/host/nimble/nimble'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/cbor/tinycbor'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/cmock/CMock'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/cmock/CMock/vendor/c_exception'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/cmock/CMock/vendor/unity'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/coap/libcoap'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/coap/libcoap/ext/tinydtls'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/esp_phy/lib'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/esp_wifi/lib'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/esptool_py/esptool'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/expat/expat'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/ieee802154/lib'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/json/cJSON'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/libsodium/libsodium'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/lwip/lwip'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/mbedtls/mbedtls'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/mqtt/esp-mqtt'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/nghttp/nghttp2'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/nghttp/nghttp2/third-party/mruby'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/nghttp/nghttp2/third-party/neverbleed'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/openthread/lib'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/openthread/openthread'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/protobuf-c/protobuf-c'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/spiffs/spiffs'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/tinyusb/tinyusb'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/components/unity/unity'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/examples/build_system/cmake/import_lib/main/lib/tinyxml2'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/ext/cddl-gen'
Synchronizing submodule url for 'third_party/mbed-mcu-boot/repo/ext/mbedtls'
Synchronizing submodule url for 'third_party/mbed-os-cypress-capsense-button/repo'
Synchronizing submodule url for 'third_party/mbed-os-posix-socket/repo'
Synchronizing submodule url for 'third_party/mbed-os/repo'
Synchronizing submodule url for 'third_party/mbedtls/repo'
Synchronizing submodule url for 'third_party/mt793x_sdk/filogic'
Synchronizing submodule url for 'third_party/mt793x_sdk/lwip'
Synchronizing submodule url for 'third_party/mt793x_sdk/mDNSResponder'
Synchronizing submodule url for 'third_party/nanopb/repo'
Synchronizing submodule url for 'third_party/nlassert/repo'
Synchronizing submodule url for 'third_party/nlio/repo'
Synchronizing submodule url for 'third_party/nlunit-test/repo'
Synchronizing submodule url for 'third_party/nxp/mw320_sdk/repo'
Synchronizing submodule url for 'third_party/open-iot-sdk/sdk'
Synchronizing submodule url for 'third_party/open-iot-sdk/sdk/developer-tools'
Synchronizing submodule url for 'third_party/openthread/ot-efr32'
Synchronizing submodule url for 'third_party/openthread/ot-efr32/openthread'
Synchronizing submodule url for 'third_party/openthread/ot-efr32/third_party/silabs/gecko_sdk'
Synchronizing submodule url for 'third_party/openthread/ot-ifx'
Synchronizing submodule url for 'third_party/openthread/ot-ifx/openthread'
Synchronizing submodule url for 'third_party/openthread/ot-ifx/third_party/infineon/btsdk-include'
Synchronizing submodule url for 'third_party/openthread/ot-ifx/third_party/infineon/btsdk-tools'
Synchronizing submodule url for 'third_party/openthread/ot-ifx/third_party/infineon/platform/cyw30739/30739a0'
Synchronizing submodule url for 'third_party/openthread/ot-ifx/third_party/infineon/platform/cyw30739/bsp/cyw930739m2evb-01/TARGET_CYW930739M2EVB-01'
Synchronizing submodule url for 'third_party/openthread/ot-nxp'
Synchronizing submodule url for 'third_party/openthread/ot-nxp/openthread'
Synchronizing submodule url for 'third_party/openthread/ot-nxp/openthread-br'
Synchronizing submodule url for 'third_party/openthread/ot-qorvo'
Synchronizing submodule url for 'third_party/openthread/ot-qorvo/openthread'
Synchronizing submodule url for 'third_party/openthread/ot-qorvo/third_party/Qorvo/repo'
Synchronizing submodule url for 'third_party/openthread/ot-ti'
Synchronizing submodule url for 'third_party/openthread/ot-ti/openthread'
Synchronizing submodule url for 'third_party/openthread/ot-ti/third_party/freertos/repo'
Synchronizing submodule url for 'third_party/openthread/ot-ti/third_party/mbedtls/repo'
Synchronizing submodule url for 'third_party/openthread/ot-ti/third_party/ti_simplelink_sdk/repo_cc13xx_cc26xx'
Synchronizing submodule url for 'third_party/openthread/repo'
Synchronizing submodule url for 'third_party/ot-br-posix/repo'
Synchronizing submodule url for 'third_party/ot-br-posix/repo/third_party/cJSON/repo'
Synchronizing submodule url for 'third_party/ot-br-posix/repo/third_party/http-parser/repo'
Synchronizing submodule url for 'third_party/ot-br-posix/repo/third_party/openthread/repo'
Synchronizing submodule url for 'third_party/perfetto/repo'
Synchronizing submodule url for 'third_party/pigweed/repo'
Synchronizing submodule url for 'third_party/pybind11/repo'
Synchronizing submodule url for 'third_party/qpg_sdk/repo'
Synchronizing submodule url for 'third_party/silabs/gecko_sdk'
Synchronizing submodule url for 'third_party/silabs/matter_support'
Synchronizing submodule url for 'third_party/silabs/wifi_sdk'
Synchronizing submodule url for 'third_party/silabs/wiseconnect-wifi-bt-sdk'
Synchronizing submodule url for 'third_party/simw-top-mini/repo'
Synchronizing submodule url for 'third_party/st/STM32CubeWB'
Synchronizing submodule url for 'third_party/ti_simplelink_sdk/repo_cc13xx_cc26xx'
Synchronizing submodule url for 'third_party/ti_simplelink_sdk/repo_cc32xx'
/workspaces/connectedhomeip/third_party/pigweed/repo/pw_env_setup/util.sh: line 14: $'\r': command not found
': not a valid identifierip/third_party/pigweed/repo/pw_env_setup/util.sh: line 16: export: `PATH
/workspaces/connectedhomeip/third_party/pigweed/repo/pw_env_setup/util.sh: line 17: $'\r': command not found
/workspaces/connectedhomeip/third_party/pigweed/repo/pw_env_setup/util.sh: line 26: syntax error near unexpected token `$'{\r''
'workspaces/connectedhomeip/third_party/pigweed/repo/pw_env_setup/util.sh: line 26: `pw_none() {
scripts/bootstrap.sh: line 113: pw_get_env_root: command not found
mkdir: cannot create directory ‘’: No such file or directory
Traceback (most recent call last):
  File "/workspaces/connectedhomeip/scripts/setup/gen_pigweed_cipd_json.py", line 61, in <module>
    main()
  File "/workspaces/connectedhomeip/scripts/setup/gen_pigweed_cipd_json.py", line 57, in main
    generate_new_cipd_package_json(**vars(parser.parse_args()))
  File "/workspaces/connectedhomeip/scripts/setup/gen_pigweed_cipd_json.py", line 42, in generate_new_cipd_package_json
    with open(output, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/pigweed.json'
scripts/bootstrap.sh: line 135: pw_bootstrap: command not found
scripts/bootstrap.sh: line 140: pw_finalize: command not found
Installing pip requirements for all...

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.9 -m pip install --upgrade pip
scripts/bootstrap.sh: line 171: pw_cleanup: command not found
 *  Terminal will be reused by tasks, press any key to close it. `

**Comment by planeckatamb** [comment]
Could solve it with 
https://github.com/espressif/esp-matter/issues/527#issuecomment-1662022440
