### ISSUE TITLE
[1.3] Unable to execute bootstrap.sh on Darwin

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#33691]
### Reproduction steps

SHA: b790232baf1a257a396e9f7b598584896fc38365

Steps:

1. git clone --recurse-submodules https://github.com/project-chip/connectedhomeip.git
2. cd ~/connectedhomeip
3. git pull
4. git reset --hard b790232baf1a257a396e9f7b598584896fc38365
5. git clean -Xdf
6. git submodule update --init
7. source scripts/bootstrap.sh

### Bug prevalence

all the time

### GitHub hash of the SDK that was being used

b790232baf1a257a396e9f7b598584896fc38365

### Platform

darwin

### Type

Platform Issue

### Anything else?

I am getting the following error;

source scripts/bootstrap.sh

  WELCOME TO...

         █
         █
     ▄   █   ▄                                █     █
     ▀▀█████▀▀      ▄▀▀▀▄ ▄▀▀▀▄    ▄▀▀▀▀▄█  ▀▀█▀▀▀▀▀█▀▀   ▄▀▀▀▀▄    ▄▀▀
   ▀█▄       ▄█▀   █     █     █  █      █    █     █    █▄▄▄▄▄▄█  █   
     ▀█▄   ▄█▀     █     █     █  █      █    █     █    █         █   
  ▄██▀▀█   █▀▀██▄  █     █     █   ▀▄▄▄▄▀█    ▀▄▄   ▀▄▄   ▀▄▄▄▄▀   █   
 ▀▀    █   █    ▀▀

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...done (4.0s)
  Setting up Project actions........skipped (0.1s)
  Setting up Python environment.....Traceback (most recent call last):
  File "/Users/priyankahonnakasturi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 995, in <module>
    sys.exit(main())
  File "/Users/priyankahonnakasturi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 987, in main
    return EnvSetup(**vars(parse())).setup()
  File "/Users/priyankahonnakasturi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 577, in setup
    result = step(spin)
  File "/Users/priyankahonnakasturi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 766, in virtualenv
    if not virtualenv_setup.install(
  File "/Users/priyankahonnakasturi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 212, in install
    version = _python_version(python)
  File "/Users/priyankahonnakasturi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 185, in _python_version
    subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/Applications/Xcode5.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Applications/Xcode5.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Applications/Xcode5.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Xcode5.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
**FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/python3'**
Installing pip requirements for all...
_install_additional_pip_requirements:29: /usr/local/bin/pip: bad interpreter: /AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/PythonLegacy: no such file or directory

**Comment by bzbarsky-apple** [comment]
Per offline discussion: `/usr/local/bin/python3` in this case is a symlink to a non-existent file.
