### ISSUE TITLE
[BUG] Failed to Read attribute with src/protocols/secure_channel/CASESession.cpp:2102: CHIP Error 0x000000DB: The Resource is busy and cannot process the request

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#33830]
### Reproduction steps

I have used python controller to done a stress test on my RPI sample dut (all-clusters-app) on Read-Write operation for 100000 iteration. The iteration 15819 is passed without any error but the 15820 is Failed to read the node-label attribute with the below traceback error and the next iteration 15821 is also passed without any issues.

> Traceback (most recent call last):
  File "/Users/chaitanyajandhyala/code/python/matter-qa/src/matter_qa/scripts/reliability_scripts/TC_Read_Write.py", line 72, in verify_read_write
    nodelabel_read_value = await self.read_single_attribute_check_success(cluster=self.clusters,
  File "/Users/chaitanyajandhyala/code/python/matter-qa/src/matter_qa/library/helper_libs/matter_testing_support.py", line 876, in read_single_attribute_check_success
    result = await dev_ctrl.ReadAttribute(node_id, [(endpoint, attribute)], fabricFiltered=fabric_filtered)
  File "/Users/chaitanyajandhyala/code/python/matter-qa/.venv/lib/python3.9/site-packages/chip/ChipDeviceCtrl.py", line 1421, in ReadAttribute
    res = await self.Read(nodeid,
  File "/Users/chaitanyajandhyala/code/python/matter-qa/.venv/lib/python3.9/site-packages/chip/ChipDeviceCtrl.py", line 1344, in Read
    device = await self.GetConnectedDevice(nodeid)
  File "/Users/chaitanyajandhyala/code/python/matter-qa/.venv/lib/python3.9/site-packages/chip/ChipDeviceCtrl.py", line 902, in GetConnectedDevice
    await future
chip.exceptions.ChipStackError: src/protocols/secure_channel/CASESession.cpp:2102: CHIP Error 0x000000DB: The Resource is busy and cannot process the request

### Bug prevalence

Whenever i do this

### GitHub hash of the SDK that was being used

3718e996b56f36a553c1b4571f77728396590776

### Platform

python, raspi

### Platform Version(s)

RPI-4, 8GB RAM

### Anything else?

Example of Failed iteartion details:

The iteartion number 15819 is passed below file for the same
TH log: [log_2024-05-30_04-24-38.log](https://github.com/user-attachments/files/15775619/log_2024-05-30_04-24-38.log)

The iteration number 15820 is failed with this error below the logfile
TH log : [log_2024-05-30_04-25-12.log](https://github.com/user-attachments/files/15775617/log_2024-05-30_04-25-12.log)

The iteartion number 15821 is passed below file for the same
TH log: [log_2024-05-30_04-25-56.log](https://github.com/user-attachments/files/15775622/log_2024-05-30_04-25-56.log)

For the detailed summary please reference this json: 
[summary.json](https://github.com/user-attachments/files/15775309/summary.json)

Script reference: https://github.com/CHIP-Specifications/matter-qa/blob/main/src/matter_qa/scripts/reliability_scripts/TC_Read_Write.py

**Comment by suhailab** [comment]
After testing your sdk branch testing/33830-42947-72252, I still face the resource busy error, 
attaching the logs for reference.

[logs_for_issue_33830.zip](https://github.com/user-attachments/files/29842517/logs_for_issue_33830.zip)
