### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-SEAR-1.2] -Python test Failure

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#34903]
### Feature Area

Other

### Test Case

TC-SEAR-1.2

### Reproduction steps

1. Command used to launch the DUT : `./chip-rvc-app`
2. Command used to run the python script : `python3 TC_SEAR_1_2.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --PICS ServiceArea.txt --app-pid 30984 --storage-path admin_storage.json --endpoint 1 --paa-trust-store-path ../../credentials/development/paa-root-certs/`

While executing the TC-SEAR-1.2 Python script, the test is failing at Test Step 3 : Read SupportedAreas attribute with error  `AttributeError: 'AreaStruct' object has no attribute 'locationInfo'.`

> [MatterTest] 08-09 07:38:56.603 ERROR Exception occurred in test_TC_SEAR_1_2.
> Traceback (most recent call last):
>   File "/home/ubuntu/cntr/connectedhomeip/no/lib/python3.10/site-packages/mobly/base_test.py", line 783, in exec_one_test
>     test_method()
>   File "/home/ubuntu/cntr/connectedhomeip/src/python_testing/matter_testing_support.py", line 1744, in async_runner
>     return _async_runner(body, self, *args, **kwargs)
>   File "/home/ubuntu/cntr/connectedhomeip/src/python_testing/matter_testing_support.py", line 1732, in _async_runner
>     return asyncio.run(runner_with_timeout)
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
>     return fut.result()
>   File "/home/ubuntu/cntr/connectedhomeip/src/python_testing/TC_SEAR_1_2.py", line 223, in test_TC_SEAR_1_2
>     await self.read_and_validate_supported_areas(step=3)
>   File "/home/ubuntu/cntr/connectedhomeip/src/python_testing/TC_SEAR_1_2.py", line 106, in read_and_validate_supported_areas
>     if a.locationInfo is NullValue and a.landmarkTag is NullValue:
> AttributeError: 'AreaStruct' object has no attribute 'locationInfo'
> [MatterTest] 08-09 07:38:56.610 INFO 		***** Test Failure : 

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

78d4020a890e78ac58dad5b1bf846714fb5f334c

### Platform

raspi

### Anything else?

**Python Script References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_SEAR_1_2.py

**Reference Log:**
[TC-SEAR-1.2.txt](https://github.com/user-attachments/files/16559805/TC-SEAR-1.2.txt)

**Comment by Ashwinigrl** [comment]
Issue Fixed in Commit a296b6609ec064b201cca9880c577f0197217d43 . Hence closing it.
