### ISSUE TITLE
[Build] able to build the chiptool but getting failed at last step

### ISSUE THREAD

**Issue by Kartikgupta1502** [project-chip/connectedhomeip#35036]
### Build issue(s)

2024-08-16 16:20:27 INFO    [1660/1660] stamp obj/default.stamp
2024-08-16 16:20:27 INFO    Command ['ninja', '-C', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool'] completed
2024-08-16 16:20:27 INFO    Prepare Native libs android-arm64-chip-tool
2024-08-16 16:20:27 INFO    Command ['mkdir', '-p', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/jniLibs/arm64-v8a'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/jni/arm64-v8a/libCHIPController.so', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/jniLibs/arm64-v8a/libCHIPController.so'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/jni/arm64-v8a/libc++_shared.so', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/jniLibs/arm64-v8a/libc++_shared.so'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/src/controller/java/CHIPController.jar', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/CHIPController.jar'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/src/controller/java/CHIPInteractionModel.jar', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/CHIPInteractionModel.jar'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/src/controller/java/OnboardingPayload.jar', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/OnboardingPayload.jar'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/src/platform/android/AndroidPlatform.jar', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/AndroidPlatform.jar'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/src/controller/java/libMatterJson.jar', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/libMatterJson.jar'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/src/controller/java/libMatterTlv.jar', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/libMatterTlv.jar'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/src/controller/java/CHIPClusters.jar', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/CHIPClusters.jar'] completed
2024-08-16 16:20:28 INFO    Command ['cp', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool/lib/src/controller/java/CHIPClusterID.jar', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/app/libs/CHIPClusterID.jar'] completed
2024-08-16 16:20:28 INFO    Building APP android-arm64-chip-tool
2024-08-16 16:20:28 INFO    > Task :app:preBuild UP-TO-DATE
2024-08-16 16:20:28 INFO    > Task :app:preDebugBuild UP-TO-DATE
2024-08-16 16:20:28 INFO    > Task :app:compileDebugAidl NO-SOURCE
2024-08-16 16:20:28 INFO    > Task :app:compileDebugRenderscript NO-SOURCE
2024-08-16 16:20:29 INFO    > Task :app:dataBindingMergeDependencyArtifactsDebug
2024-08-16 16:20:29 INFO    > Task :app:dataBindingMergeGenClassesDebug
2024-08-16 16:20:29 INFO    > Task :app:generateDebugResValues
2024-08-16 16:20:29 INFO    > Task :app:generateDebugResources
2024-08-16 16:20:29 INFO    > Task :app:generateDebugBuildConfig
2024-08-16 16:20:29 INFO    > Task :app:createDebugCompatibleScreenManifests
2024-08-16 16:20:29 INFO    > Task :app:extractDeepLinksDebug
2024-08-16 16:20:29 INFO    > Task :app:checkDebugAarMetadata
2024-08-16 16:20:29 INFO    > Task :app:processDebugMainManifest FAILED
2024-08-16 16:20:29 INFO    > Task :app:mergeDebugResources
2024-08-16 16:20:29 WARNING 
2024-08-16 16:20:29 WARNING FAILURE: Build failed with an exception.
2024-08-16 16:20:29 WARNING 
2024-08-16 16:20:29 WARNING * What went wrong:
2024-08-16 16:20:29 WARNING Execution failed for task ':app:processDebugMainManifest'.
2024-08-16 16:20:29 WARNING > Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @5d5e7338
2024-08-16 16:20:29 WARNING 
2024-08-16 16:20:29 WARNING * Try:
2024-08-16 16:20:29 WARNING Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2024-08-16 16:20:29 WARNING 
2024-08-16 16:20:29 WARNING * Get more help at https://help.gradle.org
2024-08-16 16:20:29 WARNING 
2024-08-16 16:20:29 WARNING BUILD FAILED in 1s
2024-08-16 16:20:29 INFO    9 actionable tasks: 9 executed
Traceback (most recent call last):
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/./scripts/build/build_examples.py", line 234, in <module>
    main(auto_envvar_prefix='CHIP')
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/./scripts/build/build_examples.py", line 224, in cmd_build
    context.obj.Build()
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/scripts/build/build/__init__.py", line 71, in Build
    builder.build()
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/scripts/build/builders/builder.py", line 107, in build
    self._build()
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/scripts/build/builders/android.py", line 477, in _build
    self.gradlewBuildSrcAndroid()
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/scripts/build/builders/android.py", line 291, in gradlewBuildSrcAndroid
    self._Execute(
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/scripts/build/builders/builder.py", line 112, in _Execute
    self._runner.Run(cmdarray, title=title)
  File "/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/scripts/build/runner/shell.py", line 73, in Run
    raise Exception('Command %r failed: %d' % (cmd, code))
Exception: Command ['/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool/gradlew', '-p', '/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/examples/android/CHIPTool', '-PmatterBuildSrcDir=/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool', '-PmatterSdkSourceBuild=false', '-PbuildDir=/Users/kartikgupta.int/Desktop/duplicateRepos/connectedhomeip/out/android-arm64-chip-tool', 'assembleDebug'] failed: 1

**Comment by huytungst** [comment]
Try this to fix Android app build errors:

1. Backup your works

2. Delete the entire `connectedhomeip` repo: `rm -rf connectedhomeip`

3. Reclone the repo with all submodules via SSH:
:white_check_mark: Do: `git clone --recurse-submodules git@github.com:project-chip/connectedhomeip.git`
:x: Don't: `git clone https://github.com/project-chip/connectedhomeip.git`

4. Follow the steps in the [Android Building Guide](https://project-chip.github.io/connectedhomeip-doc/platforms/android/android_building.html)
(Use OS's terminal. Don't use Android Studio's terminal)

5. To run or develop CHIPTool app, open `CHIPTool` folder in Android Studio
