### ISSUE TITLE
Build Failed android    FAILED: gen/src/controller/java/java.classlist

### ISSUE THREAD

**Issue by kiss2sky** [project-chip/connectedhomeip#36870]
2024-12-13 14:55:20 INFO    FAILED: gen/src/controller/java/java.classlist 
2024-12-13 14:55:20 INFO    python3 ../../build/chip/java/javac_runner.py --classdir obj/src/controller/java/java/classes --outfile gen/src/controller/java/java.classlist --build-config gen/src/controller/java/java.json -- -d obj/src/controller/java/java/classes @gen/src/controller/java/java.sources -Werror -Xlint:all -Xlint:deprecation -parameters -Xlint:-options -source 8 -target 8
2024-12-13 14:55:20 INFO    ../../src/controller/java/src/chip/devicecontroller/OTAProviderDelegate.java:33: error: unmappable character (0xE2) for encoding US-ASCII
2024-12-13 14:55:20 INFO       * @param vendorId Vendor ID applying to the OTA Requestor???s Node.
2024-12-13 14:55:20 INFO                                                                ^
2024-12-13 14:55:20 INFO    ../../src/controller/java/src/chip/devicecontroller/OTAProviderDelegate.java:33: error: unmappable character (0x80) for encoding US-ASCII
2024-12-13 14:55:20 INFO       * @param vendorId Vendor ID applying to the OTA Requestor???s Node.
2024-12-13 14:55:20 INFO                                                                 ^
2024-12-13 14:55:20 INFO    ../../src/controller/java/src/chip/devicecontroller/OTAProviderDelegate.java:33: error: unmappable character (0x99) for encoding US-ASCII
2024-12-13 14:55:20 INFO       * @param vendorId Vendor ID applying to the OTA Requestor???s Node.
2024-12-13 14:55:20 INFO                                                                  ^
2024-12-13 14:55:20 INFO    ../../src/controller/java/src/chip/devicecontroller/OTAProviderDelegate.java:34: error: unmappable character (0xE2) for encoding US-ASCII
2024-12-13 14:55:20 INFO       * @param productId Product ID applying to the OTA Requestor???s Node.
2024-12-13 14:55:20 INFO                                                                  ^
2024-12-13 14:55:20 INFO    ../../src/controller/java/src/chip/devicecontroller/OTAProviderDelegate.java:34: error: unmappable character (0x80) for encoding US-ASCII
2024-12-13 14:55:20 INFO       * @param productId Product ID applying to the OTA Requestor???s Node.
2024-12-13 14:55:20 INFO                                                                   ^
2024-12-13 14:55:20 INFO    ../../src/controller/java/src/chip/devicecontroller/OTAProviderDelegate.java:34: error: unmappable character (0x99) for encoding US-ASCII
2024-12-13 14:55:20 INFO       * @param productId Product ID applying to the OTA Requestor???s Node.
2024-12-13 14:55:20 INFO                                                                    ^
2024-12-13 14:55:20 INFO    ../../src/controller/java/src/chip/devicecontroller/OTAProviderDelegate.java:36: error: unmappable character (0xE2) for encoding US-ASCII
2024-12-13 14:55:20 INFO       * @param hardwareVersion OTA Requestor???s hardware version. Can be set null.
2024-12-13 14:55:20 INFO                                             ^
2024-12-13 14:55:20 INFO    ../../src/controller/java/src/chip/devicecontroller/OTAProviderDelegate.java:36: error: unmappable character (0x80) for encoding US-ASCII
2024-12-13 14:55:20 INFO       * @param hardwareVersion OTA Requestor???s hardware version. Can be set null.
2024-12-13 14:55:20 INFO                                              ^
2024-12-13 14:55:20 INFO    ../../src/controller/java/src/chip/devicecontroller/OTAProviderDelegate.java:36: error: unmappable character (0x99) for encoding US-ASCII
2024-12-13 14:55:20 INFO       * @param hardwareVersion OTA Requestor???s hardware version. Can be set null.
2024-12-13 14:55:20 INFO                                               ^
2024-12-13 14:55:20 INFO    9 errors
2024-12-13 14:55:20 INFO    Traceback (most recent call last):
2024-12-13 14:55:20 INFO      File "/media/it/2325A95CCDF15784/Android/connectedhomeip/out/android-arm64-chip-tool/../../build/chip/java/javac_runner.py", line 146, in <module>
2024-12-13 14:55:20 INFO        sys.exit(main())
2024-12-13 14:55:20 INFO      File "/media/it/2325A95CCDF15784/Android/connectedhomeip/out/android-arm64-chip-tool/../../build/chip/java/javac_runner.py", line 130, in main
2024-12-13 14:55:20 INFO        retcode = subprocess.check_call(java_args + args.rest)
2024-12-13 14:55:20 INFO      File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
2024-12-13 14:55:20 INFO        raise CalledProcessError(retcode, cmd)
2024-12-13 14:55:20 INFO    subprocess.CalledProcessError: Command '['/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/javac', '-classpath', 'lib/src/controller/java/libMatterTlv.jar:lib/third_party/java_deps/jsr305-3.0.2.jar:lib/src/controller/java/CHIPClusters.jar:lib/src/controller/java/CHIPClusterID.jar:lib/src/controller/java/android.jar', '-d', 'obj/src/controller/java/java/classes', '@gen/src/controller/java/java.sources', '-Werror', '-Xlint:all', '-Xlint:deprecation', '-parameters', '-Xlint:-options', '-source', '8', '-target', '8']' returned non-zero exit status 1.
2024-12-13 14:55:20 INFO    [23/32] ACTION //src/platform/android:java(//build/toolchain/android:android_arm64)
2024-12-13 14:56:31 INFO    [24/32] ACTION //:matter_build_venv._install_3p_deps(//third_party/pigweed/repo/pw_build/python_toolchain:python)
2024-12-13 14:56:31 INFO    ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/./scripts/build/build_examples.py", line 230, in <module>
    main(auto_envvar_prefix='CHIP')
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/./scripts/build/build_examples.py", line 220, in cmd_build
    context.obj.Build()
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/scripts/build/build/__init__.py", line 71, in Build
    builder.build()
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/scripts/build/builders/builder.py", line 99, in build
    self._build()
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/scripts/build/builders/android.py", line 446, in _build
    self._Execute(
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/scripts/build/builders/builder.py", line 104, in _Execute
    self._runner.Run(cmdarray, title=title)
  File "/media/it/2325A95CCDF15784/Android/connectedhomeip/scripts/build/runner/shell.py", line 73, in Run
    raise Exception('Command %r failed: %d' % (cmd, code))
Exception: Command ['ninja', '-C', '/media/it/2325A95CCDF15784/Android/connectedhomeip/out/android-arm64-chip-tool'] failed: 1

1.3-branch
FAILED: gen/src/controller/java/java.classlist

i am also facing the same issues,how can we solve this issue.

_Originally posted by @kiss2sky in https://github.com/project-chip/connectedhomeip/issues/26497#issuecomment-2540657501_

**Comment by yunhanw-google** [comment]
We have upgraded Gradle version 7.3.3 and JDK version 17.0 for android build, you can refer this PR for latest instructions, https://github.com/project-chip/connectedhomeip/pull/37368/files, if there is still problem, feel free to create a new issue, thanks
