### ISSUE TITLE
connectedhomeip Environment setup failing on Linux for Top of tree master

### ISSUE THREAD

**Issue by SaileeG** [project-chip/connectedhomeip#4315]
CHIP environment setup using 'source script/activate.sh' or 'source script/bootstrap.sh' on Top of tree master failing

ubuntu@ubuntu:~/chip1/connectedhomeip$ source scripts/activate.sh 

  WELCOME TO...

  ▄███▒  ░▓█  ░▓█ ░▓█▓ ▒█████▄
 ██▒ ▀█▒  ▒█   ▒█  ░█▒  ▒█░  █░
 █▓░      ▒██████  ░█▒  ▒█▄▄▄█░
 ▓█   █▒  ▒█   ▒█  ░█░  ▒█▀
 ░▓███▀  ░▓███░▓█▒ ░█░  ▒█

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...done
  Setting up Python environment.....[\]
ninja: Entering directory `/home/ubuntu/chip1/connectedhomeip/.environment/pigweed-venv/repo-3e76f0bc75f3bf878e929104ca465277'
[1/26] ACTION //pw_unit_test:unit_test_proto.python._gen(//pw_toolchain/dummy:dummy)
FAILED: gen/pw_unit_test/protos/pw_unit_test_proto/unit_test_pb2.py 
python ../../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/ --current-path /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_unit_test --default-toolchain=//pw_toolchain/dummy:dummy --current-toolchain=//pw_toolchain/dummy:dummy --capture-output -- /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py --language python --module-path /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_unit_test --include-file /home/ubuntu/chip1/connectedhomeip/.environment/pigweed-venv/repo-3e76f0bc75f3bf878e929104ca465277/gen/pw_unit_test/unit_test_proto_includes.txt --out-dir /home/ubuntu/chip1/connectedhomeip/.environment/pigweed-venv/repo-3e76f0bc75f3bf878e929104ca465277/gen/pw_unit_test/protos /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_unit_test/pw_unit_test_proto/unit_test.proto
Traceback (most recent call last):
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py", line 190, in <module>
    sys.exit(main())
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py", line 166, in main
    process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
[2/26] ACTION //pw_allocator/py:py.install(//pw_toolchain/dummy:dummy)
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 593, in <module>
    sys.exit(main())
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 585, in main
    return EnvSetup(**vars(parse())).setup()
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 307, in setup
    result = step()
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 417, in virtualenv
    env=self._env,
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 244, in install
    install_packages(gn_target)
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 229, in install_packages
    ins.read())
subprocess.CalledProcessError: Command '['ninja', '-C', '/home/ubuntu/chip1/connectedhomeip/.environment/pigweed-venv/repo-3e76f0bc75f3bf878e929104ca465277', ':python.install']' returned non-zero exit status 1
Error during bootstrap--see messages above.
ubuntu@ubuntu:~/chip1/connectedhomeip$ source scripts/bootstrap.sh 

  WELCOME TO...

  ▄███▒  ░▓█  ░▓█ ░▓█▓ ▒█████▄
 ██▒ ▀█▒  ▒█   ▒█  ░█▒  ▒█░  █░
 █▓░      ▒██████  ░█▒  ▒█▄▄▄█░
 ▓█   █▒  ▒█   ▒█  ░█░  ▒█▀
 ░▓███▀  ░▓███░▓█▒ ░█░  ▒█

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...done
  Setting up Python environment.....[/]
ninja: Entering directory `/home/ubuntu/chip1/connectedhomeip/.environment/pigweed-venv/repo-3e76f0bc75f3bf878e929104ca465277'
[1/25] ACTION //pw_unit_test:unit_test_proto.python._gen(//pw_toolchain/dummy:dummy)
FAILED: gen/pw_unit_test/protos/pw_unit_test_proto/unit_test_pb2.py 
python ../../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/ --current-path /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_unit_test --default-toolchain=//pw_toolchain/dummy:dummy --current-toolchain=//pw_toolchain/dummy:dummy --capture-output -- /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py --language python --module-path /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_unit_test --include-file /home/ubuntu/chip1/connectedhomeip/.environment/pigweed-venv/repo-3e76f0bc75f3bf878e929104ca465277/gen/pw_unit_test/unit_test_proto_includes.txt --out-dir /home/ubuntu/chip1/connectedhomeip/.environment/pigweed-venv/repo-3e76f0bc75f3bf878e929104ca465277/gen/pw_unit_test/protos /home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_unit_test/pw_unit_test_proto/unit_test.proto
Traceback (most recent call last):
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py", line 190, in <module>
    sys.exit(main())
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py", line 166, in main
    process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
[2/25] ACTION //pw_arduino_build/py:py.install(//pw_toolchain/dummy:dummy)
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 593, in <module>
    sys.exit(main())
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 585, in main
    return EnvSetup(**vars(parse())).setup()
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 307, in setup
    result = step()
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 417, in virtualenv
    env=self._env,
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 244, in install
    install_packages(gn_target)
  File "/home/ubuntu/chip1/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 229, in install_packages
    ins.read())
subprocess.CalledProcessError: Command '['ninja', '-C', '/home/ubuntu/chip1/connectedhomeip/.environment/pigweed-venv/repo-3e76f0bc75f3bf878e929104ca465277', ':python.install']' returned non-zero exit status 1
Error during bootstrap--see messages above.
ubuntu@ubuntu:~/chip1/connectedhomeip$

**Comment by SaileeG** [comment]
Initially bootstrap worked because the packages it needs (python, gn) were available on aarch64
Now bootstrap needs python, gn, and protoc where protoc is not installed by default during the env setup and need to be installed separately (sudo apt-get install protobuf-compiler). 

If you still hit other issues with CHIP env setup try removing .environment dir from ~/connectedhomeip/ and ~/connectedhomeip/third_party/pigweed/repo/ (Might not be present if you are setting up for first time and Bootstrap never completed) then in a new tab retry 'source script/bootstrap.sh'
