### ISSUE TITLE
python dev ctrl fails to install on Raspi Ubuntu

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#4454]
python dev ctrl fails to build on Raspi Ubuntu (both on server and desktop ubuntu versions on raspi), Failed building wheel for dbus-python.  while the same seem to work fine on x86 ubuntu 

**pip3 install out/host/controller/python/chip-0.0-cp38-cp38-linux_aarch64.whl 
Processing ./out/host/controller/python/chip-0.0-cp38-cp38-linux_aarch64.whl
Collecting dbus-python
  Downloading dbus-python-1.2.16.tar.gz (576 kB)
     |████████████████████████████████| 576 kB 3.0 MB/s 
Collecting pgi
  Downloading pgi-0.0.11.2.tar.gz (239 kB)
     |████████████████████████████████| 239 kB 8.1 MB/s 
Building wheels for collected packages: dbus-python, pgi
  Building wheel for dbus-python (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bgp_kby0
       cwd: /tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/
  Complete output (217 lines):
  running bdist_wheel
  running build
  creating /tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/build
  creating /tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/build/temp.linux-aarch64-3.8
  checking whether make supports nested variables... no
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking minix/config.h usability... no
  checking minix/config.h presence... no
  checking for minix/config.h... no
  checking whether it is safe to define __EXTENSIONS__... yes
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... no
  checking whether make supports the include directive... no
  checking whether UID '1000' is supported by ustar format... yes
  checking whether GID '1000' is supported by ustar format... yes
  checking how to create a ustar tar archive... gnutar
  checking dependency style of gcc... none
  checking build system type... aarch64-unknown-linux-gnu
  checking host system type... aarch64-unknown-linux-gnu
  checking for native Windows host... no
  checking how to print strings... printf
  checking for a sed that does not truncate output... /usr/bin/sed
  checking for fgrep... /usr/bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
  checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for ar... ar
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /usr/bin/dd
  checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
  checking for mt... mt
  checking if mt is a manifest tool... no
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... no
  checking for inline... inline
  checking for gawk... (cached) gawk
  checking for python... /home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/bin/python
  checking for a version of Python >= '2.1.0'... yes
  checking for a version of Python >= '2.7'... yes
  checking for the distutils Python package... yes
  checking for Python include path... -I/usr/include/python3.8
  checking for Python library path... -L/usr/lib -lpython3.8
  checking for Python site-packages path... /home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages
  checking python extra libraries... -lcrypt -lpthread -ldl  -lutil -lm -lm
  checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
  checking consistency of all components of python development environment... yes
  checking for python version... 3.8
  checking for python platform... linux
  checking for python script directory... ${prefix}/lib/python3.8/site-packages
  checking for python extension module directory... ${exec_prefix}/lib/python3.8/site-packages
  checking python module: sphinx... no
  checking python module: sphinx_rtd_theme... no
  checking for dbus-run-session... /usr/bin/dbus-run-session
  checking for pkg-config... /usr/bin/pkg-config
  checking pkg-config is at least version 0.9.0... yes
  checking for DBUS... yes
  checking for GLIB... yes
  checking whether C compiler accepts -Werror=unknown-warning-option... no
  checking whether C compiler accepts -Wno-suggest-attribute=format... yes
  checking whether C compiler accepts -fno-strict-aliasing... yes
  checking whether C compiler accepts -Wdeprecated-declarations... yes
  checking whether C compiler accepts -Wno-duplicated-branches... yes
  checking whether C compiler accepts -Wno-inline... yes
  checking whether C compiler accepts -Wno-redundant-decls... yes
  checking whether C compiler accepts -Wno-switch-default... yes
  checking whether C compiler accepts -Wno-write-strings... yes
  checking whether C compiler accepts -Wnested-externs... yes
  checking whether C compiler accepts -Wmissing-prototypes... yes
  checking whether C compiler accepts -Wstrict-prototypes... yes
  checking whether C compiler accepts -Wdeclaration-after-statement... yes
  checking whether C compiler accepts -Wimplicit-function-declaration... yes
  checking whether C compiler accepts -Wold-style-definition... yes
  checking whether C compiler accepts -Wjump-misses-init... yes
  checking whether C compiler accepts -Wall... yes
  checking whether C compiler accepts -Wextra... yes
  checking whether C compiler accepts -Wundef... yes
  checking whether C compiler accepts -Wwrite-strings... yes
  checking whether C compiler accepts -Wpointer-arith... yes
  checking whether C compiler accepts -Wmissing-declarations... yes
  checking whether C compiler accepts -Wredundant-decls... yes
  checking whether C compiler accepts -Wno-unused-parameter... yes
  checking whether C compiler accepts -Wno-missing-field-initializers... yes
  checking whether C compiler accepts -Wformat=2... yes
  checking whether C compiler accepts -Wcast-align... yes
  checking whether C compiler accepts -Wformat-nonliteral... yes
  checking whether C compiler accepts -Wformat-security... yes
  checking whether C compiler accepts -Wsign-compare... yes
  checking whether C compiler accepts -Wstrict-aliasing... yes
  checking whether C compiler accepts -Wshadow... yes
  checking whether C compiler accepts -Winline... yes
  checking whether C compiler accepts -Wpacked... yes
  checking whether C compiler accepts -Wmissing-format-attribute... yes
  checking whether C compiler accepts -Wmissing-noreturn... yes
  checking whether C compiler accepts -Winit-self... yes
  checking whether C compiler accepts -Wredundant-decls... (cached) yes
  checking whether C compiler accepts -Wmissing-include-dirs... yes
  checking whether C compiler accepts -Wunused-but-set-variable... yes
  checking whether C compiler accepts -Warray-bounds... yes
  checking whether C compiler accepts -Wreturn-type... yes
  checking whether C compiler accepts -Wswitch-enum... yes
  checking whether C compiler accepts -Wswitch-default... yes
  checking whether C compiler accepts -Wduplicated-cond... yes
  checking whether C compiler accepts -Wduplicated-branches... yes
  checking whether C compiler accepts -Wlogical-op... yes
  checking whether C compiler accepts -Wrestrict... yes
  checking whether C compiler accepts -Wnull-dereference... yes
  checking whether C compiler accepts -Wdouble-promotion... yes
  checking whether C compiler accepts -Wno-error=duplicated-branches... yes
  checking whether C compiler accepts -Wno-error=inline... yes
  checking whether C compiler accepts -Wno-error=redundant-decls... yes
  checking whether C compiler accepts -Wno-error=switch-default... yes
  checking whether C compiler accepts -Wno-error=write-strings... yes
  checking whether C compiler accepts -Wno-error=unused-parameter... yes
  checking whether C compiler accepts -Wno-error=missing-field-initializers... yes
  checking whether C compiler accepts -Werror=unknown-warning-option... (cached) no
  checking whether the linker accepts -Wl,--as-needed... yes
  checking whether the linker accepts -Wl,--as-needed... yes
  checking whether the linker accepts -Wl,-z,relro... yes
  checking whether the linker accepts -Wl,-z,relro... yes
  checking whether the linker accepts -Wl,-z,now... yes
  checking whether the linker accepts -Wl,-z,now... yes
  checking whether the linker accepts -Wl,-z,noexecstack... yes
  checking whether the linker accepts -Wl,-z,noexecstack... yes
  checking whether the linker accepts -Wl,--no-as-needed... yes
  checking whether the linker accepts -Wl,--fatal-warnings... yes
  checking whether the linker accepts -Wl,-fatal_warnings... no
  checking whether the linker accepts -Wl,--no-as-needed... yes
  checking that generated files are newer than configure... done
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating dbus-gmain/Makefile
  config.status: creating dbus-python.pc
  config.status: creating config.h
  config.status: executing depfiles commands
  config.status: error: in `/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/build/temp.linux-aarch64-3.8':
  config.status: error: Something went wrong bootstrapping makefile fragments
      for automatic dependency tracking.  Try re-running configure with the
      '--disable-dependency-tracking' option to at least be able to build
      the package (albeit without support for automatic dependency tracking).
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py", line 85, in <module>
      setup(
    File "/home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py", line 56, in run
      subprocess.check_call([
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/configure', '--disable-maintainer-mode', 'PYTHON=/home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/bin/python', '--prefix=/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/build/temp.linux-aarch64-3.8/prefix']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
  Building wheel for pgi (setup.py) ... done
  Created wheel for pgi: filename=pgi-0.0.11.2-py3-none-any.whl size=181783 sha256=53ef6f90963070274943f12da0004d8c2d25abf112f6bce1abbc8bd89dad045e
  Stored in directory: /home/ubuntu/.cache/pip/wheels/17/ee/39/e8766b9714c8a5534fa309b8b2a64f358196d8b951e573a153
Successfully built pgi
Failed to build dbus-python
Installing collected packages: pgi, dbus-python, chip
    Running setup.py install for dbus-python ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1orrdwrf/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/include/site/python3.8/dbus-python
         cwd: /tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/
    Complete output (219 lines):
    running install
    running build
    creating /tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/build
    creating /tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/build/temp.linux-aarch64-3.8
    checking whether make supports nested variables... no
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking minix/config.h usability... no
    checking minix/config.h presence... no
    checking for minix/config.h... no
    checking whether it is safe to define __EXTENSIONS__... yes
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... no
    checking whether make supports the include directive... no
    checking whether UID '1000' is supported by ustar format... yes
    checking whether GID '1000' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking dependency style of gcc... none
    checking build system type... aarch64-unknown-linux-gnu
    checking host system type... aarch64-unknown-linux-gnu
    checking for native Windows host... no
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /usr/bin/dd
    checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for inline... inline
    checking for gawk... (cached) gawk
    checking for python... /home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/bin/python
    checking for a version of Python >= '2.1.0'... yes
    checking for a version of Python >= '2.7'... yes
    checking for the distutils Python package... yes
    checking for Python include path... -I/usr/include/python3.8
    checking for Python library path... -L/usr/lib -lpython3.8
    checking for Python site-packages path... /home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages
    checking python extra libraries... -lcrypt -lpthread -ldl  -lutil -lm -lm
    checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    checking consistency of all components of python development environment... yes
    checking for python version... 3.8
    checking for python platform... linux
    checking for python script directory... ${prefix}/lib/python3.8/site-packages
    checking for python extension module directory... ${exec_prefix}/lib/python3.8/site-packages
    checking python module: sphinx... no
    checking python module: sphinx_rtd_theme... no
    checking for dbus-run-session... /usr/bin/dbus-run-session
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for DBUS... yes
    checking for GLIB... yes
    checking whether C compiler accepts -Werror=unknown-warning-option... no
    checking whether C compiler accepts -Wno-suggest-attribute=format... yes
    checking whether C compiler accepts -fno-strict-aliasing... yes
    checking whether C compiler accepts -Wdeprecated-declarations... yes
    checking whether C compiler accepts -Wno-duplicated-branches... yes
    checking whether C compiler accepts -Wno-inline... yes
    checking whether C compiler accepts -Wno-redundant-decls... yes
    checking whether C compiler accepts -Wno-switch-default... yes
    checking whether C compiler accepts -Wno-write-strings... yes
    checking whether C compiler accepts -Wnested-externs... yes
    checking whether C compiler accepts -Wmissing-prototypes... yes
    checking whether C compiler accepts -Wstrict-prototypes... yes
    checking whether C compiler accepts -Wdeclaration-after-statement... yes
    checking whether C compiler accepts -Wimplicit-function-declaration... yes
    checking whether C compiler accepts -Wold-style-definition... yes
    checking whether C compiler accepts -Wjump-misses-init... yes
    checking whether C compiler accepts -Wall... yes
    checking whether C compiler accepts -Wextra... yes
    checking whether C compiler accepts -Wundef... yes
    checking whether C compiler accepts -Wwrite-strings... yes
    checking whether C compiler accepts -Wpointer-arith... yes
    checking whether C compiler accepts -Wmissing-declarations... yes
    checking whether C compiler accepts -Wredundant-decls... yes
    checking whether C compiler accepts -Wno-unused-parameter... yes
    checking whether C compiler accepts -Wno-missing-field-initializers... yes
    checking whether C compiler accepts -Wformat=2... yes
    checking whether C compiler accepts -Wcast-align... yes
    checking whether C compiler accepts -Wformat-nonliteral... yes
    checking whether C compiler accepts -Wformat-security... yes
    checking whether C compiler accepts -Wsign-compare... yes
    checking whether C compiler accepts -Wstrict-aliasing... yes
    checking whether C compiler accepts -Wshadow... yes
    checking whether C compiler accepts -Winline... yes
    checking whether C compiler accepts -Wpacked... yes
    checking whether C compiler accepts -Wmissing-format-attribute... yes
    checking whether C compiler accepts -Wmissing-noreturn... yes
    checking whether C compiler accepts -Winit-self... yes
    checking whether C compiler accepts -Wredundant-decls... (cached) yes
    checking whether C compiler accepts -Wmissing-include-dirs... yes
    checking whether C compiler accepts -Wunused-but-set-variable... yes
    checking whether C compiler accepts -Warray-bounds... yes
    checking whether C compiler accepts -Wreturn-type... yes
    checking whether C compiler accepts -Wswitch-enum... yes
    checking whether C compiler accepts -Wswitch-default... yes
    checking whether C compiler accepts -Wduplicated-cond... yes
    checking whether C compiler accepts -Wduplicated-branches... yes
    checking whether C compiler accepts -Wlogical-op... yes
    checking whether C compiler accepts -Wrestrict... yes
    checking whether C compiler accepts -Wnull-dereference... yes
    checking whether C compiler accepts -Wdouble-promotion... yes
    checking whether C compiler accepts -Wno-error=duplicated-branches... yes
    checking whether C compiler accepts -Wno-error=inline... yes
    checking whether C compiler accepts -Wno-error=redundant-decls... yes
    checking whether C compiler accepts -Wno-error=switch-default... yes
    checking whether C compiler accepts -Wno-error=write-strings... yes
    checking whether C compiler accepts -Wno-error=unused-parameter... yes
    checking whether C compiler accepts -Wno-error=missing-field-initializers... yes
    checking whether C compiler accepts -Werror=unknown-warning-option... (cached) no
    checking whether the linker accepts -Wl,--as-needed... yes
    checking whether the linker accepts -Wl,--as-needed... yes
    checking whether the linker accepts -Wl,-z,relro... yes
    checking whether the linker accepts -Wl,-z,relro... yes
    checking whether the linker accepts -Wl,-z,now... yes
    checking whether the linker accepts -Wl,-z,now... yes
    checking whether the linker accepts -Wl,-z,noexecstack... yes
    checking whether the linker accepts -Wl,-z,noexecstack... yes
    checking whether the linker accepts -Wl,--no-as-needed... yes
    checking whether the linker accepts -Wl,--fatal-warnings... yes
    checking whether the linker accepts -Wl,-fatal_warnings... no
    checking whether the linker accepts -Wl,--no-as-needed... yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating dbus-gmain/Makefile
    config.status: creating dbus-python.pc
    config.status: creating config.h
    config.status: executing depfiles commands
    config.status: error: in `/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/build/temp.linux-aarch64-3.8':
    config.status: error: Something went wrong bootstrapping makefile fragments
        for automatic dependency tracking.  Try re-running configure with the
        '--disable-dependency-tracking' option to at least be able to build
        the package (albeit without support for automatic dependency tracking).
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py", line 85, in <module>
        setup(
      File "/home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py", line 56, in run
        subprocess.check_call([
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/configure', '--disable-maintainer-mode', 'PYTHON=/home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/bin/python', '--prefix=/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/build/temp.linux-aarch64-3.8/prefix']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vs_8gjp3/dbus-python_0d18bc5798974885b2ed8594239d89d2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1orrdwrf/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/chipCode/chip_0121/connectedhomeip/.environment/pigweed-venv/include/site/python3.8/dbus-python Check the logs for full command output.**

**Comment by cjandhyala** [comment]
Close the issue , for raspi we need to install pydbus. Verified both on Ubuntu desktop and server raspi.
