### ISSUE TITLE
python controller ble scan returns NoneType

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#5028]
chip-device-ctrl > ble-scan -t 120 CHIP-3840
2021-02-25 17:51:01,595 ChipBLEMgr   INFO     use default adapter
2021-02-25 17:51:01,840 ChipBLEMgr   INFO     scanning started
2021-02-25 17:51:02,591 ChipBLEMgr   INFO     Name            = Family Room TV
2021-02-25 17:51:02,591 ChipBLEMgr   INFO     ID              = ad13e92b-b0fa-39ca-b3aa-64c01ccb39cc
2021-02-25 17:51:02,593 ChipBLEMgr   INFO     RSSI            = -88
2021-02-25 17:51:02,594 ChipBLEMgr   INFO     Address         = 5F:33:85:F6:6C:DC
2021-02-25 17:51:02,599 ChipBLEMgr   INFO     Adv UUID        = 0000fea0-0000-1000-8000-00805f9b34fb
2021-02-25 17:51:02,601 ChipBLEMgr   INFO     Adv Data        = 03fa8fca59300e6d2020203fff
2021-02-25 17:51:02,601 ChipBLEMgr   INFO     
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/chip/ChipBluezMgr.py", line 896, in running_thread
    target(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/chip/ChipBluezMgr.py", line 957, in scan_bg_implementation
    scanned_peripheral_list = self.adapter.find_devices(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/chip/ChipBluezMgr.py", line 280, in find_devices
    for i in device.uuids:
TypeError: 'NoneType' object is not iterable

**Comment by woody-apple** [comment]
Is this resolved? Please reopen if not.
