### ISSUE TITLE
Error when source script/activate.sh

### ISSUE THREAD

**Issue by yuzibo** [project-chip/connectedhomeip#5486]
#### Problem
On PI 4 pulled latest code, I encounter the error:
```bash
ubuntu@pi-2:~/git/connectedhomeip$ source scripts/activate.sh

  WELCOME TO...
...
  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...[\]Failed to initialize CIPD. Run `CIPD_HTTP_USER_AGENT_PREFIX=pigweed-infra/tools/bbe291b3ee01bfec87366b7c45db7656b7a9cd43/manual /home/ubuntu/git/connectedhomeip/.environment/cipd/cipd selfupdate -version-file '/home/ubuntu/git/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/.cipd_version'` to diagnose if this is persistent.           Traceback (most recent call last):
  File "/home/ubuntu/git/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 596, in <module>
    sys.exit(main())
  File "/home/ubuntu/git/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 588, in main
    return EnvSetup(**vars(parse())).setup()
  File "/home/ubuntu/git/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 306, in setup
    result = step()
  File "/home/ubuntu/git/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 364, in cipd
    cipd_client = cipd_wrapper.init(install_dir, silent=True)
  File "/home/ubuntu/git/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 298, in init
    bootstrap(client, silent)
  File "/home/ubuntu/git/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 262, in bootstrap
    tmp.write(client_bytes())
  File "/home/ubuntu/git/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 246, in client_bytes
    raise Exception('failed to download client')
Exception: failed to download client
Error during bootstrap--see messages above.

```

My network is good when trying it.

**Comment by yuzibo** [comment]
I tracked it here:
```python
...
 try:
            conn.request('GET', path)
            res = conn.getresponse()
            # Have to read the response before making a new request, so make
            # sure we always read it.
            content = res.read()
            #print("content  %s" % content)
...
``` 
The output is " no such package: infra/tools/cipd/linux-armv7l"

**Comment by yuzibo** [comment]
Sorry, Raspberry Pi 4B must choose aarch64.
