### ISSUE TITLE
ESP32 reports 'UDP endpoint pool FULL'

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#5759]
#### Problem
Apparently MDNS uses too many UDP endpoints or we fail to properly release them.

Managed to attach a debugger to a DevKit-C. The stack trace when reporting the error is:

```
(gdb) bt
#0  chip::Inet::InetLayer::NewUDPEndPoint (this=0x3ffcb850 <chip::DeviceLayer::InetLayer>, retEndPoint=0x3ffcb330 <chip::Mdns::(anonymous namespace)::gAdvertiser+64>)
    at ../../../../../config/esp32/third_party/connectedhomeip/src/inet/InetLayer.cpp:656
#1  0x4012f1fb in mdns::Minimal::ServerBase::Listen (this=0x3ffcb2fc <chip::Mdns::(anonymous namespace)::gAdvertiser+12>, inetLayer=0x3ffcb850 <chip::DeviceLayer::InetLayer>, it=0x3ffd8e28, port=5353)
    at ../../../../../config/esp32/third_party/connectedhomeip/src/lib/mdns/minimal/Server.cpp:153
#2  0x40127247 in chip::Mdns::(anonymous namespace)::AdvertiserMinMdns::Start (this=0x3ffcb2f0 <chip::Mdns::(anonymous namespace)::gAdvertiser>, inetLayer=0x3ffcb850 <chip::DeviceLayer::InetLayer>, port=5353)
    at ../../../../../config/esp32/third_party/connectedhomeip/src/lib/mdns/Advertiser_ImplMinimalMdns.cpp:364
#3  0x400fe139 in chip::app::Mdns::StartServer () at /workspaces/connectedhomeip/examples/all-clusters-app/esp32/third_party/connectedhomeip/src/app/server/Mdns.cpp:134
#4  0x40104123 in DeviceCallbacks::DeviceEventCallback (this=<optimized out>, event=0x3ffd8f10, arg=1073480096) at /workspaces/connectedhomeip/examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp:70
#5  0x40174056 in chip::DeviceManager::CHIPDeviceManager::CommonDeviceEventHandler (event=0x3ffd8f10, arg=1073480096) at /workspaces/connectedhomeip/examples/all-clusters-app/esp32/main/CHIPDeviceManager.cpp:47
#6  0x40174bb0 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::DispatchEventToApplication (this=<optimized out>, event=0x3ffd8f10)
    at /workspaces/connectedhomeip/examples/all-clusters-app/esp32/third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl.cpp:274
#7  0x401299e4 in chip::DeviceLayer::Internal::GenericPlatformManagerImpl<chip::DeviceLayer::PlatformManagerImpl>::_DispatchEvent (this=0x3ffcb8e0 <chip::DeviceLayer::PlatformManagerImpl::sInstance>, event=0x3ffd8f10)
    at /workspaces/connectedhomeip/examples/all-clusters-app/esp32/third_party/connectedhomeip/src/include/platform/CHIPDeviceEvent.h:408
#8  0x40129bde in chip::DeviceLayer::PlatformManager::DispatchEvent (event=0x3ffd8f10, this=0x3ffcb8e0 <chip::DeviceLayer::PlatformManagerImpl::sInstance>)
    at /workspaces/connectedhomeip/examples/all-clusters-app/esp32/third_party/connectedhomeip/src/include/platform/PlatformManager.h:234
#9  chip::DeviceLayer::Internal::GenericPlatformManagerImpl_FreeRTOS<chip::DeviceLayer::PlatformManagerImpl>::_RunEventLoop (this=0x3ffcb8e0 <chip::DeviceLayer::PlatformManagerImpl::sInstance>)
    at /workspaces/connectedhomeip/examples/all-clusters-app/esp32/third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl_FreeRTOS.cpp:175
#10 0x40129c08 in chip::DeviceLayer::PlatformManager::RunEventLoop (this=0x3ffcb8e0 <chip::DeviceLayer::PlatformManagerImpl::sInstance>)
    at /workspaces/connectedhomeip/examples/all-clusters-app/esp32/third_party/connectedhomeip/src/include/platform/PlatformManager.h:204
```

**Comment by gjc13** [comment]
Verified issue gone after merging https://github.com/project-chip/connectedhomeip/pull/5839
