### ISSUE TITLE
chip fail to compile in mac regarding pigweed change

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#6883]
#### Problem
yunhanw-macbookpro1:connectedhomeip yunhanw$ git clean -dfx
Removing .environment/
Removing .idea/
Removing integrations/mobly/chip_mobly.egg-info/
Removing out/
yunhanw-macbookpro1:connectedhomeip yunhanw$ ./gn_build.sh 
.--------------------------------
-- Environment bringup
'--------------------------------

NB: If this fails run "source scripts/bootstrap.sh"

  WELCOME TO...

  ▄███▒  ░▓█  ░▓█ ░▓█▓ ▒█████▄
 ██▒ ▀█▒  ▒█   ▒█  ░█▒  ▒█░  █░
 █▓░      ▒██████  ░█▒  ▒█▄▄▄█░
 ▓█   █▒  ▒█   ▒█  ░█░  ▒█▀
 ░▓███▀  ░▓███░▓█▒ ░█░  ▒█

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...done
  Setting up Python environment.....[\]
ERROR at //third_party/pigweed/repo/pw_protobuf_compiler/proto.gni:24:1: Unable to load "/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo/pw_protobuf_compiler/toolchain.gni".
import("toolchain.gni")
^---------------------
See //third_party/pigweed/repo/pw_unit_test/BUILD.gn:19:1: whence it was imported.
import("$dir_pw_protobuf_compiler/proto.gni")
^-------------------------------------------
See //third_party/pigweed/repo/pw_build/python.gni:168:25: which caused the file to be included.
      _python_deps += [ get_label_info(dep, "label_with_toolchain") ]
                        ^-----------------------------------------
['gn', 'gen', '/Users/yunhanw/workspace/connectedhomeip/out', '--args=dir_pigweed="/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo"']

Traceback (most recent call last):
  File "/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 214, in install_packages
    subprocess.check_call(gn_cmd,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/Users/yunhanw/workspace/connectedhomeip/out', '--args=dir_pigweed="/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 652, in <module>
    sys.exit(main())
  File "/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 644, in main
    return EnvSetup(**vars(parse())).setup()
  File "/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 342, in setup
    result = step(spin)
  File "/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 450, in virtualenv
    if not virtualenv_setup.install(
  File "/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 251, in install
    install_packages(gn_target)
  File "/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 221, in install_packages
    raise subprocess.CalledProcessError(err.returncode, err.cmd,
subprocess.CalledProcessError: Command '['gn', 'gen', '/Users/yunhanw/workspace/connectedhomeip/out', '--args=dir_pigweed="/Users/yunhanw/workspace/connectedhomeip/third_party/pigweed/repo"']' returned non-zero exit status 1.
 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by yunhanw-google** [comment]
i think this issue happens when

git fetch origin

git reset --hard origin/master

git clean -dfx

./gn_build.sh

after delete the whole workspace, re-download chip, the issue disappear.
