### ISSUE TITLE
Endpoint error in cirque device controller test script

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7219]
Run device controller script, it seems on/off cluster's endpoint is changed in lighting example app, we may need to update device controller script as well.

CHIP:DMG: InvokeCommand =
CHIP:DMG: {
CHIP:DMG: 	CommandList =
CHIP:DMG: 	[
CHIP:DMG: 		CommandDataElement =
CHIP:DMG: 		{
CHIP:DMG: 			CommandPath =
CHIP:DMG: 			{
CHIP:DMG: 				EndpointId = 0x0,
CHIP:DMG: 				ClusterId = 0x6,
CHIP:DMG: 				CommandId = 0x1,
CHIP:DMG: 			},
CHIP:DMG: 			
CHIP:DMG: 			StatusElement =
CHIP:DMG: 			{
CHIP:DMG: 				GeneralCode = 0xd,
CHIP:DMG: 				ProtocolId = 0x0,
CHIP:DMG: 				protocolCode = 0xffff,
CHIP:DMG: 			},
CHIP:DMG: 			
CHIP:DMG: 		},
CHIP:DMG: 		
CHIP:DMG: 	],
CHIP:DMG: 	
CHIP:DMG: }

2021-05-28 05:49:14,934 [CHIPInteractionModelTest] INFO device: CHIPEndDevice(9279888a...) exec: ot-ctl extpanid
2021-05-28 05:49:15,000 [CHIPInteractionModelTest] INFO command return code: 0
2021-05-28 05:49:15,000 [CHIPInteractionModelTest] INFO command output: 
fedcba9876543210
Done

2021-05-28 05:49:15,000 [CHIPInteractionModelTest] INFO checking device log for CHIPEndDevice(9279888a...)
2021-05-28 05:49:15,018 [CHIPInteractionModelTest] INFO Finding string: "LightingManager::InitiateAction(ON_ACTION)"
2021-05-28 05:49:15,018 [CHIPInteractionModelTest] INFO Not found
2021-05-28 05:49:15,018 [CHIPInteractionModelTest] ERROR Datamodel test failed: cannot find matching string from device 9279888a4f230bef1df3bf0e1f313c0a3122249907a8df9e1ca65fee35032ac9
Traceback (most recent call last):
  File "/Users/yunhanw/workspace/connectedhomeip/src/test_driver/linux-cirque/helper/CHIPTestBase.py", line 64, in run_test
    self.test_routine()
  File "/Users/yunhanw/workspace/connectedhomeip/src/test_driver/linux-cirque/test-mobile-device.py", line 66, in test_routine
    self.run_controller_test()
  File "/Users/yunhanw/workspace/connectedhomeip/src/test_driver/linux-cirque/test-mobile-device.py", line 98, in run_controller_test
    self.assertTrue(self.sequenceMatch(self.get_device_log(device_id).decode('utf-8'), ["LightingManager::InitiateAction(ON_ACTION)", "LightingManager::InitiateAction(OFF_ACTION)"]),
  File "/Users/yunhanw/workspace/connectedhomeip/src/test_driver/linux-cirque/helper/CHIPTestBase.py", line 289, in assertTrue
    raise AssertionError
AssertionError
2021-05-28 05:49:15,046 [CHIPInteractionModelTest] INFO destroying home: 6cc60f88-9640-4ef9-8cf0-14fd402947f

**Comment by erjiaqing** [comment]
Already fixed.
