### ISSUE TITLE
scripts/bootstrap.sh execution error while building the ESP32 temperature-measurement-app

### ISSUE THREAD

**Issue by jayjayhust** [project-chip/connectedhomeip#7354]
While i'm trying to build the ESP32 in docker follow the steps below: 
(1) docker run --rm -v E:/MATTER/connectedhomeip:/project -w /project -it connectedhomeip/chip-build-esp32 
(2) source ./scripts/bootstrap.sh
(3) source ./scripts/activate.sh
(4) cd examples/temperature-measurement-app/esp32 
(5) source idf.sh 
(6) idf make menuconfig Demo->Device Type -> ESP32-DevKitC Demo->Rendezvous Mode->BLE 
(7) idf make all  

During step2, it always failed with "**ConnectionRefusedError: [Errno 111] Connection refused**"

------------------------------------------------ Log start ---------------------------------------------
root@9ceba836e995:/project# source scripts/bootstrap.sh

  WELCOME TO...

  ▄███▒  ░▓█  ░▓█ ░▓█▓ ▒█████▄
 ██▒ ▀█▒  ▒█   ▒█  ░█▒  ▒█░  █░
 █▓░      ▒██████  ░█▒  ▒█▄▄▄█░
 ▓█   █▒  ▒█   ▒█  ░█░  ▒█▀
 ░▓███▀  ░▓███░▓█▒ ░█░  ▒█

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...Traceback (most recent call last):
  File "/project/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 610, in <module>
    sys.exit(main())
  File "/project/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 602, in main
    return EnvSetup(**vars(parse())).setup()
  File "/project/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 331, in setup
    result = step(spin)
  File "/project/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 390, in cipd
    cipd_client = cipd_wrapper.init(install_dir, silent=True)
  File "/project/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 335, in init
    bootstrap(client, silent)
  File "/project/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 294, in bootstrap
    tmp.write(client_bytes())
  File "/project/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 231, in client_bytes
    conn.request('GET', path)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
**ConnectionRefusedError: [Errno 111] Connection refused**
![2c7ea1dcff09e3ed565fb106594d49c](https://user-images.githubusercontent.com/78330209/120616248-a9035c00-c48b-11eb-83c8-03cfa293ecfa.png)
------------------------------------------------ Log end ---------------------------------------------

Firstly i suppose it's the proxy setting problem, but after i added the proxy setting while starting the docker:
**docker run --env HTTP_PROXY="http://127.0.0.1:19180" --env HTTPS_PROXY="https://127.0.0.1:19180" --rm -v E:/MATTER/connectedhomeip:/project -w /project -it connectedhomeip/chip-build-esp32**
the error still showed up, can anyone give a hint on this issue? Have been stucked on this issue for weeks :(

**Comment by sweetymhaiske** [comment]
@jayjayhust Are you still facing the issue?

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
