### ISSUE TITLE
[cirque-test] Log checking pattern should be updated after #7299

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7417]
#### Problem
2021-06-06 07:13:18,382 [CHIPInteractionModelTest] INFO checking device log for CHIPEndDevice(61259268...)
2021-06-06 07:13:18,406 [CHIPInteractionModelTest] INFO Finding string: "LightingManager::InitiateAction(ON_ACTION)"
2021-06-06 07:13:18,406 [CHIPInteractionModelTest] INFO Found at index=37346
2021-06-06 07:13:18,407 [CHIPInteractionModelTest] INFO Finding string: "LightingManager::InitiateAction(OFF_ACTION)"
2021-06-06 07:13:18,407 [CHIPInteractionModelTest] INFO Found at index=39724
2021-06-06 07:13:18,407 [CHIPInteractionModelTest] INFO Finding string: "No Cluster 0x6 on Endpoint 0xe9"
2021-06-06 07:13:18,407 [CHIPInteractionModelTest] INFO Found at index=41837
2021-06-06 07:13:18,407 [CHIPInteractionModelTest] INFO Finding string: "CHIP:ZCL:   ClusterId: 0x0028
CHIP:ZCL:   attributeId: 0x0001
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:ZCL:   attributeType: 0x42
CHIP:ZCL:   value: TEST_VENDOR"
2021-06-06 07:13:18,407 [CHIPInteractionModelTest] INFO Not found
2021-06-06 07:13:18,407 [CHIPInteractionModelTest] ERROR Vendor Name was not found 612592683b146031e59f6fda320260b909c5edfef1359bf7556f49a7655f0166
Traceback (most recent call last):
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/helper/CHIPTestBase.py", line 64, in run_test
    self.test_routine()
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/test-mobile-device.py", line 66, in test_routine
    self.run_controller_test()
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/test-mobile-device.py", line 110, in run_controller_test
    self.assertTrue(self.sequenceMatch(ret['output'],
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/helper/CHIPTestBase.py", line 289, in assertTrue
    raise AssertionError
AssertionError

**Comment by erjiaqing** [comment]
Caused by log update
