### ISSUE TITLE
Error on flashing_script for esp32

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#8357]
#### Problem
bootloader_offset was changed to default None. It appears to be changed to an sdkconfig parameter, but CONFIG_BOOTLOADER_OFFSET_IN_FLASH does not appear in my sdkconfig. The result is a python exception.

Traceback (most recent call last):
  File "examples/all-clusters-app/esp32/build/chip-all-clusters-app.flash.py", line 23, in <module>
    sys.exit(esp32_firmware_utils.Flasher(**DEFAULTS).flash_command(sys.argv))
  File "/workspaces/connectedhomeip/examples/all-clusters-app/esp32/build/firmware_utils.py", line 399, in flash_command
    return self.parse_argv(argv).actions().status()
  File "/workspaces/connectedhomeip/examples/all-clusters-app/esp32/build/esp32_firmware_utils.py", line 442, in actions
    if self.flash(flash).err:
  File "/workspaces/connectedhomeip/examples/all-clusters-app/esp32/build/esp32_firmware_utils.py", line 351, in flash
    return self.run_tool(
  File "/workspaces/connectedhomeip/examples/all-clusters-app/esp32/build/firmware_utils.py", line 204, in run_tool
    arguments = self.format_command(arguments, opt=option_map)
  File "/workspaces/connectedhomeip/examples/all-clusters-app/esp32/build/firmware_utils.py", line 329, in format_command
    result += self.format_command(i, args, opt)
  File "/workspaces/connectedhomeip/examples/all-clusters-app/esp32/build/firmware_utils.py", line 329, in format_command
    result += self.format_command(i, args, opt)
  File "/workspaces/connectedhomeip/examples/all-clusters-app/esp32/build/firmware_utils.py", line 364, in format_command
    raise ValueError('Unknown: {}'.format(template))
ValueError: Unknown: None
The terminal process "/bin/bash '-c', 'examples/all-clusters-app/esp32/build/chip-all-clusters-app.flash.py'" failed to launch (exit code: 1).

 #### Proposed Solution
Add back the default, or specifically error when this value isn't in the sdkconfig with instructions on how to get it there (re-running menuconfig does not work for me)

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
