### ISSUE TITLE
Resolve command fails with python controller.

### ISSUE THREAD

**Issue by sweetymhaiske** [project-chip/connectedhomeip#9264]
#### Problem
* While trying commissioning, the `resolve` command fails.
* Log
```
chip-device-ctrl > resolve 0 12344321
[1629980681.624083][269739:269747] CHIP:DL: Avahi resolve failed
[1629980681.624162][269739:269747] CHIP:DIS: Node ID resolved failed with ../../src/platform/Linux/MdnsImpl.cpp:676: CHIP Error 0x000000AC: Internal error
[1629980681.624186][269739:269747] CHIP:CTL: Error resolving node id: ../../src/platform/Linux/MdnsImpl.cpp:676: CHIP Error 0x000000AC: Internal error
Failed to update node address: 172
Exception ignored on calling ctypes callback function: <function ChipDeviceController.__init__.<locals>.HandleAddressUpdateComplete at 0x7f754516eaf0>
Traceback (most recent call last):
  File "/home/sweety/Espressif/connectedhomeip/out/python_env/lib/python3.8/site-packages/chip/ChipDeviceCtrl.py", line 114, in HandleAddressUpdateComplete
    self.state = DCState.IDLEHandleCommissioningComplete
  File "/usr/lib/python3.8/enum.py", line 346, in __getattr__
    raise AttributeError(name) from None
AttributeError: IDLEHandleCommissioningComplete

```

**Comment by jonsmirl** [comment]
I believe this is due the the compressed fabric ID change.  My ESP is advertising:
enp3s0f1 IPv4 7B42B41C2A4BA147-000000000002104E
convert 7B42B41C2A4BA147 to decimal, 8881859448189722951
now resolve in python app
resolve 8881859448189722951 135246

It still hangs, but hang is different now...
chip-device-ctrl > resolve 8881859448189722951 135246
[1630189491.896084][2830509:2830517] CHIP:DL: ResolveNodeId 7B42B41C2A4BA147-000000000002104E
[1630189492.225321][2830509:2830517] CHIP:DL: Avahi resolve found
[1630189492.225401][2830509:2830517] CHIP:DIS: Node ID resolved for 0x000000000002104E to [192.168.1.35]:5540
Failed to update node address: 72
Exception ignored on calling ctypes callback function: <function ChipDeviceController.__init__.<locals>.HandleAddressUpdateComplete at 0x7ffa81190790>
Traceback (most recent call last):
  File "/home/jonsmirl/aosp/connectedhomeip/out/python_env/lib/python3.8/site-packages/chip/ChipDeviceCtrl.py", line 114, in HandleAddressUpdateComplete
    self.state = DCState.IDLEHandleCommissioningComplete
  File "/usr/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: IDLEHandleCommissioningComplete
[1630189492.226450][2830509:2830517] CHIP:CTL: OperationalDiscoveryComplete for device ID 135246

**Comment by jonsmirl** [comment]
I finally got it working.  If you rebuild anything you need to erase flash and start the whole process over.
The previous failure is because I did not erase the ESP32 flash.

chip-device-ctrl
chip-device-ctrl > ble-scan
chip-device-ctrl > connect -ble 3840 20202021 135246
chip-device-ctrl > zcl NetworkCommissioning AddWiFiNetwork 135246 0 0 ssid=str:TESTSSID credentials=str:TESTPASSWD breadcrumb=0 timeoutMs=1000
chip-device-ctrl > zcl NetworkCommissioning EnableNetwork 135246 0 0 networkID=str:TESTSSID breadcrumb=0 timeoutMs=1000
chip-device-ctrl > close-ble
chip-device-ctrl > getfabricid
Get fabric ID complete
Raw Fabric ID: 0x0000000000000000 (0)
Compressed Fabric ID: 0x72d633bc4bed9623 (8274858249160594979)

Now use the decimal fabric ID...
chip-device-ctrl > resolve 8274858249160594979 135246
which works!

chip-device-ctrl > zcl OnOff Off 135246 1 0
[1630213138.534262][3247557:3247565] CHIP:CTL: GetDevice1
[1630213138.534300][3247557:3247565] CHIP:CTL: GetDevice4
[1630213138.534313][3247557:3247565] CHIP:CTL: GetDevice -err
[1630213138.534820][3247557:3247565] CHIP:CTL: LoadSecureSessionParametersIfNeeded
[1630213138.534939][3247557:3247565] CHIP:IN: Encrypted message 0x16efc48 to 0x000000000002104E of type 8 and protocolId 5 on exchange 39024.
[1630213138.534971][3247557:3247565] CHIP:IN: Sending msg 0x16efc48 to 0x000000000002104E at utc time: 363312982 msec
[1630213138.534989][3247557:3247565] CHIP:IN: Sending secure msg on generic transport
[1630213138.535073][3247557:3247565] CHIP:IN: Secure msg send status ../../src/inet/IPEndPointBasis.cpp:915: Success
[1630213138.678538][3247557:3247565] CHIP:EM: Received message of type 0x09 with vendorId 0x0000 and protocolId 0x0005 on exchange 39024
SetCommandIndexStatus commandHandle=1 commandIndex=1
[1630213138.679009][3247557:3247565] CHIP:ZCL: DefaultResponse:
[1630213138.679029][3247557:3247565] CHIP:ZCL:   Transaction: 0x7fc429b83fb8
[1630213138.679045][3247557:3247565] CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
[1630213138.679171][3247557:3247565] CHIP:IN: Encrypted message 0x7fc421ffa1d0 to 0x000000000002104E of type 16 and protocolId 0 on exchange 39024.
[1630213138.679201][3247557:3247565] CHIP:IN: Sending msg 0x7fc421ffa1d0 to 0x000000000002104E at utc time: 363313127 msec
[1630213138.679215][3247557:3247565] CHIP:IN: Sending secure msg on generic transport
Received command status response:
[1630213138.679287][3247557:3247565] CHIP:IN: Secure msg send status ../../src/inet/IPEndPointBasis.cpp:915: Success
Container: 
    ProtocolId = 5
    ProtocolCode = 0
    EndpointId = 1
    ClusterId = 6
    CommandId = 0
    CommandIndex = 1
chip-device-ctrl > 

esp is advertising....
+ enp3s0f1 IPv6 72D633BC4BED9623-000000000002104E             _matter._tcp         local
+ enp3s0f1 IPv4 72D633BC4BED9623-000000000002104E             _matter._tcp         local

**Comment by jonsmirl** [comment]
I will say the ESP32 onboarding process is very fragile. For example if the BLE session encounters any errors, the ESP will stop advertising which mean you can't restart the on-boarding process. Only recovery is to reboot. This needs to be fixed so that errors in the ble onboarding will reset things to BLE advertising mode.

**Comment by jonsmirl** [comment]
This compressed fabric id procedure is very cumbersome. Every time you restart the python app the fabric ID changes. When the compressed fabric ID changes, you can no longer talk to your existing ESP nodes. So then you have to erase them and redo the BLE binding procedure.  There need to be some way to declare a stable compressed fabric ID.

**Comment by sweetymhaiske** [comment]
Closing this issue. The usage of the resolve command is added here https://github.com/project-chip/connectedhomeip/pull/9294/files#diff-fe684b29832a9dd6e243129ddea9784e0da588e6c94e1d7223362cf07418801fL206-R212
