### ISSUE TITLE
resolve command failing sporadic on TE5 branch

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#9473]
On TE5 branch (commit 6db59aa066599f9e5967e900c809a85037a56e8b (HEAD -> local_te5, origin/test_event_5), When provisioning raspi accessory using python controller, provisioning is failing at resolve API sporadically. While in the device log we see the device advertising the operational ID

Python Controller side log
---------------------------
[1630694211.926916][2573518:2573526] CHIP:EM: Removed CHIP MsgId:00000005 from RetransTable
[1630694211.926977][2573518:2573526] CHIP:DMG: InvokeCommand =
[1630694211.927015][2573518:2573526] CHIP:DMG: {
[1630694211.927043][2573518:2573526] CHIP:DMG: 	CommandList =
[1630694211.927083][2573518:2573526] CHIP:DMG: 	[
[1630694211.927117][2573518:2573526] CHIP:DMG: 		CommandDataElement =
[1630694211.927155][2573518:2573526] CHIP:DMG: 		{
[1630694211.927185][2573518:2573526] CHIP:DMG: 			CommandPath =
[1630694211.927233][2573518:2573526] CHIP:DMG: 			{
[1630694211.927282][2573518:2573526] CHIP:DMG: 				EndpointId = 0x0,
[1630694211.927334][2573518:2573526] CHIP:DMG: 				ClusterId = 0x3e,
[1630694211.927378][2573518:2573526] CHIP:DMG: 				CommandId = 0xb,
[1630694211.927418][2573518:2573526] CHIP:DMG: 			},
[1630694211.927468][2573518:2573526] CHIP:DMG: 			
[1630694211.927503][2573518:2573526] CHIP:DMG: 			StatusElement =
[1630694211.927547][2573518:2573526] CHIP:DMG: 			{
[1630694211.927591][2573518:2573526] CHIP:DMG: 				GeneralCode = 0x0,
[1630694211.927637][2573518:2573526] CHIP:DMG: 				ProtocolId = 0x5,
[1630694211.927687][2573518:2573526] CHIP:DMG: 				protocolCode = 0x0,
[1630694211.927725][2573518:2573526] CHIP:DMG: 			},
[1630694211.927771][2573518:2573526] CHIP:DMG: 			
[1630694211.927810][2573518:2573526] CHIP:DMG: 		},
[1630694211.927854][2573518:2573526] CHIP:DMG: 		
[1630694211.927887][2573518:2573526] CHIP:DMG: 	],
[1630694211.927932][2573518:2573526] CHIP:DMG: 	
[1630694211.927962][2573518:2573526] CHIP:DMG: }
SetCommandIndexStatus commandHandle=1 commandIndex=1
[1630694211.928437][2573518:2573526] CHIP:ZCL: DefaultResponse:
[1630694211.928471][2573518:2573526] CHIP:ZCL:   Transaction: 0xffffa71cf958
[1630694211.928527][2573518:2573526] CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
[1630694211.928569][2573518:2573526] CHIP:CTL: Device confirmed that it has received the root certificate
[1630694211.928600][2573518:2573526] CHIP:CTL: Sending operational certificate chain to the device
[1630694211.928665][2573518:2573526] CHIP:DMG: ICR moving to [Initialize]
[1630694211.928725][2573518:2573526] CHIP:DMG: ICR moving to [AddCommand]
[1630694211.928925][2573518:2573526] CHIP:IN: Secure message was encrypted: Msg ID 7
[1630694211.928969][2573518:2573526] CHIP:IN: Encrypted message 0xa5193b8 to 0x0000000000A98F1E of type 8 and protocolId 5 on exchange 52831.
[1630694211.929009][2573518:2573526] CHIP:IN: Sending msg 0xa5193b8 to 0x0000000000A98F1E at utc time: 333936204 msec
[1630694211.929041][2573518:2573526] CHIP:IN: Sending secure msg on generic transport
[1630694211.929163][2573518:2573526] CHIP:IN: Secure msg send status ../../src/inet/IPEndPointBasis.cpp:917: Success
[1630694211.929213][2573518:2573526] CHIP:DMG: ICR moving to [   Sending]
[1630694211.929246][2573518:2573526] CHIP:CTL: Sent operational certificate to the device
[1630694211.929356][2573518:2573526] CHIP:DMG: ICR moving to [Uninitiali]
[1630694211.929399][2573518:2573526] CHIP:EM: Sending Standalone Ack for MsgId:00000004
[1630694211.929476][2573518:2573526] CHIP:IN: Secure message was encrypted: Msg ID 8
[1630694211.929514][2573518:2573526] CHIP:IN: Encrypted message 0xffff977fcb10 to 0x0000000000A98F1E of type 16 and protocolId 0 on exchange 52830.
[1630694211.929553][2573518:2573526] CHIP:IN: Sending msg 0xffff977fcb10 to 0x0000000000A98F1E at utc time: 333936205 msec
[1630694211.929584][2573518:2573526] CHIP:IN: Sending secure msg on generic transport
[1630694211.929676][2573518:2573526] CHIP:IN: Secure msg send status ../../src/inet/IPEndPointBasis.cpp:917: Success
[1630694211.929719][2573518:2573526] CHIP:EM: Flushed pending ack for MsgId:00000004
[1630694211.944653][2573518:2573526] CHIP:EM: Received message of type 0x09 with vendorId 0x0000 and protocolId 0x0005 on exchange 52831
[1630694211.944727][2573518:2573526] CHIP:EM: Rxd Ack; Removing MsgId:00000007 from Retrans Table
[1630694211.944754][2573518:2573526] CHIP:EM: Removed CHIP MsgId:00000007 from RetransTable
[1630694211.944818][2573518:2573526] CHIP:DMG: InvokeCommand =
[1630694211.944850][2573518:2573526] CHIP:DMG: {
[1630694211.944869][2573518:2573526] CHIP:DMG: 	CommandList =
[1630694211.944899][2573518:2573526] CHIP:DMG: 	[
[1630694211.944926][2573518:2573526] CHIP:DMG: 		CommandDataElement =
[1630694211.944964][2573518:2573526] CHIP:DMG: 		{
[1630694211.944996][2573518:2573526] CHIP:DMG: 			CommandPath =
[1630694211.945032][2573518:2573526] CHIP:DMG: 			{
[1630694211.945073][2573518:2573526] CHIP:DMG: 				EndpointId = 0x0,
[1630694211.945112][2573518:2573526] CHIP:DMG: 				ClusterId = 0x3e,
[1630694211.945147][2573518:2573526] CHIP:DMG: 				CommandId = 0x8,
[1630694211.945175][2573518:2573526] CHIP:DMG: 			},
[1630694211.945212][2573518:2573526] CHIP:DMG: 			
[1630694211.945243][2573518:2573526] CHIP:DMG: 			CommandData = 
[1630694211.945276][2573518:2573526] CHIP:DMG: 			{
[1630694211.945311][2573518:2573526] CHIP:DMG: 				0x0 = 0, 
[1630694211.945344][2573518:2573526] CHIP:DMG: 				0x1 = 3, 
[1630694211.945381][2573518:2573526] CHIP:DMG: 				0x2 = [
[1630694211.945413][2573518:2573526] CHIP:DMG: 					
[1630694211.945442][2573518:2573526] CHIP:DMG: 			]
[1630694211.945470][2573518:2573526] CHIP:DMG: 			},
[1630694211.945502][2573518:2573526] CHIP:DMG: 		},
[1630694211.945541][2573518:2573526] CHIP:DMG: 		
[1630694211.945568][2573518:2573526] CHIP:DMG: 	],
[1630694211.945599][2573518:2573526] CHIP:DMG: 	
[1630694211.945623][2573518:2573526] CHIP:DMG: }
[1630694211.945680][2573518:2573526] CHIP:ZCL: Received Cluster Command: Cluster=3e Command=8 Endpoint=0
[1630694211.945720][2573518:2573526] CHIP:ZCL: NOCResponse:
[1630694211.945744][2573518:2573526] CHIP:ZCL:   StatusCode: 0
[1630694211.945766][2573518:2573526] CHIP:ZCL:   FabricIndex: 3
[1630694211.945788][2573518:2573526] CHIP:ZCL:   DebugText: 0
[1630694211.945816][2573518:2573526] CHIP:CTL: Device returned status 0 on receiving the NOC
[1630694211.945843][2573518:2573526] CHIP:CTL: Operational credentials provisioned on device 0xa4be110
[1630694211.945868][2573518:2573526] CHIP:CTL: Enabling Network
[1630694211.945972][2573518:2573526] CHIP:DMG: ICR moving to [Initialize]
[1630694211.946024][2573518:2573526] CHIP:DMG: ICR moving to [AddCommand]
[1630694211.946153][2573518:2573526] CHIP:IN: Secure message was encrypted: Msg ID 9
[1630694211.946189][2573518:2573526] CHIP:IN: Encrypted message 0xa5193b8 to 0x0000000000A98F1E of type 8 and protocolId 5 on exchange 52832.
[1630694211.946222][2573518:2573526] CHIP:IN: Sending msg 0xa5193b8 to 0x0000000000A98F1E at utc time: 333936221 msec
[1630694211.946247][2573518:2573526] CHIP:IN: Sending secure msg on generic transport
[1630694211.946377][2573518:2573526] CHIP:IN: Secure msg send status ../../src/inet/IPEndPointBasis.cpp:917: Success
[1630694211.946444][2573518:2573526] CHIP:DMG: ICR moving to [   Sending]
[1630694211.946649][2573518:2573526] CHIP:DMG: ICR moving to [Uninitiali]
[1630694211.946711][2573518:2573526] CHIP:EM: Sending Standalone Ack for MsgId:00000005
[1630694211.946822][2573518:2573526] CHIP:IN: Secure message was encrypted: Msg ID 10
[1630694211.946876][2573518:2573526] CHIP:IN: Encrypted message 0xffff977fcb10 to 0x0000000000A98F1E of type 16 and protocolId 0 on exchange 52831.
[1630694211.946933][2573518:2573526] CHIP:IN: Sending msg 0xffff977fcb10 to 0x0000000000A98F1E at utc time: 333936222 msec
[1630694211.946976][2573518:2573526] CHIP:IN: Sending secure msg on generic transport
[1630694211.947106][2573518:2573526] CHIP:IN: Secure msg send status ../../src/inet/IPEndPointBasis.cpp:917: Success
[1630694211.947170][2573518:2573526] CHIP:EM: Flushed pending ack for MsgId:00000005
[1630694211.950034][2573518:2573526] CHIP:EM: Received message of type 0x09 with vendorId 0x0000 and protocolId 0x0005 on exchange 52832
[1630694211.950134][2573518:2573526] CHIP:EM: Rxd Ack; Removing MsgId:00000009 from Retrans Table
[1630694211.950181][2573518:2573526] CHIP:EM: Removed CHIP MsgId:00000009 from RetransTable
[1630694211.950255][2573518:2573526] CHIP:DMG: InvokeCommand =
[1630694211.950308][2573518:2573526] CHIP:DMG: {
[1630694211.950352][2573518:2573526] CHIP:DMG: 	CommandList =
[1630694211.950404][2573518:2573526] CHIP:DMG: 	[
[1630694211.950451][2573518:2573526] CHIP:DMG: 		CommandDataElement =
[1630694211.950510][2573518:2573526] CHIP:DMG: 		{
[1630694211.950564][2573518:2573526] CHIP:DMG: 			CommandPath =
[1630694211.950627][2573518:2573526] CHIP:DMG: 			{
[1630694211.950692][2573518:2573526] CHIP:DMG: 				EndpointId = 0x0,
[1630694211.950759][2573518:2573526] CHIP:DMG: 				ClusterId = 0x31,
[1630694211.950828][2573518:2573526] CHIP:DMG: 				CommandId = 0xc,
[1630694211.950889][2573518:2573526] CHIP:DMG: 			},
[1630694211.950948][2573518:2573526] CHIP:DMG: 			
[1630694211.950997][2573518:2573526] CHIP:DMG: 			StatusElement =
[1630694211.951053][2573518:2573526] CHIP:DMG: 			{
[1630694211.951110][2573518:2573526] CHIP:DMG: 				GeneralCode = 0x0,
[1630694211.951170][2573518:2573526] CHIP:DMG: 				ProtocolId = 0x5,
[1630694211.951229][2573518:2573526] CHIP:DMG: 				protocolCode = 0x0,
[1630694211.951284][2573518:2573526] CHIP:DMG: 			},
[1630694211.951336][2573518:2573526] CHIP:DMG: 			
[1630694211.951377][2573518:2573526] CHIP:DMG: 		},
[1630694211.951430][2573518:2573526] CHIP:DMG: 		
[1630694211.951476][2573518:2573526] CHIP:DMG: 	],
[1630694211.951536][2573518:2573526] CHIP:DMG: 	
[1630694211.951580][2573518:2573526] CHIP:DMG: }
SetCommandIndexStatus commandHandle=1 commandIndex=1
[1630694211.952154][2573518:2573526] CHIP:ZCL: DefaultResponse:
[1630694211.952206][2573518:2573526] CHIP:ZCL:   Transaction: 0xffffa71cf958
[1630694211.952246][2573518:2573526] CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
[1630694211.952296][2573518:2573526] CHIP:CTL: Received success response 0x3194

[1630694211.952352][2573518:2573526] CHIP:CTL: Finding node on operational network
[1630694211.954501][2573518:2573526] CHIP:DMG: ICR moving to [Uninitiali]
[1630694211.954789][2573518:2573526] CHIP:EM: Sending Standalone Ack for MsgId:00000006
[1630694211.954964][2573518:2573526] CHIP:IN: Secure message was encrypted: Msg ID 11
[1630694211.955025][2573518:2573526] CHIP:IN: Encrypted message 0xffff977fcb10 to 0x0000000000A98F1E of type 16 and protocolId 0 on exchange 52832.
[1630694211.955088][2573518:2573526] CHIP:IN: Sending msg 0xffff977fcb10 to 0x0000000000A98F1E at utc time: 333936230 msec
[1630694211.955134][2573518:2573526] CHIP:IN: Sending secure msg on generic transport
[1630694211.955303][2573518:2573526] CHIP:IN: Secure msg send status ../../src/inet/IPEndPointBasis.cpp:917: Success
[1630694211.955370][2573518:2573526] CHIP:EM: Flushed pending ack for MsgId:00000006

[1630694216.955071][2573518:2573526] CHIP:DL: Avahi resolve failed
[1630694216.955190][2573518:2573526] CHIP:DIS: Node ID resolved failed with ../../src/platform/Linux/MdnsImpl.cpp:676: CHIP Error 0x000000AC: Internal error
[1630694216.955259][2573518:2573526] CHIP:CTL: Error resolving node id: ../../src/platform/Linux/MdnsImpl.cpp:676: CHIP Error 0x000000AC: Internal error
Failed to update node address: 172
Exception ignored on calling ctypes callback function: <function ChipDeviceController.__init__.<locals>.HandleAddressUpdateComplete at 0xffffa71fb310>
Traceback (most recent call last):
  File "/home/pi/code/chipCode/chip_0902/connectedhomeip/out/python_env/lib/python3.8/site-packages/chip/ChipDeviceCtrl.py", line 114, in HandleAddressUpdateComplete
    self.state = DCState.IDLEHandleCommissioningComplete
  File "/usr/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: IDLEHandleCommissioningComplete
[1630694241.862772][2573518:2573526] CHIP:CTL: SyncSetKeyValue on StartKeyID
[1630694241.862961][2573518:2573526] CHIP:CTL: SyncSetKeyValue on PairedDevicea98f1e
Failed to establish secure session to device: 50
CHIP Error 0x00000032: Timeout
chip-device-ctrl > 

Deviceside log
---------------

[1630700567.177157][2442:2442] CHIP:DIS: Advertise operational node 0000000000000000-0000000000BC5C02
[1630700567.177202][2442:2442] CHIP:DIS: CHIP minimal mDNS configured as 'Operational device'.
[1630700567.177525][2442:2442] CHIP:DIS: Using wifi MAC for hostname
[1630700567.177551][2442:2442] CHIP:DIS: Advertise operational node 0000000000000000-0000000000BC614E
[1630700567.177589][2442:2442] CHIP:DIS: CHIP minimal mDNS configured as 'Operational device'.
[1630700567.177906][2442:2442] CHIP:DIS: Using wifi MAC for hostname
[1630700567.177931][2442:2442] CHIP:DIS: Advertise operational node 0000000000000000-00000000075BCD15
[1630700567.177967][2442:2442] CHIP:DIS: CHIP minimal mDNS configured as 'Operational device'.
[1630700567.177991][2442:2442] CHIP:DIS: Operational advertising enabled
[1630700567.178029][2442:2442] CHIP:DMG: ICR moving to [AddCommand]
[1630700567.178074][2442:2442] CHIP:EM: Piggybacking Ack for MsgId:00000009 with msg

**Comment by woody-apple** [comment]
Given this is an older issue, is this complete at this point? If not, please re-open.
