### ISSUE TITLE
python controller crashes when calling setup-payload command

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#9624]
Steps to reproduce. 

1. Launch python controller and run the below command. 
setup-payload parse-manual
Traceback (most recent call last):
  File "/home/ubuntu/chipCode/chip_0902/connectedhomeip/out/python_env/bin/chip-device-ctrl", line 1044, in <module>
    main()
  File "/home/ubuntu/chipCode/chip_0902/connectedhomeip/out/python_env/bin/chip-device-ctrl", line 1036, in main
    devMgrCmd.cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/ubuntu/chipCode/chip_0902/connectedhomeip/out/python_env/bin/chip-device-ctrl", line 371, in do_setuppayload
    SetupPayload().ParseManualPairingCode(arglist[1]).Print()
IndexError: list index out of range

**Comment by woody-apple** [comment]
Closing, as this likely doesn't happen anymore. Please re-open if this still persists.
